import type { FileBundle, FileManifest, FileProgress, SaveResult } from '../../shared/files';
export interface RecoveryInfo {task:string;token:string;transport:string;point:{fileIndex:number;offset:string;bytes:string;chain:string;root:string;chunkBytes:number};summary:NonNullable<PeerState['summary']>;expiresAt:number;checkpointMiB:number;automaticRetries:number;role?:string;kind?:string;destinationName?:string}
export interface PeerState { recovery?:RecoveryInfo|null;recoverySaved?:boolean;retryCount?:number;speedBytes?:number;etaSeconds?:number|null;history?:RecoveryInfo[];destinationName?:string;verifiedBytes?:string; transport?:string;share?:{id:string;token?:string;expiresAt:number;maxDownloads:number;downloads:number}|null; status: string; role: string; code: string; error: string; name: string | null; note: string; summary: {files:number;directories:number;totalBytes:string;maxFileBytes:string;manifestHash:string}|null; manifest: FileManifest|null; progress: FileProgress; result: SaveResult|null; rateKbps:number|null; link:string; expiresAt?:number; partialDirectory?:string; completedFiles?:number }
export class DirectPeer { constructor(options:{ticket:(role:string,transport?:string)=>Promise<{ticket:string;networks:string;signalPath:string}>;scope?:unknown;onState?:(state:PeerState)=>void}); state:PeerState; update(patch:Partial<PeerState>):void; active():boolean; configureRecovery(owner:string,remember?:boolean):void; forgetRecovery(task:string,role:string):void; pause():void; resume(bundle?:FileBundle|null,record?:RecoveryInfo|null):Promise<void>; create(bundle:FileBundle,note?:string,rateKbps?:number|null,transport?:string):Promise<void>; join(code:string,rateKbps?:number|null,transport?:string):Promise<void>; claimShare():void; confirm():void; cancel():void; stop():void; save(kind:string):Promise<void> }
export function readPairCode(value:string):string;
export function shareLink(location:{href:string},code:string):string;

export function readShareToken(value:string):string;
export function transferHint(value:string):string|null;
