import type { FileBundle, ManifestEntry, FileOptions, SaveResult } from '../../shared/files';
export function browserFileSupport(scope?: unknown): { directoryRead: boolean; directoryWrite: boolean; streamSave: boolean };
export function writeChunks(chunks: AsyncIterable<Uint8Array>, writable: unknown, options?: FileOptions): Promise<string>;
export function boundedBlob(chunks: AsyncIterable<Uint8Array>, expectedBytes: string | bigint, options?: FileOptions & { maximumBytes?: number; type?: string }): Promise<Blob>;
export function offerBlob(blob: Blob, name: string, scope?: unknown): SaveResult;
export function exportName(suffix?: string): string;
export function saveZip(bundle: FileBundle, options?: FileOptions & { scope?: unknown }): Promise<SaveResult>;
export function saveSingle(bundle: FileBundle, entry: ManifestEntry, options?: FileOptions & { scope?: unknown }): Promise<SaveResult>;
export function writeDirectory(bundle: FileBundle, root: unknown, options?: FileOptions & { containerName?: string }): Promise<SaveResult>;
export function saveDirectory(bundle: FileBundle, options?: FileOptions & { scope?: unknown }): Promise<SaveResult>;
