<script setup lang="ts">
import { ArrowRight, Eye, EyeOff, LogIn } from '@lucide/vue'
import { safeApplicationRedirect } from '~~/shared/utils/redirect'
import { apiErrorDetails } from '~/utils/interaction-errors'
const props=defineProps<{locale:'zh'|'en'}>(); const route=useRoute(); const router=useRouter(); const auth=useAuthSession()
const USERNAME_PATTERN=/^[A-Za-z][A-Za-z0-9._-]{2,63}$/u; const usernameQuery=route.query.username
const username=ref(typeof usernameQuery==='string'&&USERNAME_PATTERN.test(usernameQuery)?usernameQuery.toLowerCase():''); const password=ref(''); const showPassword=ref(false); const error=ref<{message:string;requestId:string|null}|null>(null)
const labels=computed(()=>props.locale==='zh'?{username:'用户名',password:'密码',submit:'登录',pending:'正在登录…',register:'创建账号',forgot:'当前版本未开放在线找回密码，请联系管理员。',fallback:'登录失败，请稍后重试。'}:{username:'Username',password:'Password',submit:'Sign in',pending:'Signing in…',register:'Create account',forgot:'Online password recovery is not enabled yet. Contact an administrator.',fallback:'Sign-in failed. Please try again.'})
async function enterTarget(target:string):Promise<void> { if(target==='/admin'||target.startsWith('/admin/')){window.location.replace(target);return} await router.replace(target) }
async function submit():Promise<void>{ error.value=null; try { const session=await auth.login({username:username.value,password:password.value}); if(!session.authenticated)throw new Error('Login endpoint returned an anonymous session'); const accountPath=`/${props.locale}/account`; const passwordPath=`/${props.locale}/account/password`; const requested=safeApplicationRedirect(route.query.next,accountPath); const target=session.user.mustChangePassword?`${passwordPath}?next=${encodeURIComponent(requested)}`:requested; await enterTarget(target) } catch(cause){const details=apiErrorDetails(cause,labels.value.fallback); error.value={message:details.message,requestId:details.requestId}} }
</script>
<template><form class="public-form" @submit.prevent="submit"><PublicAuthStatusMessage v-if="error" tone="error" :request-id="error.requestId">{{ error.message }}</PublicAuthStatusMessage><label class="public-field"><span>{{ labels.username }}</span><input v-model.trim="username" name="username" type="text" autocomplete="username" maxlength="64" required autofocus></label><label class="public-field"><span>{{ labels.password }}</span><span class="public-password-field"><input v-model="password" name="password" :type="showPassword?'text':'password'" autocomplete="current-password" maxlength="256" required><button type="button" :aria-label="showPassword?'Hide password':'Show password'" @click="showPassword=!showPassword"><EyeOff v-if="showPassword" :size="18" /><Eye v-else :size="18" /></button></span></label><button class="public-form-submit" type="submit" :disabled="auth.pending.value"><LogIn :size="18" />{{ auth.pending.value?labels.pending:labels.submit }}</button><div class="public-form-links"><NuxtLink :to="{path:`/${locale}/register`,query:route.query.next?{next:route.query.next}:{}}">{{ labels.register }}<ArrowRight :size="15" /></NuxtLink><small>{{ labels.forgot }}</small></div></form></template>
