export type FieldType = "text" | "textarea" | "number" | "date" | "datetime" | "email" | "url" | "select" | "file";

export type FieldMeta = {
  name: string;
  label: string;
  type?: FieldType;
  choices?: string[];
  suggest?: boolean;
  list?: boolean;
};

export type TableMeta = {
  name: string;
  label: string;
  titleField: string;
  fields: FieldMeta[];
  listFields: string[];
  searchFields: string[];
  duplicateFields?: string[];
};

const visibilityChoices = ["public", "authenticated", "staff", "owner", "hidden"];

export const tables: TableMeta[] = [
  {
    name: "site_settings",
    label: "Site settings",
    titleField: "site_name",
    listFields: ["site_name", "hero_title", "is_active", "updated_at"],
    searchFields: ["site_name", "hero_title", "seo_keywords"],
    fields: [
      { name: "config_name", label: "Config name", suggest: true },
      { name: "is_active", label: "Active", type: "number" },
      { name: "site_name", label: "Site name" },
      { name: "site_name_en", label: "Site name EN" },
      { name: "hero_title", label: "Hero title" },
      { name: "hero_title_en", label: "Hero title EN" },
      { name: "hero_subtitle", label: "Hero subtitle", type: "textarea" },
      { name: "hero_subtitle_en", label: "Hero subtitle EN", type: "textarea" },
      { name: "logo_key", label: "Logo key", type: "file" },
      { name: "favicon_key", label: "Favicon key", type: "file" },
      { name: "og_image_key", label: "OG image key", type: "file" },
      { name: "seo_title", label: "SEO title" },
      { name: "seo_description", label: "SEO description", type: "textarea" },
      { name: "seo_keywords", label: "SEO keywords" },
      { name: "footer_text", label: "Footer HTML", type: "textarea" },
      { name: "footer_text_en", label: "Footer HTML EN", type: "textarea" },
      { name: "homepage_profile_id", label: "Homepage profile ID", type: "number" },
    ],
  },
  {
    name: "global_settings",
    label: "Global settings",
    titleField: "id",
    listFields: ["translation_provider", "enable_site_translator", "allow_public_registration", "updated_at"],
    searchFields: ["translation_provider", "notify_email"],
    fields: [
      { name: "translation_provider", label: "Translation provider", type: "select", choices: ["gtranslate", "mymemory", "google_cloud"] },
      { name: "translation_default_source", label: "Translation source" },
      { name: "translation_default_target", label: "Translation target" },
      { name: "enable_site_translator", label: "Enable site translator", type: "number" },
      { name: "allow_public_registration", label: "Allow public registration", type: "number" },
      { name: "publication_metadata_provider", label: "Publication metadata provider", type: "select", choices: ["crossref", "openalex", "crossref_openalex", "openalex_crossref"] },
      { name: "publication_metadata_email", label: "Metadata email", type: "email" },
      { name: "crossref_endpoint", label: "Crossref endpoint", type: "url" },
      { name: "openalex_endpoint", label: "OpenAlex endpoint", type: "url" },
      { name: "publication_metadata_overwrite", label: "Overwrite fields", type: "number" },
      { name: "upload_max_size_mb", label: "Max upload MB", type: "number" },
      { name: "upload_allowed_extensions", label: "Allowed extensions", type: "textarea" },
      { name: "news_pdf_engine", label: "News PDF engine", type: "select", choices: ["pdfjs", "native"] },
      { name: "news_pdf_allow_download", label: "Allow PDF download", type: "number" },
      { name: "news_pdf_watermark", label: "PDF watermark" },
      { name: "allow_anonymous_messages", label: "Allow anonymous messages", type: "number" },
      { name: "notify_email", label: "Notify email", type: "email" },
    ],
  },
  {
    name: "navigation_items",
    label: "Navigation",
    titleField: "title",
    listFields: ["title", "title_en", "url_name", "display_order", "enabled"],
    searchFields: ["title", "title_en", "url_name"],
    duplicateFields: ["title", "url_name"],
    fields: [
      { name: "title", label: "Title" },
      { name: "title_en", label: "Title EN" },
      { name: "url_name", label: "URL name", suggest: true },
      { name: "fragment", label: "Fragment" },
      { name: "display_order", label: "Order", type: "number" },
      { name: "enabled", label: "Enabled", type: "number" },
    ],
  },
  {
    name: "profiles",
    label: "Profiles",
    titleField: "name",
    listFields: ["name", "title", "organization", "email", "is_active"],
    searchFields: ["name", "name_en", "title", "organization", "email"],
    duplicateFields: ["name", "name_en", "email"],
    fields: [
      { name: "name", label: "Name" },
      { name: "name_en", label: "Name EN" },
      { name: "title", label: "Title", suggest: true },
      { name: "title_en", label: "Title EN" },
      { name: "organization", label: "Organization", suggest: true },
      { name: "organization_en", label: "Organization EN" },
      { name: "lab", label: "Lab", suggest: true },
      { name: "lab_en", label: "Lab EN" },
      { name: "avatar_key", label: "Avatar key", type: "file" },
      { name: "email", label: "Email", type: "email" },
      { name: "phone", label: "Phone" },
      { name: "office", label: "Office", suggest: true },
      { name: "office_en", label: "Office EN" },
      { name: "bio", label: "Bio", type: "textarea" },
      { name: "bio_en", label: "Bio EN", type: "textarea" },
      { name: "education", label: "Education", type: "textarea" },
      { name: "experience", label: "Experience", type: "textarea" },
      { name: "recruiting", label: "Recruiting", type: "textarea" },
      { name: "orcid", label: "ORCID" },
      { name: "personal_homepage", label: "Homepage", type: "url" },
      { name: "google_scholar", label: "Google Scholar", type: "url" },
      { name: "researchgate", label: "ResearchGate", type: "url" },
      { name: "dblp", label: "DBLP", type: "url" },
      { name: "github", label: "GitHub", type: "url" },
      { name: "cnki", label: "CNKI", type: "url" },
      { name: "contact_visibility", label: "Contact visibility", type: "select", choices: visibilityChoices },
      { name: "is_active", label: "Active", type: "number" },
      { name: "sort_order", label: "Sort order", type: "number" },
    ],
  },
  {
    name: "research_interests",
    label: "Research interests",
    titleField: "name",
    listFields: ["name", "name_en", "sort_order"],
    searchFields: ["name", "name_en", "description"],
    duplicateFields: ["name", "name_en"],
    fields: [
      { name: "name", label: "Name", suggest: true },
      { name: "name_en", label: "Name EN" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "description_en", label: "Description EN", type: "textarea" },
      { name: "sort_order", label: "Sort order", type: "number" },
    ],
  },
  {
    name: "publications",
    label: "Publications",
    titleField: "title",
    listFields: ["title", "authors", "year", "venue", "doi", "visibility", "is_featured"],
    searchFields: ["title", "authors", "venue", "doi", "citation"],
    duplicateFields: ["title", "doi"],
    fields: [
      { name: "title", label: "Title" },
      { name: "source_citation", label: "Source citation / DOI / BibTeX", type: "textarea" },
      { name: "citation_source_format", label: "Source format", type: "select", choices: ["auto", "doi", "bibtex", "gbt", "apa", "ieee"] },
      { name: "citation_style", label: "Citation style", type: "select", choices: ["gbt", "apa", "ieee"] },
      { name: "authors", label: "Authors", type: "textarea" },
      { name: "venue", label: "Venue", suggest: true },
      { name: "year", label: "Year", type: "number" },
      { name: "volume", label: "Volume" },
      { name: "issue", label: "Issue" },
      { name: "pages", label: "Pages" },
      { name: "doi", label: "DOI" },
      { name: "url", label: "URL", type: "url" },
      { name: "pdf_key", label: "PDF key", type: "file" },
      { name: "bibtex", label: "BibTeX", type: "textarea" },
      { name: "citation", label: "Citation", type: "textarea" },
      { name: "publication_type", label: "Type", suggest: true },
      { name: "author_role", label: "Author role", type: "select", choices: ["", "first", "corresponding", "other"] },
      { name: "index_type", label: "Index / partition", suggest: true },
      { name: "abstract", label: "Abstract", type: "textarea" },
      { name: "keywords", label: "Keywords" },
      { name: "pdf_visibility", label: "PDF visibility", type: "select", choices: visibilityChoices },
      { name: "visibility", label: "Visibility", type: "select", choices: visibilityChoices },
      { name: "is_featured", label: "Featured", type: "number" },
      { name: "sort_order", label: "Sort order", type: "number" },
    ],
  },
  {
    name: "projects",
    label: "Projects",
    titleField: "name",
    listFields: ["name", "source", "project_number", "status", "visibility", "is_featured"],
    searchFields: ["name", "source", "fund_name", "project_number", "principal", "summary"],
    duplicateFields: ["name", "project_number", "contract_number"],
    fields: [
      { name: "name", label: "Name" },
      { name: "source", label: "Source", suggest: true },
      { name: "fund_name", label: "Fund", suggest: true },
      { name: "project_number", label: "Project number" },
      { name: "category", label: "Category", suggest: true },
      { name: "principal", label: "Principal", suggest: true },
      { name: "members", label: "Members" },
      { name: "start_date", label: "Start date", type: "date" },
      { name: "end_date", label: "End date", type: "date" },
      { name: "status", label: "Status", suggest: true },
      { name: "amount", label: "Amount", type: "number" },
      { name: "amount_visibility", label: "Amount visibility", type: "select", choices: visibilityChoices },
      { name: "contract_number", label: "Contract number" },
      { name: "summary", label: "Summary", type: "textarea" },
      { name: "visibility", label: "Visibility", type: "select", choices: visibilityChoices },
      { name: "is_featured", label: "Featured", type: "number" },
      { name: "sort_order", label: "Sort order", type: "number" },
    ],
  },
  {
    name: "patents",
    label: "Patents / software copyrights",
    titleField: "name",
    listFields: ["name", "country", "patent_type", "grant_number", "legal_status"],
    searchFields: ["name", "name_en", "application_number", "grant_number", "inventors", "owner"],
    duplicateFields: ["name", "application_number", "grant_number"],
    fields: [
      { name: "name", label: "Name" },
      { name: "name_en", label: "Name EN" },
      { name: "country", label: "Country", suggest: true },
      { name: "patent_type", label: "Type", suggest: true },
      { name: "application_number", label: "Application number" },
      { name: "grant_number", label: "Grant number" },
      { name: "application_date", label: "Application date", type: "date" },
      { name: "grant_date", label: "Grant date", type: "date" },
      { name: "inventors", label: "Inventors" },
      { name: "owner", label: "Owner", suggest: true },
      { name: "legal_status", label: "Legal status", suggest: true },
      { name: "summary", label: "Summary", type: "textarea" },
      { name: "certificate_key", label: "Certificate key", type: "file" },
      { name: "visibility", label: "Visibility", type: "select", choices: visibilityChoices },
      { name: "is_featured", label: "Featured", type: "number" },
      { name: "sort_order", label: "Sort order", type: "number" },
    ],
  },
  {
    name: "students",
    label: "Students",
    titleField: "name",
    listFields: ["name", "degree", "category", "grade", "status", "visibility"],
    searchFields: ["name", "name_en", "student_id", "degree", "category", "direction", "email"],
    duplicateFields: ["name", "student_id", "email"],
    fields: [
      { name: "name", label: "Name" },
      { name: "name_en", label: "Name EN" },
      { name: "avatar_key", label: "Avatar key", type: "file" },
      { name: "student_id", label: "Student ID" },
      { name: "degree", label: "Degree", suggest: true },
      { name: "category", label: "Category", suggest: true },
      { name: "grade", label: "Grade", suggest: true },
      { name: "direction", label: "Direction", suggest: true },
      { name: "status", label: "Status", suggest: true },
      { name: "email", label: "Email", type: "email" },
      { name: "phone", label: "Phone" },
      { name: "homepage", label: "Homepage", type: "url" },
      { name: "enrollment_date", label: "Enrollment date", type: "date" },
      { name: "graduation_date", label: "Graduation date", type: "date" },
      { name: "destination", label: "Destination", suggest: true },
      { name: "awards", label: "Awards", type: "textarea" },
      { name: "contact_visibility", label: "Contact visibility", type: "select", choices: visibilityChoices },
      { name: "visibility", label: "Visibility", type: "select", choices: visibilityChoices },
      { name: "is_featured", label: "Featured", type: "number" },
      { name: "sort_order", label: "Sort order", type: "number" },
    ],
  },
  {
    name: "student_category_displays",
    label: "Student category display",
    titleField: "label",
    listFields: ["label", "label_en", "key", "display_order", "enabled"],
    searchFields: ["label", "label_en", "key", "keywords"],
    duplicateFields: ["key", "label"],
    fields: [
      { name: "key", label: "Key" },
      { name: "label", label: "Label" },
      { name: "label_en", label: "Label EN" },
      { name: "keywords", label: "Keywords", type: "textarea" },
      { name: "display_order", label: "Order", type: "number" },
      { name: "enabled", label: "Enabled", type: "number" },
    ],
  },
  {
    name: "news",
    label: "News",
    titleField: "title",
    listFields: ["title", "slug", "category", "published_at", "visibility", "is_featured"],
    searchFields: ["title", "slug", "category", "content"],
    duplicateFields: ["title", "slug"],
    fields: [
      { name: "title", label: "Title" },
      { name: "slug", label: "Slug" },
      { name: "category", label: "Category", suggest: true },
      { name: "cover_key", label: "Cover key", type: "file" },
      { name: "content", label: "Content", type: "textarea" },
      { name: "content_format", label: "Content format", type: "select", choices: ["plain", "html"] },
      { name: "allow_comments", label: "Allow comments", type: "number" },
      { name: "published_at", label: "Published at", type: "datetime" },
      { name: "visibility", label: "Visibility", type: "select", choices: visibilityChoices },
      { name: "is_featured", label: "Featured", type: "number" },
      { name: "sort_order", label: "Sort order", type: "number" },
    ],
  },
  {
    name: "courses",
    label: "Courses",
    titleField: "name",
    listFields: ["name", "semester", "audience", "visibility"],
    searchFields: ["name", "semester", "audience", "summary"],
    duplicateFields: ["name", "semester"],
    fields: [
      { name: "name", label: "Name" },
      { name: "semester", label: "Semester", suggest: true },
      { name: "audience", label: "Audience", suggest: true },
      { name: "summary", label: "Summary", type: "textarea" },
      { name: "syllabus_key", label: "Syllabus key", type: "file" },
      { name: "material_key", label: "Material key", type: "file" },
      { name: "material_visibility", label: "Material visibility", type: "select", choices: visibilityChoices },
      { name: "references_text", label: "References", type: "textarea" },
      { name: "visibility", label: "Visibility", type: "select", choices: visibilityChoices },
      { name: "is_featured", label: "Featured", type: "number" },
      { name: "sort_order", label: "Sort order", type: "number" },
    ],
  },
  {
    name: "messages",
    label: "Messages",
    titleField: "subject",
    listFields: ["subject", "name", "email", "message_type", "status", "created_at"],
    searchFields: ["subject", "name", "email", "content"],
    fields: [
      { name: "name", label: "Name" },
      { name: "email", label: "Email", type: "email" },
      { name: "message_type", label: "Type", type: "select", choices: ["recruiting", "cooperation", "paper", "project", "course", "other"] },
      { name: "subject", label: "Subject" },
      { name: "content", label: "Content", type: "textarea" },
      { name: "attachment_key", label: "Attachment key", type: "file" },
      { name: "status", label: "Status", type: "select", choices: ["new", "read", "replied", "archived"] },
    ],
  },
  {
    name: "media_assets",
    label: "Media assets",
    titleField: "title",
    listFields: ["object_key", "title", "category", "mime_type", "size", "uploaded_at"],
    searchFields: ["object_key", "title", "category", "mime_type"],
    duplicateFields: ["object_key"],
    fields: [
      { name: "object_key", label: "Object key", type: "file" },
      { name: "title", label: "Title" },
      { name: "category", label: "Category", suggest: true },
      { name: "mime_type", label: "MIME type" },
      { name: "size", label: "Size", type: "number" },
    ],
  },
  {
    name: "translation_cache",
    label: "Translation cache",
    titleField: "source_text",
    listFields: ["source_text", "translated_text", "source_lang", "target_lang", "status", "is_manual"],
    searchFields: ["source_text", "translated_text", "source_refs"],
    fields: [
      { name: "source_hash", label: "Source hash" },
      { name: "source_ref_key", label: "Source ref key" },
      { name: "source_text", label: "Source text", type: "textarea" },
      { name: "source_lang", label: "Source lang" },
      { name: "target_lang", label: "Target lang" },
      { name: "translated_text", label: "Translated text", type: "textarea" },
      { name: "provider", label: "Provider" },
      { name: "status", label: "Status", type: "select", choices: ["pending", "success", "failed"] },
      { name: "is_manual", label: "Manual", type: "number" },
      { name: "is_current", label: "Current", type: "number" },
      { name: "source_refs", label: "Source refs", type: "textarea" },
      { name: "error_message", label: "Error", type: "textarea" },
    ],
  },
  {
    name: "autofetch_logs",
    label: "Auto fetch logs",
    titleField: "query",
    listFields: ["source", "query", "success", "message", "created_at"],
    searchFields: ["source", "query", "message"],
    fields: [
      { name: "source", label: "Source" },
      { name: "query", label: "Query" },
      { name: "success", label: "Success", type: "number" },
      { name: "message", label: "Message", type: "textarea" },
      { name: "changes_json", label: "Changes JSON", type: "textarea" },
      { name: "publication_id", label: "Publication ID", type: "number" },
    ],
  },
];

export function tableMeta(name: string) {
  return tables.find((table) => table.name === name);
}

export function editableFields(name: string) {
  return tableMeta(name)?.fields || [];
}

export function fieldNames(name: string) {
  return editableFields(name).map((field) => field.name);
}

export function isKnownTable(name: string) {
  return Boolean(tableMeta(name));
}
