<script setup lang="ts">
const props = defineProps<{ locale: 'zh' | 'en' }>()
const copy = computed(() => props.locale === 'en' ? { title:'Initialize administrator', intro:'Create the first administrator for an empty database.', token:'Bootstrap token', username:'Username', name:'Display name', email:'Email', password:'Password', confirm:'Confirm password', submit:'Create administrator', success:'Administrator created. Continue to sign in.', mismatch:'Passwords do not match.', failure:'Initialization failed.', login:'Go to sign in' } : { title:'初始化管理员', intro:'为空数据库创建第一个系统管理员。初始化完成后，服务端会拒绝再次使用本入口。', token:'初始化令牌', username:'登录账号', name:'显示名称', email:'邮箱', password:'密码', confirm:'确认密码', submit:'创建管理员', success:'管理员已创建，请继续登录。', mismatch:'两次输入的密码不一致。', failure:'初始化失败。', login:'前往登录' })
const form=reactive({bootstrapToken:'',username:'',displayName:'',email:'',password:'',confirmPassword:''});const pending=ref(false);const error=ref('');const complete=ref(false)
function requestError(cause:unknown){const value=cause as {data?:{error?:{message?:unknown}}};return typeof value?.data?.error?.message==='string'?value.data.error.message:copy.value.failure}
async function submit(){error.value='';if(form.password!==form.confirmPassword){error.value=copy.value.mismatch;return}pending.value=true;try{await $fetch('/api/v1/auth/bootstrap',{method:'POST',headers:{authorization:`Bearer ${form.bootstrapToken}`},body:{username:form.username,displayName:form.displayName,email:form.email,password:form.password}});complete.value=true;form.bootstrapToken='';form.password='';form.confirmPassword=''}catch(cause:unknown){error.value=requestError(cause)}finally{pending.value=false}}
</script>
<template><main class="setup-page"><section class="setup-card" aria-labelledby="setup-title"><h1 id="setup-title">{{copy.title}}</h1><p>{{copy.intro}}</p><div v-if="error" role="alert" class="alert">{{error}}</div><div v-if="complete" class="success"><strong>{{copy.success}}</strong><NuxtLink class="primary-link" :to="`/${locale}/login`">{{copy.login}}</NuxtLink></div><form v-else @submit.prevent="submit"><label><span>{{copy.token}}</span><input v-model="form.bootstrapToken" required type="password" autocomplete="off"></label><label><span>{{copy.username}}</span><input v-model.trim="form.username" required maxlength="64" autocomplete="username"></label><label><span>{{copy.name}}</span><input v-model.trim="form.displayName" required maxlength="120" autocomplete="name"></label><label><span>{{copy.email}}</span><input v-model.trim="form.email" required type="email" maxlength="254" autocomplete="email"></label><label><span>{{copy.password}}</span><input v-model="form.password" required minlength="6" maxlength="256" type="password" autocomplete="new-password"></label><label><span>{{copy.confirm}}</span><input v-model="form.confirmPassword" required minlength="6" maxlength="256" type="password" autocomplete="new-password"></label><button type="submit" :disabled="pending">{{pending?'…':copy.submit}}</button></form></section></main></template>
<style scoped>.setup-page{min-height:100vh;display:grid;place-items:center;padding:2rem;background:#f5f7fa;color:#1f2937}.setup-card{width:min(36rem,100%);display:grid;gap:1rem;padding:clamp(1.25rem,4vw,2.25rem);border:1px solid #dcdfe6;border-radius:1rem;background:#fff;box-shadow:0 12px 32px #00000012}h1,p{margin:0}form{display:grid;gap:1rem}label{display:grid;gap:.4rem;font-weight:600}input{min-height:2.75rem;border:1px solid #c0c4cc;border-radius:.5rem;padding:.55rem .75rem;font:inherit}input:focus{outline:3px solid #409eff33;border-color:#409eff}button,.primary-link{display:inline-flex;justify-content:center;align-items:center;min-height:2.75rem;border:0;border-radius:.5rem;padding:.6rem 1rem;background:#409eff;color:#fff;font:inherit;font-weight:700;text-decoration:none;cursor:pointer}button:disabled{opacity:.6;cursor:wait}.alert{padding:.75rem;border:1px solid #f56c6c;border-radius:.5rem;background:#fef0f0;color:#b42318}.success{display:grid;gap:1rem;padding:1rem;border:1px solid #67c23a;border-radius:.5rem;background:#f0f9eb}</style>
