<script setup lang="ts">
import { Eye, EyeOff, KeyRound } from '@lucide/vue'; import { safeApplicationRedirect } from '~~/shared/utils/redirect'; import { apiErrorDetails } from '~/utils/interaction-errors'
const props=defineProps<{locale:'zh'|'en'}>(); const auth=useAuthSession(); const route=useRoute(); const router=useRouter(); const currentPassword=ref(''); const newPassword=ref(''); const confirmPassword=ref(''); const showPassword=ref(false); const error=ref<{message:string;requestId:string|null}|null>(null)
const labels=computed(()=>props.locale==='zh'?{current:'当前密码',next:'新密码',confirm:'确认新密码',submit:'修改密码',pending:'正在修改…',mismatch:'两次输入的新密码不一致。',fallback:'密码修改失败，请稍后重试。',login:'请先登录后再修改密码。'}:{current:'Current password',next:'New password',confirm:'Confirm new password',submit:'Change password',pending:'Changing…',mismatch:'The new password confirmation does not match.',fallback:'Password change failed. Please try again.',login:'Sign in before changing your password.'})
const fallback=`/${props.locale}/account`; const returnTarget=computed(()=>safeApplicationRedirect(route.query.next,fallback)); await auth.load()
async function enterTarget(target:string):Promise<void>{if(target==='/admin'||target.startsWith('/admin/')){window.location.replace(target);return}await router.replace(target)}
async function submit():Promise<void>{error.value=null;if(newPassword.value!==confirmPassword.value){error.value={message:labels.value.mismatch,requestId:null};return}try{await auth.changePassword({currentPassword:currentPassword.value,newPassword:newPassword.value});currentPassword.value='';newPassword.value='';confirmPassword.value='';await enterTarget(returnTarget.value)}catch(cause){const details=apiErrorDetails(cause,labels.value.fallback);error.value={message:details.message,requestId:details.requestId}}}
</script>
<template><div v-if="!auth.session.value.authenticated" class="public-form"><PublicAuthStatusMessage>{{ labels.login }}</PublicAuthStatusMessage><NuxtLink class="public-form-submit" :to="{path:`/${locale}/login`,query:{next:returnTarget}}">{{ locale==='zh'?'前往登录':'Sign in' }}</NuxtLink></div><form v-else class="public-form" @submit.prevent="submit"><PublicAuthStatusMessage v-if="error" tone="error" :request-id="error.requestId">{{ error.message }}</PublicAuthStatusMessage><label class="public-field"><span>{{ labels.current }}</span><input v-model="currentPassword" :type="showPassword?'text':'password'" autocomplete="current-password" maxlength="256" required></label><label class="public-field"><span>{{ labels.next }}</span><input v-model="newPassword" :type="showPassword?'text':'password'" autocomplete="new-password" minlength="6" maxlength="256" required></label><label class="public-field"><span>{{ labels.confirm }}</span><input v-model="confirmPassword" :type="showPassword?'text':'password'" autocomplete="new-password" minlength="6" maxlength="256" required></label><label class="public-form-toggle"><input v-model="showPassword" type="checkbox"><span><EyeOff v-if="showPassword" :size="16" /><Eye v-else :size="16" />{{ locale==='zh'?'显示密码':'Show passwords' }}</span></label><button class="public-form-submit" type="submit" :disabled="auth.pending.value"><KeyRound :size="18" />{{ auth.pending.value?labels.pending:labels.submit }}</button></form></template>
