#!/usr/bin/env bash
# Ubuntu/Debian standalone installer. Fetch and execute directly; prompts use /dev/tty.
set -Eeuo pipefail
umask 077
BASE=/opt/file-transfer
ETC=/etc/file-transfer
SERVICE=file-transfer
REPO=''; BRANCH=web-vue-nuxt; SUBDIR=auto; MODE=install; BRANCH_EXPLICIT=no
NODE_VERSION=24.19.0
PNPM_VERSION=11.19.0
usage(){ cat <<'TXT'
Usage: install.sh --repo https://github.com/biao169/web-teacher.git [--branch web-vue-nuxt] [--subdir file-transfer|.] [--mode install|update|menu]
Terminal menu after installation: Fweb
Updates preserve storage and configuration, and take a stopped-service backup.
TXT
}
while (($#)); do
 case "$1" in
 --repo|--branch|--subdir|--mode) (($#>=2)) || { usage; exit 2; }; [[ $1 != --branch ]] || BRANCH_EXPLICIT=yes; key=${1#--}; printf -v "${key^^}" '%s' "$2"; shift 2;;
 --help|-h) usage; exit 0;;
 *) usage; exit 2;; esac
done
[[ $EUID == 0 ]] || { echo '请使用 sudo bash 执行。'; exit 1; }
[[ -r /etc/os-release ]] || exit 1
. /etc/os-release
[[ $ID == ubuntu || $ID == debian ]] || { echo '仅支持 Ubuntu / Debian。'; exit 1; }
ask(){ local label=$1 default=${2-}; printf '%s [%s]: ' "$label" "$default" >/dev/tty; IFS= read -r answer </dev/tty; answer=${answer:-$default}; }
fail(){ echo "[失败] $*" >&2; exit 1; }
if [[ -f $ETC/source.conf ]]; then
 # Configuration is generated by this script, owned by root, never sourced from Git.
 [[ $(stat -c %u "$ETC/source.conf") == 0 ]] || fail '配置文件所有者异常'
 . "$ETC/source.conf"
 REPO=${REPO:-$SAVED_REPO}
 [[ $BRANCH_EXPLICIT == yes ]] || BRANCH=$SAVED_BRANCH
 [[ $SUBDIR != auto ]] || SUBDIR=$SAVED_SUBDIR
fi
backup(){
 mkdir -p "$BASE/backups"
 local archive="$BASE/backups/backup-$(date -u +%Y%m%dT%H%M%SZ).tar.gz" was=no
 systemctl is-active --quiet "$SERVICE" && was=yes || true
 systemctl stop "$SERVICE" || true
 if ! tar -czf "$archive" -C "$BASE/app" storage -C /etc file-transfer; then
  [[ $was == no ]] || systemctl start "$SERVICE"
  fail '备份失败'
 fi
 [[ $was == no ]] || systemctl start "$SERVICE"
 echo "备份：$archive"
}
if [[ $MODE == menu ]]; then
 while true; do
  printf '\n文件快传 Fweb\n1 状态  2 日志  3 重启  4 更新源码与数据库  5 备份  6 初始化管理员  7 查看访问地址  0 退出\n'
  ask '选择' 1
  case "$answer" in
   1) systemctl status "$SERVICE" --no-pager || true;;
   2) journalctl -u "$SERVICE" -n 100 --no-pager;;
   3) systemctl restart "$SERVICE";;
   4) exec bash "$BASE/install.sh" --mode update;;
   5) backup;;
   6) systemctl stop "$SERVICE"; ask '管理员名称' admin; admin=$answer; printf '密码（至少 6 位）: ' >/dev/tty; IFS= read -rs password </dev/tty; printf '\n' >/dev/tty
      printf '%s\n%s\n' "$admin" "$password" | runuser -u ftweb -- env PATH="$BASE/node/bin:/usr/bin:/bin" "$BASE/node/bin/node" "$BASE/app/scripts/standalone-admin.mjs" || true
      unset password; systemctl start "$SERVICE";;
   7) cat "$ETC/address";;
   0) exit 0;;
  esac
 done
fi
[[ $MODE == install || $MODE == update ]] || fail '不支持的模式'
[[ -n $REPO ]] || { ask 'Git 仓库 HTTPS 地址' 'https://github.com/biao169/web-teacher.git'; REPO=$answer; }
[[ $REPO =~ ^https://[^[:space:]]+$ && $REPO != *'@'* ]] || fail '请使用不含访问令牌的 HTTPS 仓库地址；私有仓库使用 root 的 Git credential helper。'
[[ -n $BRANCH && $BRANCH != -* && $BRANCH != *$'\n'* ]] || fail '无效分支'
[[ $SUBDIR == auto || $SUBDIR == . || $SUBDIR =~ ^[A-Za-z0-9_/-]+$ && $SUBDIR != *..* && $SUBDIR != /* ]] || fail '无效子目录'
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y ca-certificates curl git xz-utils nginx openssl python3
mkdir -p "$BASE" "$ETC"
exec 9>"$ETC/install.lock"
flock -n 9 || fail '已有部署任务运行中'
WORK=$(mktemp -d "$BASE/staging.XXXXXX")
SWAPPED=no
finish(){ local result=$?; if ((result!=0)) && [[ $SWAPPED == yes && -d $BASE/previous ]]; then
 echo '更新失败，正在恢复上一版本及备份的数据。' >&2
 systemctl stop "$SERVICE" || true
 mv "$BASE/app" "$WORK/failed-app"
 mv "$BASE/previous" "$BASE/app"
 systemctl start "$SERVICE" || true
 fi
 rm -rf -- "$WORK"
}
trap finish EXIT
if [[ ! -x $BASE/node/bin/node || $($BASE/node/bin/node --version) != v$NODE_VERSION ]]; then
 case $(dpkg --print-architecture) in amd64) ARCH=x64;; arm64) ARCH=arm64;; *) fail '仅支持 amd64 / arm64';; esac
 FILE="node-v$NODE_VERSION-linux-$ARCH.tar.xz"
 curl --fail --show-error --location --proto '=https' --tlsv1.2 "https://nodejs.org/dist/v$NODE_VERSION/$FILE" -o "$WORK/$FILE"
 curl --fail --show-error --location --proto '=https' --tlsv1.2 "https://nodejs.org/dist/v$NODE_VERSION/SHASUMS256.txt" -o "$WORK/SHASUMS256.txt"
 (cd "$WORK"; awk -v file="$FILE" '$2==file' SHASUMS256.txt > selected.sha256; [[ -s selected.sha256 ]]; sha256sum -c selected.sha256)
 tar -xJf "$WORK/$FILE" -C "$WORK"
 [[ ! -e $BASE/node ]] || mv "$BASE/node" "$WORK/old-node"
 mv "$WORK/node-v$NODE_VERSION-linux-$ARCH" "$BASE/node"
fi
export PATH="$BASE/node/bin:/usr/sbin:/usr/bin:/sbin:/bin"
npm install --global "pnpm@$PNPM_VERSION"
git check-ref-format --branch "$BRANCH" >/dev/null || fail '无效 Git 分支'
git clone --depth 1 --single-branch --branch "$BRANCH" -- "$REPO" "$WORK/repo"
if [[ $SUBDIR == auto ]]; then
 if [[ -f $WORK/repo/file-transfer/scripts/standalone.mjs ]]; then SUBDIR=file-transfer; else SUBDIR=.; fi
fi
SOURCE="$WORK/repo/$SUBDIR"
[[ -f $SOURCE/scripts/standalone.mjs && -f $SOURCE/wrangler.jsonc ]] || fail '仓库中没有新版快传源码，请检查 --subdir 和 --branch'
cp -a "$SOURCE" "$WORK/app"
# Runtime data must not come from a repository.
rm -rf -- "$WORK/app/storage/data" "$WORK/app/node_modules" "$WORK/app/.git"
(cd "$WORK/app"; pnpm install --frozen-lockfile; pnpm build)
[[ -f $WORK/app/dist/index.html ]] || fail '前台构建失败'
id ftweb >/dev/null 2>&1 || useradd --system --home-dir "$BASE/app" --shell /usr/sbin/nologin ftweb
if [[ -d $BASE/app ]]; then
 [[ $MODE == update ]] || fail '已有安装；请使用 --mode update 或 Fweb 菜单。'
 backup
 systemctl stop "$SERVICE"
 cp -a "$BASE/app/storage" "$WORK/app/"
 [[ ! -f $BASE/app/config.local.json ]] || cp -a "$BASE/app/config.local.json" "$WORK/app/"
 [[ ! -e $BASE/previous ]] || mv "$BASE/previous" "$BASE/backups/previous-$(date +%s)"
 mv "$BASE/app" "$BASE/previous"
 SWAPPED=yes
fi
mv "$WORK/app" "$BASE/app"
mkdir -p "$BASE/app/storage/data"
chown -R root:root "$BASE/app"
chmod -R a+rX "$BASE/app"
chown -R ftweb:ftweb "$BASE/app/storage"
chmod -R go-rwx "$BASE/app/storage"
if [[ ! -f $ETC/runtime.env ]]; then
 ask '公网域名（先把 A/AAAA 指向此服务器；留空仅本机使用）' ''; DOMAIN=$answer
 [[ -z $DOMAIN || $DOMAIN =~ ^[A-Za-z0-9]([A-Za-z0-9.-]*[A-Za-z0-9])?$ && $DOMAIN == *.* && $DOMAIN != *..* ]] || fail '无效域名'
 ORIGIN=http://127.0.0.1:8787
 [[ -z $DOMAIN ]] || ORIGIN="https://$DOMAIN"
 printf 'FT_HOST=127.0.0.1\nFT_PORT=8787\nFT_PUBLIC_ORIGIN=%s\n' "$ORIGIN" > "$ETC/runtime.env"
 printf '%s\n' "$ORIGIN" > "$ETC/address"
 ask '首个管理员名称' admin; admin=$answer
 while true; do
  printf '管理员密码（至少 6 位）: ' >/dev/tty; IFS= read -rs password </dev/tty; printf '\n重复密码: ' >/dev/tty; IFS= read -rs repeated </dev/tty; printf '\n' >/dev/tty
  [[ ${#password} -ge 6 && $password == "$repeated" ]] && break
  echo '密码长度不足或两次不一致。'
 done
 printf '%s\n%s\n' "$admin" "$password" | runuser -u ftweb -- env PATH="$PATH" node "$BASE/app/scripts/standalone-admin.mjs"
 unset password repeated
 if [[ -n $DOMAIN ]]; then
 cat > /etc/nginx/sites-available/file-transfer <<NGINX
server {
 listen 80;
 server_name $DOMAIN;
 client_max_body_size 128k;
 location / {
  proxy_pass http://127.0.0.1:8787;
  proxy_http_version 1.1;
  proxy_set_header Host \$host;
  proxy_set_header Upgrade \$http_upgrade;
  proxy_set_header Connection "upgrade";
  proxy_read_timeout 3600s;
  proxy_send_timeout 3600s;
  proxy_buffering off;
 }
}
NGINX
 ln -sf /etc/nginx/sites-available/file-transfer /etc/nginx/sites-enabled/file-transfer
 nginx -t
 systemctl reload nginx
 apt-get install -y certbot python3-certbot-nginx
 ask '证书通知邮箱'; EMAIL=$answer
 certbot --nginx --non-interactive --agree-tos --redirect -m "$EMAIL" -d "$DOMAIN"
 fi
fi
cat > /etc/systemd/system/file-transfer.service <<UNIT
[Unit]
Description=Standalone file transfer
After=network-online.target
Wants=network-online.target
[Service]
Type=simple
User=ftweb
Group=ftweb
WorkingDirectory=$BASE/app
EnvironmentFile=$ETC/runtime.env
ExecStart=$BASE/node/bin/node $BASE/app/scripts/standalone.mjs
Restart=on-failure
RestartSec=3
TimeoutStopSec=30
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=$BASE/app/storage
UMask=0077
[Install]
WantedBy=multi-user.target
UNIT
printf 'SAVED_REPO=%q\nSAVED_BRANCH=%q\nSAVED_SUBDIR=%q\n' "$REPO" "$BRANCH" "$SUBDIR" > "$ETC/source.conf"
cp "$BASE/app/install.sh" "$BASE/install.sh"
cat > /usr/local/bin/Fweb <<'MENU'
#!/usr/bin/env bash
exec sudo bash /opt/file-transfer/install.sh --mode menu
MENU
chmod 755 /usr/local/bin/Fweb
systemctl daemon-reload
systemctl enable --now "$SERVICE"
systemctl restart "$SERVICE"
for ((i=0;i<30;i++)); do
 if curl -fsS http://127.0.0.1:8787/transfer-api/ready >/dev/null; then SWAPPED=no; break; fi
 sleep 1
done
[[ $SWAPPED == no ]] || fail '新版本健康检查未通过'
curl -fsS http://127.0.0.1:8787/transfer-api/ready >/dev/null || fail '服务未就绪，使用 Fweb 查看日志'
echo '部署完成。终端输入 Fweb 打开管理菜单。'
cat "$ETC/address"
echo '登录 /transfer-admin/，先配置链路、权限与额度，再开放传输。'
