// Generated from db/schema-spec.json. Edit the spec, then run db:generate.
import { sql } from 'drizzle-orm'
import { sqliteTable, text, integer, index, uniqueIndex, check } from 'drizzle-orm/sqlite-core'
import type { JsonValue } from './schema-types'

export const mediaAssets = sqliteTable('media_assets', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  uid: text('uid').notNull().unique(),
  created_at: text('created_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  updated_at: text('updated_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  object_key: text('object_key').notNull().unique(),
  title: text('title'),
  category: text('category'),
  mime_type: text('mime_type'),
  size: integer('size').notNull().default(sql.raw("0")),
  storage_kind: text('storage_kind').$type<"static" | "local" | "r2" | "external">().notNull().default(sql.raw("'local'")),
  status: text('status').$type<"active" | "trash">().notNull().default(sql.raw("'active'")),
  checksum: text('checksum'),
}, t => [
  check('ck_media_assets_uid_0', sql.raw("length(trim(\"uid\")) > 0")),
  check('ck_media_assets_uid_1', sql.raw("length(\"uid\") <= 128")),
  check('ck_media_assets_created_at_0', sql.raw("length(\"created_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"created_at\", '+0 seconds') = \"created_at\", 0)")),
  check('ck_media_assets_updated_at_0', sql.raw("length(\"updated_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"updated_at\", '+0 seconds') = \"updated_at\", 0)")),
  check('ck_media_assets_object_key_0', sql.raw("length(trim(\"object_key\")) > 0")),
  check('ck_media_assets_size_0', sql.raw("typeof(\"size\") = 'integer' AND \"size\" BETWEEN -9007199254740991 AND 9007199254740991")),
  check('ck_media_assets_size_1', sql.raw("\"size\" >= 0")),
  check('ck_media_assets_storage_kind_0', sql.raw("\"storage_kind\" IN ('static', 'local', 'r2', 'external')")),
  check('ck_media_assets_status_0', sql.raw("\"status\" IN ('active', 'trash')")),
  index('idx_media_assets_status_category_mime').on(t.status, t.category, t.mime_type, t.id),
])

export const authRoles = sqliteTable('auth_roles', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  uid: text('uid').notNull().unique(),
  created_at: text('created_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  updated_at: text('updated_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  name: text('name').notNull(),
  level: integer('level').notNull().default(sql.raw("0")),
  description: text('description'),
  visibility_scopes: text('visibility_scopes', { mode: 'json' }).$type<JsonValue>().notNull().default(sql.raw("'[\"public\"]'")),
  is_system: integer('is_system', { mode: 'boolean' }).notNull().default(sql.raw("0")),
  is_active: integer('is_active', { mode: 'boolean' }).notNull().default(sql.raw("0")),
  sort_order: integer('sort_order').notNull().default(sql.raw("0")),
}, t => [
  check('ck_auth_roles_uid_0', sql.raw("length(trim(\"uid\")) > 0")),
  check('ck_auth_roles_uid_1', sql.raw("length(\"uid\") <= 128")),
  check('ck_auth_roles_created_at_0', sql.raw("length(\"created_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"created_at\", '+0 seconds') = \"created_at\", 0)")),
  check('ck_auth_roles_updated_at_0', sql.raw("length(\"updated_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"updated_at\", '+0 seconds') = \"updated_at\", 0)")),
  check('ck_auth_roles_name_0', sql.raw("length(trim(\"name\")) > 0")),
  check('ck_auth_roles_level_0', sql.raw("typeof(\"level\") = 'integer' AND \"level\" BETWEEN -9007199254740991 AND 9007199254740991")),
  check('ck_auth_roles_level_1', sql.raw("\"level\" >= 0")),
  check('ck_auth_roles_visibility_scopes_0', sql.raw("CASE WHEN json_valid(\"visibility_scopes\") THEN json_type(\"visibility_scopes\") = 'array' ELSE 0 END")),
  check('ck_auth_roles_is_system_0', sql.raw("\"is_system\" IN (0, 1)")),
  check('ck_auth_roles_is_active_0', sql.raw("\"is_active\" IN (0, 1)")),
  check('ck_auth_roles_sort_order_0', sql.raw("typeof(\"sort_order\") = 'integer' AND \"sort_order\" BETWEEN -9007199254740991 AND 9007199254740991")),
])

export const authUsers = sqliteTable('auth_users', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  uid: text('uid').notNull().unique(),
  created_at: text('created_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  updated_at: text('updated_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  username: text('username').notNull(),
  password_hash: text('password_hash').notNull(),
  display_name: text('display_name'),
  email: text('email'),
  role_uid: text('role_uid').notNull().references(() => authRoles.uid, { onDelete: 'restrict', onUpdate: 'restrict' }),
  status: text('status').$type<"active" | "disabled" | "locked">().notNull().default(sql.raw("'disabled'")),
  must_change_password: integer('must_change_password', { mode: 'boolean' }).notNull().default(sql.raw("0")),
  last_login_at: text('last_login_at'),
  visibility: text('visibility').$type<"public" | "authenticated" | "staff" | "owner" | "hidden">().notNull().default(sql.raw("'hidden'")),
}, t => [
  check('ck_auth_users_uid_0', sql.raw("length(trim(\"uid\")) > 0")),
  check('ck_auth_users_uid_1', sql.raw("length(\"uid\") <= 128")),
  check('ck_auth_users_created_at_0', sql.raw("length(\"created_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"created_at\", '+0 seconds') = \"created_at\", 0)")),
  check('ck_auth_users_updated_at_0', sql.raw("length(\"updated_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"updated_at\", '+0 seconds') = \"updated_at\", 0)")),
  check('ck_auth_users_username_0', sql.raw("length(trim(\"username\")) > 0")),
  check('ck_auth_users_username_1', sql.raw("length(\"username\") <= 150")),
  check('ck_auth_users_password_hash_0', sql.raw("length(trim(\"password_hash\")) > 0")),
  check('ck_auth_users_role_uid_0', sql.raw("length(trim(\"role_uid\")) > 0")),
  check('ck_auth_users_status_0', sql.raw("\"status\" IN ('active', 'disabled', 'locked')")),
  check('ck_auth_users_must_change_password_0', sql.raw("\"must_change_password\" IN (0, 1)")),
  check('ck_auth_users_last_login_at_0', sql.raw("\"last_login_at\" IS NULL OR (length(\"last_login_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"last_login_at\", '+0 seconds') = \"last_login_at\", 0))")),
  check('ck_auth_users_visibility_0', sql.raw("\"visibility\" IN ('public', 'authenticated', 'staff', 'owner', 'hidden')")),
  index('idx_auth_users_role_uid').on(t.role_uid),
  uniqueIndex('idx_auth_users_username_nocase').on(sql`${t.username} COLLATE NOCASE`),
])

export const authPermissions = sqliteTable('auth_permissions', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  uid: text('uid').notNull().unique(),
  created_at: text('created_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  updated_at: text('updated_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  role_uid: text('role_uid').notNull().references(() => authRoles.uid, { onDelete: 'restrict', onUpdate: 'restrict' }),
  module: text('module').notNull(),
  can_view: integer('can_view', { mode: 'boolean' }).notNull().default(sql.raw("0")),
  can_create: integer('can_create', { mode: 'boolean' }).notNull().default(sql.raw("0")),
  can_edit: integer('can_edit', { mode: 'boolean' }).notNull().default(sql.raw("0")),
  can_delete: integer('can_delete', { mode: 'boolean' }).notNull().default(sql.raw("0")),
  can_export: integer('can_export', { mode: 'boolean' }).notNull().default(sql.raw("0")),
  sort_order: integer('sort_order').notNull().default(sql.raw("0")),
}, t => [
  check('ck_auth_permissions_uid_0', sql.raw("length(trim(\"uid\")) > 0")),
  check('ck_auth_permissions_uid_1', sql.raw("length(\"uid\") <= 128")),
  check('ck_auth_permissions_created_at_0', sql.raw("length(\"created_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"created_at\", '+0 seconds') = \"created_at\", 0)")),
  check('ck_auth_permissions_updated_at_0', sql.raw("length(\"updated_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"updated_at\", '+0 seconds') = \"updated_at\", 0)")),
  check('ck_auth_permissions_role_uid_0', sql.raw("length(trim(\"role_uid\")) > 0")),
  check('ck_auth_permissions_module_0', sql.raw("length(trim(\"module\")) > 0")),
  check('ck_auth_permissions_can_view_0', sql.raw("\"can_view\" IN (0, 1)")),
  check('ck_auth_permissions_can_create_0', sql.raw("\"can_create\" IN (0, 1)")),
  check('ck_auth_permissions_can_edit_0', sql.raw("\"can_edit\" IN (0, 1)")),
  check('ck_auth_permissions_can_delete_0', sql.raw("\"can_delete\" IN (0, 1)")),
  check('ck_auth_permissions_can_export_0', sql.raw("\"can_export\" IN (0, 1)")),
  check('ck_auth_permissions_sort_order_0', sql.raw("typeof(\"sort_order\") = 'integer' AND \"sort_order\" BETWEEN -9007199254740991 AND 9007199254740991")),
  index('idx_auth_permissions_role_uid').on(t.role_uid),
  uniqueIndex('idx_auth_permissions_role_module').on(t.role_uid, t.module),
])

export const profiles = sqliteTable('profiles', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  uid: text('uid').notNull().unique(),
  created_at: text('created_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  updated_at: text('updated_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  name: text('name').notNull(),
  name_en: text('name_en'),
  role: text('role'),
  title: text('title'),
  organization: text('organization'),
  lab: text('lab'),
  avatar_key: text('avatar_key').references(() => mediaAssets.object_key, { onDelete: 'restrict', onUpdate: 'restrict' }),
  email: text('email'),
  phone: text('phone'),
  office: text('office'),
  bio: text('bio'),
  bio_en: text('bio_en'),
  education: text('education'),
  experience: text('experience'),
  recruiting: text('recruiting'),
  orcid: text('orcid'),
  personal_homepage: text('personal_homepage'),
  google_scholar: text('google_scholar'),
  dblp: text('dblp'),
  github: text('github'),
  cnki: text('cnki'),
  contact_visibility: text('contact_visibility').$type<"public" | "authenticated" | "staff" | "owner" | "hidden">().notNull().default(sql.raw("'hidden'")),
  visibility: text('visibility').$type<"public" | "authenticated" | "staff" | "owner" | "hidden">().notNull().default(sql.raw("'hidden'")),
  is_active: integer('is_active', { mode: 'boolean' }).notNull().default(sql.raw("0")),
  is_featured: integer('is_featured', { mode: 'boolean' }).notNull().default(sql.raw("0")),
  sort_order: integer('sort_order').notNull().default(sql.raw("0")),
  orcid_value: integer('orcid_value'),
  personal_homepage_value: integer('personal_homepage_value'),
  google_scholar_value: integer('google_scholar_value'),
  dblp_value: integer('dblp_value'),
  github_value: integer('github_value'),
  cnki_value: integer('cnki_value'),
}, t => [
  check('ck_profiles_uid_0', sql.raw("length(trim(\"uid\")) > 0")),
  check('ck_profiles_uid_1', sql.raw("length(\"uid\") <= 128")),
  check('ck_profiles_created_at_0', sql.raw("length(\"created_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"created_at\", '+0 seconds') = \"created_at\", 0)")),
  check('ck_profiles_updated_at_0', sql.raw("length(\"updated_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"updated_at\", '+0 seconds') = \"updated_at\", 0)")),
  check('ck_profiles_name_0', sql.raw("length(trim(\"name\")) > 0")),
  check('ck_profiles_contact_visibility_0', sql.raw("\"contact_visibility\" IN ('public', 'authenticated', 'staff', 'owner', 'hidden')")),
  check('ck_profiles_visibility_0', sql.raw("\"visibility\" IN ('public', 'authenticated', 'staff', 'owner', 'hidden')")),
  check('ck_profiles_is_active_0', sql.raw("\"is_active\" IN (0, 1)")),
  check('ck_profiles_is_featured_0', sql.raw("\"is_featured\" IN (0, 1)")),
  check('ck_profiles_sort_order_0', sql.raw("typeof(\"sort_order\") = 'integer' AND \"sort_order\" BETWEEN -9007199254740991 AND 9007199254740991")),
  check('ck_profiles_orcid_value_0', sql.raw("\"orcid_value\" IS NULL OR (typeof(\"orcid_value\") = 'integer' AND \"orcid_value\" BETWEEN -9007199254740991 AND 9007199254740991)")),
  check('ck_profiles_orcid_value_1', sql.raw("\"orcid_value\" IS NULL OR (\"orcid_value\" >= 0)")),
  check('ck_profiles_personal_homepage_value_0', sql.raw("\"personal_homepage_value\" IS NULL OR (typeof(\"personal_homepage_value\") = 'integer' AND \"personal_homepage_value\" BETWEEN -9007199254740991 AND 9007199254740991)")),
  check('ck_profiles_personal_homepage_value_1', sql.raw("\"personal_homepage_value\" IS NULL OR (\"personal_homepage_value\" >= 0)")),
  check('ck_profiles_google_scholar_value_0', sql.raw("\"google_scholar_value\" IS NULL OR (typeof(\"google_scholar_value\") = 'integer' AND \"google_scholar_value\" BETWEEN -9007199254740991 AND 9007199254740991)")),
  check('ck_profiles_google_scholar_value_1', sql.raw("\"google_scholar_value\" IS NULL OR (\"google_scholar_value\" >= 0)")),
  check('ck_profiles_dblp_value_0', sql.raw("\"dblp_value\" IS NULL OR (typeof(\"dblp_value\") = 'integer' AND \"dblp_value\" BETWEEN -9007199254740991 AND 9007199254740991)")),
  check('ck_profiles_dblp_value_1', sql.raw("\"dblp_value\" IS NULL OR (\"dblp_value\" >= 0)")),
  check('ck_profiles_github_value_0', sql.raw("\"github_value\" IS NULL OR (typeof(\"github_value\") = 'integer' AND \"github_value\" BETWEEN -9007199254740991 AND 9007199254740991)")),
  check('ck_profiles_github_value_1', sql.raw("\"github_value\" IS NULL OR (\"github_value\" >= 0)")),
  check('ck_profiles_cnki_value_0', sql.raw("\"cnki_value\" IS NULL OR (typeof(\"cnki_value\") = 'integer' AND \"cnki_value\" BETWEEN -9007199254740991 AND 9007199254740991)")),
  check('ck_profiles_cnki_value_1', sql.raw("\"cnki_value\" IS NULL OR (\"cnki_value\" >= 0)")),
  index('idx_profiles_visibility_sort').on(t.visibility, t.sort_order, t.id),
  index('idx_profiles_featured').on(t.visibility, t.is_featured, t.sort_order, t.id),
  index('idx_profiles_avatar_key').on(t.avatar_key),
  index('idx_profiles_visibility_active_sort').on(t.visibility, t.is_active, t.sort_order, t.id),
])

export const siteSettings = sqliteTable('site_settings', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  uid: text('uid').notNull().unique(),
  created_at: text('created_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  updated_at: text('updated_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  is_active: integer('is_active', { mode: 'boolean' }).notNull().default(sql.raw("0")),
  site_name: text('site_name').notNull(),
  site_name_en: text('site_name_en'),
  hero_title: text('hero_title'),
  hero_subtitle: text('hero_subtitle'),
  logo_key: text('logo_key').references(() => mediaAssets.object_key, { onDelete: 'restrict', onUpdate: 'restrict' }),
  favicon_key: text('favicon_key').references(() => mediaAssets.object_key, { onDelete: 'restrict', onUpdate: 'restrict' }),
  og_image_key: text('og_image_key').references(() => mediaAssets.object_key, { onDelete: 'restrict', onUpdate: 'restrict' }),
  seo_title: text('seo_title'),
  seo_description: text('seo_description'),
  seo_keywords: text('seo_keywords'),
  footer_text: text('footer_text'),
  homepage_profile_uid: text('homepage_profile_uid').references(() => profiles.uid, { onDelete: 'set null', onUpdate: 'restrict' }),
  homepage_publication_limit: integer('homepage_publication_limit').notNull().default(sql.raw("6")),
  homepage_news_limit: integer('homepage_news_limit').notNull().default(sql.raw("5")),
}, t => [
  check('ck_site_settings_uid_0', sql.raw("length(trim(\"uid\")) > 0")),
  check('ck_site_settings_uid_1', sql.raw("length(\"uid\") <= 128")),
  check('ck_site_settings_created_at_0', sql.raw("length(\"created_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"created_at\", '+0 seconds') = \"created_at\", 0)")),
  check('ck_site_settings_updated_at_0', sql.raw("length(\"updated_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"updated_at\", '+0 seconds') = \"updated_at\", 0)")),
  check('ck_site_settings_is_active_0', sql.raw("\"is_active\" IN (0, 1)")),
  check('ck_site_settings_site_name_0', sql.raw("length(trim(\"site_name\")) > 0")),
  check('ck_site_settings_homepage_publication_limit_0', sql.raw("typeof(\"homepage_publication_limit\") = 'integer' AND \"homepage_publication_limit\" BETWEEN -9007199254740991 AND 9007199254740991")),
  check('ck_site_settings_homepage_publication_limit_1', sql.raw("\"homepage_publication_limit\" >= 0")),
  check('ck_site_settings_homepage_news_limit_0', sql.raw("typeof(\"homepage_news_limit\") = 'integer' AND \"homepage_news_limit\" BETWEEN -9007199254740991 AND 9007199254740991")),
  check('ck_site_settings_homepage_news_limit_1', sql.raw("\"homepage_news_limit\" >= 0")),
  index('idx_site_settings_logo_key').on(t.logo_key),
  index('idx_site_settings_favicon_key').on(t.favicon_key),
  index('idx_site_settings_og_image_key').on(t.og_image_key),
  index('idx_site_settings_homepage_profile_uid').on(t.homepage_profile_uid),
  uniqueIndex('idx_site_settings_one_active').on(t.is_active).where(sql.raw("\"is_active\" = 1")),
])

export const globalSettings = sqliteTable('global_settings', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  uid: text('uid').notNull().unique(),
  created_at: text('created_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  updated_at: text('updated_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  allow_public_registration: integer('allow_public_registration', { mode: 'boolean' }).notNull().default(sql.raw("0")),
  allow_anonymous_messages: integer('allow_anonymous_messages', { mode: 'boolean' }).notNull().default(sql.raw("0")),
  upload_max_size_mb: integer('upload_max_size_mb').notNull().default(sql.raw("20")),
  upload_allowed_extensions: text('upload_allowed_extensions', { mode: 'json' }).$type<JsonValue>().notNull().default(sql.raw("'[\"jpg\",\"jpeg\",\"png\",\"webp\",\"pdf\"]'")),
  media_trash_retention_days: integer('media_trash_retention_days').notNull().default(sql.raw("30")),
  news_pdf_engine: text('news_pdf_engine'),
  news_pdf_allow_download: integer('news_pdf_allow_download', { mode: 'boolean' }).notNull().default(sql.raw("0")),
  news_pdf_watermark: text('news_pdf_watermark'),
  translation_provider: text('translation_provider'),
  translation_providers: text('translation_providers', { mode: 'json' }).$type<JsonValue>().notNull().default(sql.raw("'[]'")),
  libretranslate_url: text('libretranslate_url'),
  libretranslate_api_key: text('libretranslate_api_key'),
  deepl_api_key: text('deepl_api_key'),
  google_translate_api_key: text('google_translate_api_key'),
  microsoft_translator_key: text('microsoft_translator_key'),
  microsoft_translator_region: text('microsoft_translator_region'),
  microsoft_translator_endpoint: text('microsoft_translator_endpoint'),
  mymemory_email: text('mymemory_email'),
  translation_batch_size: integer('translation_batch_size').notNull().default(sql.raw("10")),
  translation_worker_count: integer('translation_worker_count').notNull().default(sql.raw("2")),
  translation_timeout_seconds: integer('translation_timeout_seconds').notNull().default(sql.raw("15")),
  translation_job_state: text('translation_job_state', { mode: 'json' }).$type<JsonValue>().notNull().default(sql.raw("'{}'")),
  publication_metadata_provider: text('publication_metadata_provider'),
  publication_metadata_providers: text('publication_metadata_providers', { mode: 'json' }).$type<JsonValue>().notNull().default(sql.raw("'[]'")),
  publication_display_style: text('publication_display_style'),
  publication_suggestion_cache_seconds: integer('publication_suggestion_cache_seconds').notNull().default(sql.raw("60")),
  profile_suggestion_cache_seconds: integer('profile_suggestion_cache_seconds').notNull().default(sql.raw("60")),
  project_suggestion_cache_seconds: integer('project_suggestion_cache_seconds').notNull().default(sql.raw("60")),
  patent_suggestion_cache_seconds: integer('patent_suggestion_cache_seconds').notNull().default(sql.raw("60")),
  student_suggestion_cache_seconds: integer('student_suggestion_cache_seconds').notNull().default(sql.raw("60")),
  news_suggestion_cache_seconds: integer('news_suggestion_cache_seconds').notNull().default(sql.raw("60")),
  course_suggestion_cache_seconds: integer('course_suggestion_cache_seconds').notNull().default(sql.raw("60")),
  patent_metadata_providers: text('patent_metadata_providers', { mode: 'json' }).$type<JsonValue>().notNull().default(sql.raw("'[]'")),
  patentsview_api_key: text('patentsview_api_key'),
  epo_ops_client_id: text('epo_ops_client_id'),
  epo_ops_client_secret: text('epo_ops_client_secret'),
  notify_email: text('notify_email'),
}, t => [
  check('ck_global_settings_uid_0', sql.raw("length(trim(\"uid\")) > 0")),
  check('ck_global_settings_uid_1', sql.raw("length(\"uid\") <= 128")),
  check('ck_global_settings_created_at_0', sql.raw("length(\"created_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"created_at\", '+0 seconds') = \"created_at\", 0)")),
  check('ck_global_settings_updated_at_0', sql.raw("length(\"updated_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"updated_at\", '+0 seconds') = \"updated_at\", 0)")),
  check('ck_global_settings_allow_public_registration_0', sql.raw("\"allow_public_registration\" IN (0, 1)")),
  check('ck_global_settings_allow_anonymous_messages_0', sql.raw("\"allow_anonymous_messages\" IN (0, 1)")),
  check('ck_global_settings_upload_max_size_mb_0', sql.raw("typeof(\"upload_max_size_mb\") = 'integer' AND \"upload_max_size_mb\" BETWEEN -9007199254740991 AND 9007199254740991")),
  check('ck_global_settings_upload_max_size_mb_1', sql.raw("\"upload_max_size_mb\" >= 1")),
  check('ck_global_settings_upload_allowed_extensions_0', sql.raw("CASE WHEN json_valid(\"upload_allowed_extensions\") THEN json_type(\"upload_allowed_extensions\") = 'array' ELSE 0 END")),
  check('ck_global_settings_media_trash_retention_days_0', sql.raw("typeof(\"media_trash_retention_days\") = 'integer' AND \"media_trash_retention_days\" BETWEEN -9007199254740991 AND 9007199254740991")),
  check('ck_global_settings_media_trash_retention_days_1', sql.raw("\"media_trash_retention_days\" >= 0")),
  check('ck_global_settings_news_pdf_allow_download_0', sql.raw("\"news_pdf_allow_download\" IN (0, 1)")),
  check('ck_global_settings_translation_providers_0', sql.raw("CASE WHEN json_valid(\"translation_providers\") THEN json_type(\"translation_providers\") = 'array' ELSE 0 END")),
  check('ck_global_settings_translation_batch_size_0', sql.raw("typeof(\"translation_batch_size\") = 'integer' AND \"translation_batch_size\" BETWEEN -9007199254740991 AND 9007199254740991")),
  check('ck_global_settings_translation_batch_size_1', sql.raw("\"translation_batch_size\" >= 1")),
  check('ck_global_settings_translation_batch_size_2', sql.raw("\"translation_batch_size\" <= 50")),
  check('ck_global_settings_translation_worker_count_0', sql.raw("typeof(\"translation_worker_count\") = 'integer' AND \"translation_worker_count\" BETWEEN -9007199254740991 AND 9007199254740991")),
  check('ck_global_settings_translation_worker_count_1', sql.raw("\"translation_worker_count\" >= 1")),
  check('ck_global_settings_translation_worker_count_2', sql.raw("\"translation_worker_count\" <= 8")),
  check('ck_global_settings_translation_timeout_seconds_0', sql.raw("typeof(\"translation_timeout_seconds\") = 'integer' AND \"translation_timeout_seconds\" BETWEEN -9007199254740991 AND 9007199254740991")),
  check('ck_global_settings_translation_timeout_seconds_1', sql.raw("\"translation_timeout_seconds\" >= 1")),
  check('ck_global_settings_translation_timeout_seconds_2', sql.raw("\"translation_timeout_seconds\" <= 120")),
  check('ck_global_settings_translation_job_state_0', sql.raw("CASE WHEN json_valid(\"translation_job_state\") THEN json_type(\"translation_job_state\") = 'object' ELSE 0 END")),
  check('ck_global_settings_publication_metadata_providers_0', sql.raw("CASE WHEN json_valid(\"publication_metadata_providers\") THEN json_type(\"publication_metadata_providers\") = 'array' ELSE 0 END")),
  check('ck_global_settings_publication_suggestion_cache_seconds_0', sql.raw("typeof(\"publication_suggestion_cache_seconds\") = 'integer' AND \"publication_suggestion_cache_seconds\" BETWEEN -9007199254740991 AND 9007199254740991")),
  check('ck_global_settings_publication_suggestion_cache_seconds_1', sql.raw("\"publication_suggestion_cache_seconds\" >= 0")),
  check('ck_global_settings_profile_suggestion_cache_seconds_0', sql.raw("typeof(\"profile_suggestion_cache_seconds\") = 'integer' AND \"profile_suggestion_cache_seconds\" BETWEEN -9007199254740991 AND 9007199254740991")),
  check('ck_global_settings_profile_suggestion_cache_seconds_1', sql.raw("\"profile_suggestion_cache_seconds\" >= 0")),
  check('ck_global_settings_project_suggestion_cache_seconds_0', sql.raw("typeof(\"project_suggestion_cache_seconds\") = 'integer' AND \"project_suggestion_cache_seconds\" BETWEEN -9007199254740991 AND 9007199254740991")),
  check('ck_global_settings_project_suggestion_cache_seconds_1', sql.raw("\"project_suggestion_cache_seconds\" >= 0")),
  check('ck_global_settings_patent_suggestion_cache_seconds_0', sql.raw("typeof(\"patent_suggestion_cache_seconds\") = 'integer' AND \"patent_suggestion_cache_seconds\" BETWEEN -9007199254740991 AND 9007199254740991")),
  check('ck_global_settings_patent_suggestion_cache_seconds_1', sql.raw("\"patent_suggestion_cache_seconds\" >= 0")),
  check('ck_global_settings_student_suggestion_cache_seconds_0', sql.raw("typeof(\"student_suggestion_cache_seconds\") = 'integer' AND \"student_suggestion_cache_seconds\" BETWEEN -9007199254740991 AND 9007199254740991")),
  check('ck_global_settings_student_suggestion_cache_seconds_1', sql.raw("\"student_suggestion_cache_seconds\" >= 0")),
  check('ck_global_settings_news_suggestion_cache_seconds_0', sql.raw("typeof(\"news_suggestion_cache_seconds\") = 'integer' AND \"news_suggestion_cache_seconds\" BETWEEN -9007199254740991 AND 9007199254740991")),
  check('ck_global_settings_news_suggestion_cache_seconds_1', sql.raw("\"news_suggestion_cache_seconds\" >= 0")),
  check('ck_global_settings_course_suggestion_cache_seconds_0', sql.raw("typeof(\"course_suggestion_cache_seconds\") = 'integer' AND \"course_suggestion_cache_seconds\" BETWEEN -9007199254740991 AND 9007199254740991")),
  check('ck_global_settings_course_suggestion_cache_seconds_1', sql.raw("\"course_suggestion_cache_seconds\" >= 0")),
  check('ck_global_settings_patent_metadata_providers_0', sql.raw("CASE WHEN json_valid(\"patent_metadata_providers\") THEN json_type(\"patent_metadata_providers\") = 'array' ELSE 0 END")),
])

export const navigationItems = sqliteTable('navigation_items', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  uid: text('uid').notNull().unique(),
  created_at: text('created_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  updated_at: text('updated_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  title: text('title').notNull(),
  title_en: text('title_en'),
  kind: text('kind'),
  url_name: text('url_name'),
  path: text('path'),
  fragment: text('fragment'),
  icon: text('icon'),
  style: text('style'),
  location: text('location'),
  visibility: text('visibility').$type<"public" | "authenticated" | "staff" | "owner" | "hidden">().notNull().default(sql.raw("'hidden'")),
  enabled: integer('enabled', { mode: 'boolean' }).notNull().default(sql.raw("0")),
  sort_order: integer('sort_order').notNull().default(sql.raw("0")),
}, t => [
  check('ck_navigation_items_uid_0', sql.raw("length(trim(\"uid\")) > 0")),
  check('ck_navigation_items_uid_1', sql.raw("length(\"uid\") <= 128")),
  check('ck_navigation_items_created_at_0', sql.raw("length(\"created_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"created_at\", '+0 seconds') = \"created_at\", 0)")),
  check('ck_navigation_items_updated_at_0', sql.raw("length(\"updated_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"updated_at\", '+0 seconds') = \"updated_at\", 0)")),
  check('ck_navigation_items_title_0', sql.raw("length(trim(\"title\")) > 0")),
  check('ck_navigation_items_visibility_0', sql.raw("\"visibility\" IN ('public', 'authenticated', 'staff', 'owner', 'hidden')")),
  check('ck_navigation_items_enabled_0', sql.raw("\"enabled\" IN (0, 1)")),
  check('ck_navigation_items_sort_order_0', sql.raw("typeof(\"sort_order\") = 'integer' AND \"sort_order\" BETWEEN -9007199254740991 AND 9007199254740991")),
  index('idx_navigation_items_visibility_sort').on(t.visibility, t.sort_order, t.id),
  index('idx_navigation_items_location').on(t.location, t.enabled, t.visibility, t.sort_order, t.id),
])

export const researchInterests = sqliteTable('research_interests', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  uid: text('uid').notNull().unique(),
  created_at: text('created_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  updated_at: text('updated_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  name: text('name').notNull(),
  name_en: text('name_en'),
  description: text('description'),
  sort_order: integer('sort_order').notNull().default(sql.raw("0")),
  visibility: text('visibility').$type<"public" | "authenticated" | "staff" | "owner" | "hidden">().notNull().default(sql.raw("'hidden'")),
}, t => [
  check('ck_research_interests_uid_0', sql.raw("length(trim(\"uid\")) > 0")),
  check('ck_research_interests_uid_1', sql.raw("length(\"uid\") <= 128")),
  check('ck_research_interests_created_at_0', sql.raw("length(\"created_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"created_at\", '+0 seconds') = \"created_at\", 0)")),
  check('ck_research_interests_updated_at_0', sql.raw("length(\"updated_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"updated_at\", '+0 seconds') = \"updated_at\", 0)")),
  check('ck_research_interests_name_0', sql.raw("length(trim(\"name\")) > 0")),
  check('ck_research_interests_sort_order_0', sql.raw("typeof(\"sort_order\") = 'integer' AND \"sort_order\" BETWEEN -9007199254740991 AND 9007199254740991")),
  check('ck_research_interests_visibility_0', sql.raw("\"visibility\" IN ('public', 'authenticated', 'staff', 'owner', 'hidden')")),
  index('idx_research_interests_visibility_sort').on(t.visibility, t.sort_order, t.id),
])

export const publications = sqliteTable('publications', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  uid: text('uid').notNull().unique(),
  created_at: text('created_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  updated_at: text('updated_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  title: text('title').notNull(),
  source_citation: text('source_citation'),
  authors: text('authors'),
  venue: text('venue'),
  year: integer('year'),
  volume: text('volume'),
  issue: text('issue'),
  pages: text('pages'),
  doi: text('doi'),
  url: text('url'),
  pdf_key: text('pdf_key').references(() => mediaAssets.object_key, { onDelete: 'restrict', onUpdate: 'restrict' }),
  bibtex: text('bibtex'),
  citation_gbt: text('citation_gbt'),
  citation_elsevier: text('citation_elsevier'),
  citation_apa: text('citation_apa'),
  citation_ieee: text('citation_ieee'),
  highlight_gbt: text('highlight_gbt'),
  highlight_elsevier: text('highlight_elsevier'),
  highlight_apa: text('highlight_apa'),
  highlight_ieee: text('highlight_ieee'),
  publication_type: text('publication_type'),
  author_role: text('author_role'),
  corresponding_authors: text('corresponding_authors'),
  index_type: text('index_type'),
  display_tags: text('display_tags'),
  abstract: text('abstract'),
  keywords: text('keywords'),
  pdf_visibility: text('pdf_visibility').$type<"public" | "authenticated" | "staff" | "owner" | "hidden">().notNull().default(sql.raw("'hidden'")),
  visibility: text('visibility').$type<"public" | "authenticated" | "staff" | "owner" | "hidden">().notNull().default(sql.raw("'hidden'")),
  is_featured: integer('is_featured', { mode: 'boolean' }).notNull().default(sql.raw("0")),
  sort_order: integer('sort_order').notNull().default(sql.raw("0")),
}, t => [
  check('ck_publications_uid_0', sql.raw("length(trim(\"uid\")) > 0")),
  check('ck_publications_uid_1', sql.raw("length(\"uid\") <= 128")),
  check('ck_publications_created_at_0', sql.raw("length(\"created_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"created_at\", '+0 seconds') = \"created_at\", 0)")),
  check('ck_publications_updated_at_0', sql.raw("length(\"updated_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"updated_at\", '+0 seconds') = \"updated_at\", 0)")),
  check('ck_publications_title_0', sql.raw("length(trim(\"title\")) > 0")),
  check('ck_publications_year_0', sql.raw("\"year\" IS NULL OR (typeof(\"year\") = 'integer' AND \"year\" BETWEEN -9007199254740991 AND 9007199254740991)")),
  check('ck_publications_year_1', sql.raw("\"year\" IS NULL OR (\"year\" >= 1)")),
  check('ck_publications_year_2', sql.raw("\"year\" IS NULL OR (\"year\" <= 9999)")),
  check('ck_publications_pdf_visibility_0', sql.raw("\"pdf_visibility\" IN ('public', 'authenticated', 'staff', 'owner', 'hidden')")),
  check('ck_publications_visibility_0', sql.raw("\"visibility\" IN ('public', 'authenticated', 'staff', 'owner', 'hidden')")),
  check('ck_publications_is_featured_0', sql.raw("\"is_featured\" IN (0, 1)")),
  check('ck_publications_sort_order_0', sql.raw("typeof(\"sort_order\") = 'integer' AND \"sort_order\" BETWEEN -9007199254740991 AND 9007199254740991")),
  index('idx_publications_visibility_sort').on(t.visibility, t.sort_order, t.id),
  index('idx_publications_featured').on(t.visibility, t.is_featured, t.sort_order, t.id),
  index('idx_publications_pdf_key').on(t.pdf_key),
  index('idx_publications_visibility_year').on(t.visibility, sql`${t.year} DESC`, t.sort_order, t.id),
])

export const projects = sqliteTable('projects', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  uid: text('uid').notNull().unique(),
  created_at: text('created_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  updated_at: text('updated_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  name: text('name').notNull(),
  source: text('source'),
  fund_name: text('fund_name'),
  project_number: text('project_number'),
  project_role: text('project_role'),
  principal: text('principal'),
  members: text('members'),
  start_date: text('start_date'),
  end_date: text('end_date'),
  status: text('status'),
  amount: text('amount'),
  summary: text('summary'),
  visibility: text('visibility').$type<"public" | "authenticated" | "staff" | "owner" | "hidden">().notNull().default(sql.raw("'hidden'")),
  is_featured: integer('is_featured', { mode: 'boolean' }).notNull().default(sql.raw("0")),
  sort_order: integer('sort_order').notNull().default(sql.raw("0")),
}, t => [
  check('ck_projects_uid_0', sql.raw("length(trim(\"uid\")) > 0")),
  check('ck_projects_uid_1', sql.raw("length(\"uid\") <= 128")),
  check('ck_projects_created_at_0', sql.raw("length(\"created_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"created_at\", '+0 seconds') = \"created_at\", 0)")),
  check('ck_projects_updated_at_0', sql.raw("length(\"updated_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"updated_at\", '+0 seconds') = \"updated_at\", 0)")),
  check('ck_projects_name_0', sql.raw("length(trim(\"name\")) > 0")),
  check('ck_projects_start_date_0', sql.raw("\"start_date\" IS NULL OR (length(\"start_date\") = 10 AND COALESCE(strftime('%Y-%m-%d', \"start_date\", '+0 days') = \"start_date\", 0))")),
  check('ck_projects_end_date_0', sql.raw("\"end_date\" IS NULL OR (length(\"end_date\") = 10 AND COALESCE(strftime('%Y-%m-%d', \"end_date\", '+0 days') = \"end_date\", 0))")),
  check('ck_projects_amount_0', sql.raw("\"amount\" IS NULL OR (length(\"amount\") BETWEEN 1 AND 23 AND \"amount\" NOT GLOB '*[^0-9.]*' AND \"amount\" NOT LIKE '%.%.%' AND substr(\"amount\", 1, 1) GLOB '[0-9]' AND substr(\"amount\", -1, 1) GLOB '[0-9]' AND (instr(\"amount\", '.') = 0 AND length(\"amount\") <= 18 OR instr(\"amount\", '.') BETWEEN 2 AND 19 AND length(\"amount\") - instr(\"amount\", '.') BETWEEN 1 AND 4) AND (substr(\"amount\", 1, 1) != '0' OR \"amount\" = '0' OR substr(\"amount\", 1, 2) = '0.'))")),
  check('ck_projects_visibility_0', sql.raw("\"visibility\" IN ('public', 'authenticated', 'staff', 'owner', 'hidden')")),
  check('ck_projects_is_featured_0', sql.raw("\"is_featured\" IN (0, 1)")),
  check('ck_projects_sort_order_0', sql.raw("typeof(\"sort_order\") = 'integer' AND \"sort_order\" BETWEEN -9007199254740991 AND 9007199254740991")),
  index('idx_projects_visibility_sort').on(t.visibility, t.sort_order, t.id),
  index('idx_projects_featured').on(t.visibility, t.is_featured, t.sort_order, t.id),
  index('idx_projects_visibility_start_date').on(t.visibility, sql`${t.start_date} DESC`, t.sort_order, t.id),
])

export const patents = sqliteTable('patents', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  uid: text('uid').notNull().unique(),
  created_at: text('created_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  updated_at: text('updated_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  name: text('name').notNull(),
  country: text('country'),
  patent_type: text('patent_type'),
  application_number: text('application_number'),
  grant_number: text('grant_number'),
  application_date: text('application_date'),
  grant_date: text('grant_date'),
  inventors: text('inventors'),
  owner: text('owner'),
  legal_status: text('legal_status'),
  summary: text('summary'),
  certificate_key: text('certificate_key').references(() => mediaAssets.object_key, { onDelete: 'restrict', onUpdate: 'restrict' }),
  visibility: text('visibility').$type<"public" | "authenticated" | "staff" | "owner" | "hidden">().notNull().default(sql.raw("'hidden'")),
  is_featured: integer('is_featured', { mode: 'boolean' }).notNull().default(sql.raw("0")),
  sort_order: integer('sort_order').notNull().default(sql.raw("0")),
}, t => [
  check('ck_patents_uid_0', sql.raw("length(trim(\"uid\")) > 0")),
  check('ck_patents_uid_1', sql.raw("length(\"uid\") <= 128")),
  check('ck_patents_created_at_0', sql.raw("length(\"created_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"created_at\", '+0 seconds') = \"created_at\", 0)")),
  check('ck_patents_updated_at_0', sql.raw("length(\"updated_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"updated_at\", '+0 seconds') = \"updated_at\", 0)")),
  check('ck_patents_name_0', sql.raw("length(trim(\"name\")) > 0")),
  check('ck_patents_application_date_0', sql.raw("\"application_date\" IS NULL OR (length(\"application_date\") = 10 AND COALESCE(strftime('%Y-%m-%d', \"application_date\", '+0 days') = \"application_date\", 0))")),
  check('ck_patents_grant_date_0', sql.raw("\"grant_date\" IS NULL OR (length(\"grant_date\") = 10 AND COALESCE(strftime('%Y-%m-%d', \"grant_date\", '+0 days') = \"grant_date\", 0))")),
  check('ck_patents_visibility_0', sql.raw("\"visibility\" IN ('public', 'authenticated', 'staff', 'owner', 'hidden')")),
  check('ck_patents_is_featured_0', sql.raw("\"is_featured\" IN (0, 1)")),
  check('ck_patents_sort_order_0', sql.raw("typeof(\"sort_order\") = 'integer' AND \"sort_order\" BETWEEN -9007199254740991 AND 9007199254740991")),
  index('idx_patents_visibility_sort').on(t.visibility, t.sort_order, t.id),
  index('idx_patents_featured').on(t.visibility, t.is_featured, t.sort_order, t.id),
  index('idx_patents_certificate_key').on(t.certificate_key),
])

export const students = sqliteTable('students', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  uid: text('uid').notNull().unique(),
  created_at: text('created_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  updated_at: text('updated_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  name: text('name').notNull(),
  name_en: text('name_en'),
  avatar_key: text('avatar_key').references(() => mediaAssets.object_key, { onDelete: 'restrict', onUpdate: 'restrict' }),
  student_id: text('student_id'),
  degree: text('degree'),
  category: text('category'),
  grade: text('grade'),
  direction: text('direction'),
  status: text('status'),
  email: text('email'),
  homepage: text('homepage'),
  enrollment_date: text('enrollment_date'),
  graduation_date: text('graduation_date'),
  destination: text('destination'),
  awards: text('awards'),
  bio: text('bio'),
  contact_visibility: text('contact_visibility').$type<"public" | "authenticated" | "staff" | "owner" | "hidden">().notNull().default(sql.raw("'hidden'")),
  visibility: text('visibility').$type<"public" | "authenticated" | "staff" | "owner" | "hidden">().notNull().default(sql.raw("'hidden'")),
  is_featured: integer('is_featured', { mode: 'boolean' }).notNull().default(sql.raw("0")),
  sort_order: integer('sort_order').notNull().default(sql.raw("0")),
}, t => [
  check('ck_students_uid_0', sql.raw("length(trim(\"uid\")) > 0")),
  check('ck_students_uid_1', sql.raw("length(\"uid\") <= 128")),
  check('ck_students_created_at_0', sql.raw("length(\"created_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"created_at\", '+0 seconds') = \"created_at\", 0)")),
  check('ck_students_updated_at_0', sql.raw("length(\"updated_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"updated_at\", '+0 seconds') = \"updated_at\", 0)")),
  check('ck_students_name_0', sql.raw("length(trim(\"name\")) > 0")),
  check('ck_students_enrollment_date_0', sql.raw("\"enrollment_date\" IS NULL OR (length(\"enrollment_date\") = 10 AND COALESCE(strftime('%Y-%m-%d', \"enrollment_date\", '+0 days') = \"enrollment_date\", 0))")),
  check('ck_students_graduation_date_0', sql.raw("\"graduation_date\" IS NULL OR (length(\"graduation_date\") = 10 AND COALESCE(strftime('%Y-%m-%d', \"graduation_date\", '+0 days') = \"graduation_date\", 0))")),
  check('ck_students_contact_visibility_0', sql.raw("\"contact_visibility\" IN ('public', 'authenticated', 'staff', 'owner', 'hidden')")),
  check('ck_students_visibility_0', sql.raw("\"visibility\" IN ('public', 'authenticated', 'staff', 'owner', 'hidden')")),
  check('ck_students_is_featured_0', sql.raw("\"is_featured\" IN (0, 1)")),
  check('ck_students_sort_order_0', sql.raw("typeof(\"sort_order\") = 'integer' AND \"sort_order\" BETWEEN -9007199254740991 AND 9007199254740991")),
  index('idx_students_visibility_sort').on(t.visibility, t.sort_order, t.id),
  index('idx_students_featured').on(t.visibility, t.is_featured, t.sort_order, t.id),
  index('idx_students_avatar_key').on(t.avatar_key),
  index('idx_students_group').on(t.visibility, t.category, t.status, t.sort_order, t.id),
])

export const studentCategoryDisplays = sqliteTable('student_category_displays', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  uid: text('uid').notNull().unique(),
  created_at: text('created_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  updated_at: text('updated_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  key: text('key').notNull().unique(),
  label: text('label').notNull(),
  label_en: text('label_en'),
  keywords: text('keywords'),
  enabled: integer('enabled', { mode: 'boolean' }).notNull().default(sql.raw("0")),
  display_order: integer('display_order').notNull().default(sql.raw("0")),
}, t => [
  check('ck_student_category_displays_uid_0', sql.raw("length(trim(\"uid\")) > 0")),
  check('ck_student_category_displays_uid_1', sql.raw("length(\"uid\") <= 128")),
  check('ck_student_category_displays_created_at_0', sql.raw("length(\"created_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"created_at\", '+0 seconds') = \"created_at\", 0)")),
  check('ck_student_category_displays_updated_at_0', sql.raw("length(\"updated_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"updated_at\", '+0 seconds') = \"updated_at\", 0)")),
  check('ck_student_category_displays_key_0', sql.raw("length(trim(\"key\")) > 0")),
  check('ck_student_category_displays_label_0', sql.raw("length(trim(\"label\")) > 0")),
  check('ck_student_category_displays_enabled_0', sql.raw("\"enabled\" IN (0, 1)")),
  check('ck_student_category_displays_display_order_0', sql.raw("typeof(\"display_order\") = 'integer' AND \"display_order\" BETWEEN -9007199254740991 AND 9007199254740991")),
])

export const news = sqliteTable('news', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  uid: text('uid').notNull().unique(),
  created_at: text('created_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  updated_at: text('updated_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  title: text('title').notNull(),
  slug: text('slug').notNull().unique(),
  category: text('category'),
  cover_key: text('cover_key').references(() => mediaAssets.object_key, { onDelete: 'restrict', onUpdate: 'restrict' }),
  content: text('content'),
  content_format: text('content_format').$type<"plain" | "html" | "markdown">().notNull().default(sql.raw("'plain'")),
  related_publication_uid: text('related_publication_uid').references(() => publications.uid, { onDelete: 'set null', onUpdate: 'restrict' }),
  related_project_uid: text('related_project_uid').references(() => projects.uid, { onDelete: 'set null', onUpdate: 'restrict' }),
  related_student_uid: text('related_student_uid').references(() => students.uid, { onDelete: 'set null', onUpdate: 'restrict' }),
  allow_comments: integer('allow_comments', { mode: 'boolean' }).notNull().default(sql.raw("0")),
  published_at: text('published_at'),
  visibility: text('visibility').$type<"public" | "authenticated" | "staff" | "owner" | "hidden">().notNull().default(sql.raw("'hidden'")),
  is_featured: integer('is_featured', { mode: 'boolean' }).notNull().default(sql.raw("0")),
  sort_order: integer('sort_order').notNull().default(sql.raw("0")),
}, t => [
  check('ck_news_uid_0', sql.raw("length(trim(\"uid\")) > 0")),
  check('ck_news_uid_1', sql.raw("length(\"uid\") <= 128")),
  check('ck_news_created_at_0', sql.raw("length(\"created_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"created_at\", '+0 seconds') = \"created_at\", 0)")),
  check('ck_news_updated_at_0', sql.raw("length(\"updated_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"updated_at\", '+0 seconds') = \"updated_at\", 0)")),
  check('ck_news_title_0', sql.raw("length(trim(\"title\")) > 0")),
  check('ck_news_slug_0', sql.raw("length(trim(\"slug\")) > 0")),
  check('ck_news_content_format_0', sql.raw("\"content_format\" IN ('plain', 'html', 'markdown')")),
  check('ck_news_allow_comments_0', sql.raw("\"allow_comments\" IN (0, 1)")),
  check('ck_news_published_at_0', sql.raw("\"published_at\" IS NULL OR (length(\"published_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"published_at\", '+0 seconds') = \"published_at\", 0))")),
  check('ck_news_visibility_0', sql.raw("\"visibility\" IN ('public', 'authenticated', 'staff', 'owner', 'hidden')")),
  check('ck_news_is_featured_0', sql.raw("\"is_featured\" IN (0, 1)")),
  check('ck_news_sort_order_0', sql.raw("typeof(\"sort_order\") = 'integer' AND \"sort_order\" BETWEEN -9007199254740991 AND 9007199254740991")),
  index('idx_news_visibility_sort').on(t.visibility, t.sort_order, t.id),
  index('idx_news_featured').on(t.visibility, t.is_featured, t.sort_order, t.id),
  index('idx_news_cover_key').on(t.cover_key),
  index('idx_news_related_publication_uid').on(t.related_publication_uid),
  index('idx_news_related_project_uid').on(t.related_project_uid),
  index('idx_news_related_student_uid').on(t.related_student_uid),
  index('idx_news_published').on(t.visibility, sql`${t.published_at} DESC`, t.sort_order, t.id),
])

export const courses = sqliteTable('courses', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  uid: text('uid').notNull().unique(),
  created_at: text('created_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  updated_at: text('updated_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  name: text('name').notNull(),
  semester: text('semester'),
  audience: text('audience'),
  summary: text('summary'),
  syllabus_key: text('syllabus_key').references(() => mediaAssets.object_key, { onDelete: 'restrict', onUpdate: 'restrict' }),
  material_key: text('material_key').references(() => mediaAssets.object_key, { onDelete: 'restrict', onUpdate: 'restrict' }),
  material_visibility: text('material_visibility').$type<"public" | "authenticated" | "staff" | "owner" | "hidden">().notNull().default(sql.raw("'hidden'")),
  references_text: text('references_text'),
  visibility: text('visibility').$type<"public" | "authenticated" | "staff" | "owner" | "hidden">().notNull().default(sql.raw("'hidden'")),
  is_featured: integer('is_featured', { mode: 'boolean' }).notNull().default(sql.raw("0")),
  sort_order: integer('sort_order').notNull().default(sql.raw("0")),
}, t => [
  check('ck_courses_uid_0', sql.raw("length(trim(\"uid\")) > 0")),
  check('ck_courses_uid_1', sql.raw("length(\"uid\") <= 128")),
  check('ck_courses_created_at_0', sql.raw("length(\"created_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"created_at\", '+0 seconds') = \"created_at\", 0)")),
  check('ck_courses_updated_at_0', sql.raw("length(\"updated_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"updated_at\", '+0 seconds') = \"updated_at\", 0)")),
  check('ck_courses_name_0', sql.raw("length(trim(\"name\")) > 0")),
  check('ck_courses_material_visibility_0', sql.raw("\"material_visibility\" IN ('public', 'authenticated', 'staff', 'owner', 'hidden')")),
  check('ck_courses_visibility_0', sql.raw("\"visibility\" IN ('public', 'authenticated', 'staff', 'owner', 'hidden')")),
  check('ck_courses_is_featured_0', sql.raw("\"is_featured\" IN (0, 1)")),
  check('ck_courses_sort_order_0', sql.raw("typeof(\"sort_order\") = 'integer' AND \"sort_order\" BETWEEN -9007199254740991 AND 9007199254740991")),
  index('idx_courses_visibility_sort').on(t.visibility, t.sort_order, t.id),
  index('idx_courses_featured').on(t.visibility, t.is_featured, t.sort_order, t.id),
  index('idx_courses_syllabus_key').on(t.syllabus_key),
  index('idx_courses_material_key').on(t.material_key),
  index('idx_courses_visibility_semester').on(t.visibility, sql`${t.semester} DESC`, t.sort_order, t.id),
])

export const messages = sqliteTable('messages', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  uid: text('uid').notNull().unique(),
  created_at: text('created_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  updated_at: text('updated_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  name: text('name'),
  email: text('email'),
  message_type: text('message_type'),
  subject: text('subject'),
  content: text('content').notNull(),
  attachment_key: text('attachment_key').references(() => mediaAssets.object_key, { onDelete: 'restrict', onUpdate: 'restrict' }),
  status: text('status').notNull().default(sql.raw("'new'")),
  visibility: text('visibility').$type<"public" | "authenticated" | "staff" | "owner" | "hidden">().notNull().default(sql.raw("'hidden'")),
}, t => [
  check('ck_messages_uid_0', sql.raw("length(trim(\"uid\")) > 0")),
  check('ck_messages_uid_1', sql.raw("length(\"uid\") <= 128")),
  check('ck_messages_created_at_0', sql.raw("length(\"created_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"created_at\", '+0 seconds') = \"created_at\", 0)")),
  check('ck_messages_updated_at_0', sql.raw("length(\"updated_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"updated_at\", '+0 seconds') = \"updated_at\", 0)")),
  check('ck_messages_content_0', sql.raw("length(trim(\"content\")) > 0")),
  check('ck_messages_visibility_0', sql.raw("\"visibility\" IN ('public', 'authenticated', 'staff', 'owner', 'hidden')")),
  index('idx_messages_attachment_key').on(t.attachment_key),
  index('idx_messages_status_created').on(t.status, sql`${t.created_at} DESC`, t.id),
])

export const translationCache = sqliteTable('translation_cache', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  uid: text('uid').notNull().unique(),
  created_at: text('created_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  updated_at: text('updated_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  source_hash: text('source_hash').notNull(),
  source_ref_key: text('source_ref_key').notNull(),
  source_text: text('source_text').notNull(),
  source_lang: text('source_lang').notNull(),
  target_lang: text('target_lang').notNull(),
  translated_text: text('translated_text'),
  provider: text('provider'),
  status: text('status').$type<"pending" | "success" | "failed">().notNull().default(sql.raw("'pending'")),
  is_manual: integer('is_manual', { mode: 'boolean' }).notNull().default(sql.raw("0")),
  is_current: integer('is_current', { mode: 'boolean' }).notNull().default(sql.raw("0")),
  source_refs: text('source_refs', { mode: 'json' }).$type<JsonValue>().notNull().default(sql.raw("'[]'")),
  error_message: text('error_message'),
}, t => [
  check('ck_translation_cache_uid_0', sql.raw("length(trim(\"uid\")) > 0")),
  check('ck_translation_cache_uid_1', sql.raw("length(\"uid\") <= 128")),
  check('ck_translation_cache_created_at_0', sql.raw("length(\"created_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"created_at\", '+0 seconds') = \"created_at\", 0)")),
  check('ck_translation_cache_updated_at_0', sql.raw("length(\"updated_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"updated_at\", '+0 seconds') = \"updated_at\", 0)")),
  check('ck_translation_cache_source_hash_0', sql.raw("length(trim(\"source_hash\")) > 0")),
  check('ck_translation_cache_source_hash_1', sql.raw("length(\"source_hash\") >= 64")),
  check('ck_translation_cache_source_hash_2', sql.raw("length(\"source_hash\") <= 64")),
  check('ck_translation_cache_source_ref_key_0', sql.raw("length(trim(\"source_ref_key\")) > 0")),
  check('ck_translation_cache_source_text_0', sql.raw("length(trim(\"source_text\")) > 0")),
  check('ck_translation_cache_source_lang_0', sql.raw("length(trim(\"source_lang\")) > 0")),
  check('ck_translation_cache_target_lang_0', sql.raw("length(trim(\"target_lang\")) > 0")),
  check('ck_translation_cache_status_0', sql.raw("\"status\" IN ('pending', 'success', 'failed')")),
  check('ck_translation_cache_is_manual_0', sql.raw("\"is_manual\" IN (0, 1)")),
  check('ck_translation_cache_is_current_0', sql.raw("\"is_current\" IN (0, 1)")),
  check('ck_translation_cache_source_refs_0', sql.raw("CASE WHEN json_valid(\"source_refs\") THEN json_type(\"source_refs\") = 'array' ELSE 0 END")),
  index('idx_translation_cache_hash_language').on(t.source_hash, t.target_lang, t.is_current),
  index('idx_translation_cache_ref_language').on(t.source_ref_key, t.target_lang, t.is_current),
  uniqueIndex('idx_translation_cache_one_current').on(t.source_ref_key, t.target_lang).where(sql.raw("\"is_current\" = 1 AND \"status\" = 'success'")),
])

export const operationLogs = sqliteTable('operation_logs', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  uid: text('uid').notNull().unique(),
  created_at: text('created_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  updated_at: text('updated_at').notNull().default(sql.raw("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
  actor_uid: text('actor_uid'),
  actor_name: text('actor_name'),
  action: text('action').notNull(),
  module: text('module').notNull(),
  target_uid: text('target_uid'),
  summary: text('summary'),
  detail_json: text('detail_json', { mode: 'json' }).$type<JsonValue>().notNull().default(sql.raw("'{}'")),
  status: text('status'),
}, t => [
  check('ck_operation_logs_uid_0', sql.raw("length(trim(\"uid\")) > 0")),
  check('ck_operation_logs_uid_1', sql.raw("length(\"uid\") <= 128")),
  check('ck_operation_logs_created_at_0', sql.raw("length(\"created_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"created_at\", '+0 seconds') = \"created_at\", 0)")),
  check('ck_operation_logs_updated_at_0', sql.raw("length(\"updated_at\") = 24 AND COALESCE(strftime('%Y-%m-%dT%H:%M:%fZ', \"updated_at\", '+0 seconds') = \"updated_at\", 0)")),
  check('ck_operation_logs_action_0', sql.raw("length(trim(\"action\")) > 0")),
  check('ck_operation_logs_module_0', sql.raw("length(trim(\"module\")) > 0")),
  check('ck_operation_logs_detail_json_0', sql.raw("CASE WHEN json_valid(\"detail_json\") THEN json_type(\"detail_json\") = 'object' ELSE 0 END")),
  index('idx_operation_logs_module_created').on(t.module, sql`${t.created_at} DESC`, t.id),
])

export const schema = { mediaAssets, authRoles, authUsers, authPermissions, profiles, siteSettings, globalSettings, navigationItems, researchInterests, publications, projects, patents, students, studentCategoryDisplays, news, courses, messages, translationCache, operationLogs }
