<script setup lang="ts">
import { ref, computed, watch, nextTick, onMounted, onBeforeUnmount } from '#imports'
import { useTransferSession } from '../composables/useTransferSession'
import { useTransferFiles } from '../composables/useTransferFiles'
import { useDirectTransfer } from '../composables/useDirectTransfer'
import {recoveryReason} from '../../shared/recovery.mjs'
import type {RecoveryInfo} from '../files/peer.mjs'
import { NETWORK_REASONS } from '../../shared/network.mjs'
import { vpnReason, VPN_REASONS } from '../../shared/vpn.mjs'
import { readPairCode, readShareToken, transferHint } from '../files/peer.mjs'
import { browserFileSupport } from '../files/save.mjs'
import qrcode from 'qrcode-generator'
const props = defineProps<{mode:'send'|'receive';zh:boolean}>()
const {session,auth} = useTransferSession(); const files = useTransferFiles()
const {state,peer} = useDirectTransfer(async (role,transport) => {
  const current = auth.session.value
  try { return await $fetch<{ticket:string;networks:string;signalPath:string}>('/transfer-api/v1/pairing-ticket', {method:'PUT',body:{role,transport:transport||'lan-direct'},headers:current.authenticated?{'x-csrf-token':current.csrfToken}:{},retry:0,timeout:6500}) }
  catch(e) { const error=e as {data?:{error?:{code?:string}}}; throw {code:error.data?.error?.code || 'FT_SIGNAL_UNAVAILABLE'} }
})
const code = files.receiveCode; const secure=ref(false),rtc=ref(false),transport=ref('lan-direct'); const supported=computed(()=>secure.value&&(!['lan-direct','wan-direct'].includes(transport.value)||rtc.value)); const support = ref({directoryRead:false,directoryWrite:false,streamSave:false}); const visible = ref(100); const copied = ref(false)
const more=ref<HTMLElement|null>(null); let observer:IntersectionObserver|null=null; let mounted=false
async function observe(){await nextTick();observer?.disconnect();if(mounted && more.value && typeof IntersectionObserver!=='undefined'){observer=new IntersectionObserver(items=>{if(items.some(i=>i.isIntersecting))visible.value+=100},{rootMargin:'120px'});observer.observe(more.value)}}
watch(()=>[visible.value,state.value.manifest],observe)
const requestedRate = ref('')
const taskRate = computed(() => transport.value==='temporary-share' || requestedRate.value === '' ? null : Number(requestedRate.value))
const rateValid = computed(() => taskRate.value === null || (Number.isSafeInteger(taskRate.value) && taskRate.value >= 1 && taskRate.value <= 1000000000))
const active = computed(() => !['idle','complete','cancelled','error','shared','paused','retrying'].includes(state.value.status))
const recoverable=computed(()=>!!state.value.recovery&&state.value.recovery.expiresAt>Date.now())
const rememberRecovery=ref(false)
function recoveryOwner(){return session.value?.user?'user:'+session.value.user.uid:'guest'}
watch([()=>session.value,rememberRecovery],()=>{if(mounted&&session.value){peer.configureRecovery(recoveryOwner(),rememberRecovery.value);try{localStorage.setItem('file-transfer:remember-recovery',String(rememberRecovery.value))}catch{}}})
async function resumeTask(record:RecoveryInfo|null=null){const role=record?.role||state.value.role;await peer.resume(role==='send'&&files.collection.value.manifest.entries.length?files.collection.value:null,record)}
const matchingHistory=computed(()=>(state.value.history||[]).filter(row=>row.role===props.mode&&row.task!==state.value.recovery?.task))
const sameMode = computed(() => !active.value || state.value.role === props.mode)
const selectedLink=computed(()=>session.value?.policy?.links.find(link=>link.id===transport.value))
const allowed=computed(()=>!!session.value?.policy?.enabled&&!!session.value.policy.rule[props.mode]&&session.value.policy.rule.links.includes(transport.value)&&!session.value.policy.accessReasons?.[props.mode]&&!!selectedLink.value?.available&&!selectedLink.value.accessReasons?.[props.mode])
const transportNames:Record<string,[string,string]>={'lan-direct':['局域网直连 · 同网优先','LAN direct · Nearby first'],'wan-direct':['远程直连 · 双方在线','Internet direct · Both online'],'server-relay':['受控中继 · 直连失败时使用','Controlled relay · When direct fails'],'temporary-share':['临时分享 · 上传后可离线','Temporary share · Leave after upload']}
const validCode=computed(()=>transport.value==='temporary-share'?!!readShareToken(code.value):!!readPairCode(code.value))
watch(code,value=>{if(!active.value){const hint=transferHint(value);if(hint)transport.value=hint}})
watch(()=>state.value.transport,value=>{if(value)transport.value=value})
const revoking=ref(false),revokeError=ref(false)
async function revokeShare(){if(!state.value.share||revoking.value)return;const current=auth.session.value;revoking.value=true;revokeError.value=false;try{await $fetch('/transfer-api/v1/share-action',{method:'PUT',body:{id:state.value.share.id},headers:current.authenticated?{'x-csrf-token':current.csrfToken}:{},retry:0,timeout:6500});peer.stop();peer.update({status:'cancelled',error:'FT_SHARE_UNAVAILABLE',link:'',share:null})}catch{revokeError.value=true}finally{revoking.value=false}}

const qr = computed(() => { if (!state.value.link) return ''; try { const q=qrcode(0,'M');q.addData(state.value.link);q.make();return q.createDataURL(4,16) } catch { return '' } })
const single = computed(() => state.value.manifest?.entries.length === 1 && state.value.manifest.entries[0]?.kind === 'file')
const percent = computed(() => state.value.progress.totalBytes === '0' ? 0 : Math.min(100,Number(BigInt(state.value.progress.bytes)*100n/BigInt(state.value.progress.totalBytes))))
const statusText:Record<string,[string,string]> = {paused:['任务已暂停，可从检查点恢复','Paused; resume from the checkpoint'],retrying:['连接中断，正在准备重试…','Connection interrupted. Preparing retry…'],verifying:['正在核对已完成的内容…','Checking the completed content…'],'waiting-resume':['等待另一方恢复同一任务','Waiting for the other person to resume'],idle:['准备好，连接另一台设备','Ready to connect'],connecting:['正在连接配对服务…','Connecting to pairing service…'],'waiting-peer':['把接收码发给对方','Share this receive code'],confirm:['请确认本次配对','Confirm this pairing'],'waiting-confirmation':['等待另一方确认','Waiting for the other person'],'checking-route':['正在核验直连路径…','Verifying the direct path…'],'share-preview':['文件已暂存，请确认领取','Files are stored. Confirm retrieval.'],shared:['分享已创建，可以离开页面','Share ready. You can leave this page.'],'waiting-save':['连接就绪，等待对方选择保存位置','Connected. Waiting for a save destination.'],'reading-manifest':['正在读取对方的文件清单…','Reading the file manifest…'],'ready-save':['选择保存方式，开始接收','Choose where to save'],transferring:['正在传输并校验…','Transferring and verifying…'],finishing:['文件已保存，正在确认任务结束…','Files saved. Confirming task closure…'],complete:['传输已完成，内容校验通过','Transfer complete; integrity verified'],cancelled:['本次传输已取消','Transfer cancelled'],error:['本次连接未完成','Connection not completed']}
const errors:Record<string,[string,string]> = { ...NETWORK_REASONS, ...VPN_REASONS,
 FT_TOOL_DISABLED:['管理员尚未开放文件传输。','File transfers are not enabled.'],FT_LAN_UNVERIFIED:['请管理员在快传管理页填写并核验局域网网段。','Ask an administrator to configure and verify the LAN ranges.'],
 FT_ACCESS_DENIED:['当前账号或匿名身份没有此操作权限。','Your account or guest access does not allow this action.'],
 FT_QUOTA_DAILY:['今日个人额度不足，请查看剩余额度与重置时间。','Your daily allowance is insufficient. Check the remaining allowance and reset time.'],FT_QUOTA_MONTHLY:['本月个人额度不足，请减小任务或等待重置。','Your monthly allowance is insufficient. Reduce the task size or wait for reset.'],
 FT_GUEST_POOL_DAILY:['匿名访客共享的今日额度不足，匿名链路暂不可用。','The shared daily guest allowance is insufficient. Guest transfers are unavailable.'],FT_GUEST_POOL_MONTHLY:['匿名访客共享的本月额度不足。','The shared monthly guest allowance is insufficient.'],FT_GUEST_POOL_CONCURRENCY:['匿名访客共享的同时任务数已满，请稍后再试。','All shared guest task slots are in use. Try again later.'],FT_GUEST_REQUIRED:['请允许本站 Cookie 后重新生成接收码或连接。','Allow this site’s cookies and start again.'],FT_COMPLETION_UNCONFIRMED:['文件已保存，但服务未确认任务结束。请检查保存结果；不要重复接收。','Files were saved, but task closure was not confirmed. Check the saved files before retrying.'],FT_ACCOUNTING_UNAVAILABLE:['额度记录暂时不可用，连接已停止，请稍后重试。','Allowance recording is unavailable. The connection stopped. Try again later.'],FT_SERVICE_STOPPED:['快传服务已重启，请重新配对。','Transfer service restarted. Pair again.'],
 FT_LAN_ADDRESS_HIDDEN:['浏览器未提供可核验的局域网地址，或地址不在允许网段。本次未发送文件；请管理员检查网络及浏览器策略。','The browser did not expose an allowed LAN address. No files were sent. Ask an administrator to check the network and browser policy.'],
 FT_ROUTE_UNKNOWN:['无法确认当前路径符合已核验的局域网范围，已停止连接。','The selected route could not be verified against the configured LAN ranges. Connection stopped.'],FT_ROUTE_CHANGED:['网络链路发生变化，已停止传输，请重新配对。','The network route changed. Pair again to continue.'],
 FT_CODE_UNAVAILABLE:['接收码无效、已被使用或已过期，请发送方重新生成。','This code is invalid, in use or expired. Ask for a new code.'],FT_PAIRING_EXPIRED:['配对已过期，请重新生成接收码。','Pairing expired. Generate a new code.'],FT_BROWSER_UNSUPPORTED:['请使用 HTTPS 页面及支持 WebRTC 的浏览器。','Use HTTPS and a browser with WebRTC support.'],
 FT_POLICY_CHANGED:['管理员更新了规则，本次传输已停止，请重新配对。','The administrator changed the rules. Pair again.'],FT_AUTH_EXPIRED:['账号授权已失效，传输停止。请重新登录或配对。','Authorization expired. Sign in or pair again.'],FT_AUTH_CHANGED:['登录身份发生变化，传输已停止。','Your sign-in identity changed. Transfer stopped.'],
 FT_FILE_COUNT_LIMIT:['文件数超过当前身份的限制。','Too many files for your access level.'],FT_FILE_SIZE_LIMIT:['单个文件超过允许大小。','A file exceeds the size limit.'],FT_TASK_SIZE_LIMIT:['本次总大小超过允许范围。','This transfer exceeds the task size limit.'],FT_CONCURRENCY:['当前身份的同时任务数已达上限。','Your concurrent task limit has been reached.'],
 FT_MEMORY_LIMIT:['当前浏览器的兼容下载最多 128 MiB，请分批发送，或使用支持流式保存的浏览器。','Fallback saving is limited to 128 MiB. Split the transfer or use a browser with streaming save.'],FT_DOWNLOAD_BUSY:['浏览器仍在处理上一次下载，请稍后重新接收。','Your browser is still handling the previous download. Try again shortly.'],
 FT_INTEGRITY:['内容完整性校验未通过，当前文件已中止写入。','Integrity verification failed. The current file write was aborted.'],FT_FILE_CHANGED:['发送方的源文件已变化，请重新选择。','The source file changed. Select it again.'],FT_CANCELLED:['已取消；已完成的文件可能保留在接收目录中。','Cancelled. Completed files may remain in the destination.'],
 FT_TOO_MANY_ATTEMPTS:['尝试较频繁，请稍后再试。','Too many attempts. Please try again shortly.'],FT_SIGNAL_UNAVAILABLE:['配对服务暂时不可用，请检查快传服务及 WebSocket 代理。','Pairing is unavailable. Check the service and WebSocket proxy.'],FT_CONNECTION_TIMEOUT:['连接超时，请检查双方网络、防火墙和浏览器是否允许局域网直连。','Connection timed out. Check both networks, firewall and LAN access.'],FT_PEER_LEFT:['对方已离开页面或断开连接。','The other device disconnected.'],FT_CONNECTION_CLOSED:['连接已断开，请重新配对。','Connection closed. Pair again.'],FT_TIMEOUT:['等待文件数据超时，请保持双方页面在线后重试。','Data timed out. Keep both pages online and retry.']
}
const unavailableText = computed(() => { const reason=selectedLink.value?.reason||selectedLink.value?.accessReasons?.[props.mode]||session.value?.policy?.accessReasons?.[props.mode]; return reason && errors[reason] ? errors[reason]![props.zh?0:1] : (props.zh?'当前尚未开放此操作；请检查工具开关及账号或匿名权限。':'This action is unavailable. Check tool and account permissions.') })
const errorText = computed(() => /^(FT_RECOVERY_|FT_CHECKPOINT_INVALID|FT_PAUSED|FT_WRITE_FAILED)/.test(state.value.error)?recoveryReason(state.value.error,props.zh):(errors[state.value.error] || ["传输未完成，请检查文件权限、磁盘空间和连接后重试。","Transfer failed. Check file access, disk space and the connection."])[props.zh?0:1])
function size(value:string) { const n=BigInt(value); return n<1048576n?`${n} B`:`${n/1048576n}.${n%1048576n*10n/1048576n} MiB` }
async function copyLink() { try { await navigator.clipboard.writeText(state.value.link); copied.value=true } catch { copied.value=false } }
function beforeUnload(event:BeforeUnloadEvent) { if(active.value||recoverable.value&&!state.value.recoverySaved) {event.preventDefault();event.returnValue=''} }
function pageHide() { if(active.value){if(recoverable.value)peer.pause();else peer.cancel()} }
onMounted(() => { mounted=true;try{rememberRecovery.value=localStorage.getItem('file-transfer:remember-recovery')==='true'}catch{}if(session.value)peer.configureRecovery(recoveryOwner(),rememberRecovery.value);void observe(); secure.value=window.isSecureContext&&typeof WebSocket!=='undefined';rtc.value=typeof RTCPeerConnection!=='undefined'; support.value=browserFileSupport(window); const hash=new URLSearchParams(location.hash.slice(1)),incoming=readShareToken(hash.get('share')||'')||readPairCode(hash.get('receive')||'');if(incoming) {code.value=incoming;transport.value=hash.has('share')?'temporary-share':['wan-direct','server-relay'].includes(hash.get('via')||'')?hash.get('via')!:'lan-direct'; history.replaceState(history.state,'',location.pathname+location.search)};window.addEventListener('beforeunload',beforeUnload);window.addEventListener('pagehide',pageHide) })
onBeforeUnmount(() => {mounted=false;observer?.disconnect();if(!/^\/(zh|en)\/transfer\/?$/.test(window.location.pathname)&&active.value){if(recoverable.value)peer.pause();else peer.cancel();}window.removeEventListener('beforeunload',beforeUnload);window.removeEventListener('pagehide',pageHide)})
watch(() => session.value?.user?.uid, (value,old) => {if(old!==undefined && value!==old && active.value) peer.cancel()})
watch(() => state.value.status, value => { if (mounted && ['waiting-peer','confirm','waiting-save','ready-save','shared','complete','error','cancelled'].includes(value)) window.dispatchEvent(new Event('ft-usage-changed')) })
watch(() => state.value.manifest, () => {visible.value=100})
</script>
<template>
 <section class="ft-pairing" :aria-label="zh?'设备直传':'Device transfer'">
  <div class="ft-selection-heading"><div><p class="ft-eyebrow">{{transport==='temporary-share'?(zh?'临时保存 · 稍后领取':'Temporary storage · Receive later'):(zh?'两台设备 · 双方在线':'Two devices · Both online')}}</p><h2>{{(statusText[state.status] || statusText.idle)![zh?0:1]}}</h2></div><span class="ft-badge">{{(transportNames[transport]||transportNames['lan-direct'])![zh?0:1]}}</span></div>
  <p class="ft-muted">{{transport==='temporary-share'?(zh?'上传完成后分享链接，对方可稍后领取。文件暂存在本站服务器，上传和领取都受权限与额度约束。':'Share the link after upload. The recipient can collect later. Files are temporarily stored on this server; upload and retrieval both require access and allowance.'):transport==='server-relay'?(zh?'适合直连失败或 UDP 不可用的网络。双方保持在线，文件经本站服务器转发，受速度和出口额度限制。':'Useful when direct connections fail or UDP is unavailable. Both people stay online; this server forwards files under rate and exit limits.'):(zh?'同一网络优先选局域网；远程直连需要核验公网范围。文件直接传给对方，服务只交换配对信息。':'Prefer LAN on the same network. Internet direct requires verified public ranges. Files go directly to the other device; the service exchanges pairing information.')}}</p>
  <p v-if="!supported" class="ft-notice">{{zh?(!secure?'请通过 HTTPS 页面使用网络传输。本机文件整理仍可使用。':'当前浏览器不支持 WebRTC 直连，可以检查是否允许使用中继或临时分享。'):(!secure?'Use HTTPS for network transfers. Local file preparation remains available.':'This browser cannot use WebRTC direct transfer. Check whether relay or temporary sharing is allowed.')}}</p>
  <p v-if="['server-relay','temporary-share'].includes(transport)" class="ft-muted">{{zh?'文件清单上限 256 KiB；文件较多或名称较长时请分批发送。服务器可以接触文件内容，临时分享会保存文件。':'The file list is limited to 256 KiB. Split tasks with many files or long names. The server can access contents; temporary sharing stores files.'}}</p>
  <p v-if="(active || recoverable) && state.role!==mode" class="ft-notice">{{zh?'已有进行中的任务。切换视图不会中断连接；取消后可发起另一项任务。':'A task is already active. Switching views keeps it connected. Cancel it before starting another.'}}</p>
  <label v-if="!active && !recoverable" class="ft-field ft-transport-select">{{zh?'传输方式':'Connection'}}<select id="ft-transport" v-model="transport"><option v-for="(name,id) in transportNames" :key="id" :value="id">{{name[zh?0:1]}}</option></select><small>{{zh?'默认优先局域网；无法连接时，可由发送方重新选择已开放的方式，并把新链接发给接收方。不会暗中切换到计费链路。':'LAN is the default. If it fails, the sender can choose an enabled option and share the new link. Metered fallback requires your choice.'}}</small></label>
  <label v-if="!active && !recoverable && transport!=='temporary-share'" class="ft-field ft-task-rate">{{zh?'本次限速 · Kbit/s（可选）':'This task · Kbit/s (optional)'}}<input v-model="requestedRate" type="number" min="1" max="1000000000" step="1" :aria-invalid="!rateValid" :placeholder="zh?'留空按账号规则':'Empty: use account rule'"><small>{{zh?'可以主动调低；双方配置与本次设置取较低速率。':'Choose a slower speed. The lowest of both policies and task choices applies.'}}</small><span v-if="!rateValid" class="ft-field-error">{{zh?'请输入 1 至 1000000000 的整数，或留空。':'Enter an integer from 1 to 1000000000, or leave empty.'}}</span></label>
  <div v-if="!active && !recoverable" class="ft-actions">
   <button v-if="mode==='send'" class="ft-button" :disabled="!supported || !allowed || !rateValid || !!files.busy.value || !files.collection.value.manifest.entries.length" @click="peer.create(files.collection.value,files.note.value,taskRate,transport)">{{transport==='temporary-share'?(zh?'上传并创建分享':'Upload and create share'):(zh?'生成接收码':'Create receive code')}}</button>
   <template v-else><label class="ft-field ft-code-input">{{zh?'接收码或分享链接':'Receive code or shared link'}}<input id="ft-receive-code" v-model="code" maxlength="2048" autocomplete="off" spellcheck="false" :placeholder="zh?'输入对方的接收码':'Enter the sender’s code'"></label><button class="ft-button" :disabled="!supported || !allowed || !rateValid || !validCode" @click="peer.join(code,taskRate,transport)">{{transport==='temporary-share'?(zh?'查看分享':'View share'):(zh?'连接发送方':'Connect to sender')}}</button></template>
  </div>
  <div class="ft-recovery-options"><label><input id="ft-remember-recovery" v-model="rememberRecovery" type="checkbox">{{zh?'在本机保留恢复记录':'Keep recovery records on this device'}}</label><small>{{zh?'最多 10 项，仅保存恢复凭据和进度，不保存文件正文。刷新后需要重新选择原文件或保存位置；共用电脑可保持关闭。':'Up to 10 records, containing recovery credentials and progress, without file contents. After reload, reselect original files or destinations. Leave off on shared computers.'}}</small></div>
  <div v-if="recoverable" class="ft-recovery-status"><p>{{zh?'已确认保存：':'Confirmed saved: '}}{{size(state.recovery!.point.bytes)}} / {{size(state.recovery!.summary.totalBytes)}} · {{zh?'可恢复至：':'Recover until: '}}{{new Date(state.recovery!.expiresAt).toLocaleString()}}</p><p class="ft-muted">{{zh?'恢复同一任务不重复计入个人额度；重传流量仍计入 VPN 预算。ZIP 会重新生成，文件和文件夹从已提交的检查点续写。':'Resuming the same task does not charge personal allowance again; retransmitted traffic still uses the VPN budget. ZIP restarts; files and folders resume from committed checkpoints.'}}</p><p v-if="rememberRecovery && !state.recoverySaved" role="status">{{zh?'浏览器未能保存恢复记录；请保持此页面打开。':'The browser could not save recovery metadata. Keep this page open.'}}</p><div class="ft-actions"><button v-if="active" class="ft-button ft-secondary" @click="peer.pause">{{zh?'暂停任务':'Pause task'}}</button><button v-else-if="state.role===mode" class="ft-button" @click="resumeTask()">{{state.status==='retrying'?(zh?'立即重试':'Retry now'):(zh?'恢复同一任务':'Resume this task')}}</button><button v-if="state.status==='retrying'" class="ft-text-button" @click="peer.pause">{{zh?'停止自动重试':'Stop automatic retry'}}</button></div><p v-if="state.status==='retrying'" class="ft-muted">{{zh?'本次自动重试：':'Automatic retry: '}}{{state.retryCount}} / {{state.recovery!.automaticRetries}}</p></div>
  <details v-if="matchingHistory.length && !active" class="ft-recovery-history"><summary>{{zh?'本机可恢复的任务':'Recoverable tasks on this device'}} · {{matchingHistory.length}}</summary><ul><li v-for="row in matchingHistory" :key="row.task"><div>{{row.summary.files}} {{zh?'个文件':'files'}} · {{size(row.point.bytes)}} / {{size(row.summary.totalBytes)}}<small>{{new Date(row.expiresAt).toLocaleString()}}<template v-if="row.destinationName"> · {{row.destinationName}}</template></small></div><button class="ft-button ft-secondary" @click="resumeTask(row)">{{zh?'恢复':'Resume'}}</button><button class="ft-text-button" @click="peer.forgetRecovery(row.task,row.role!)">{{zh?'移除此机记录':'Forget locally'}}</button></li></ul></details>
  <p v-if="!allowed && !active && !recoverable" class="ft-muted">{{unavailableText}}</p>
  <div v-if="state.code && active" class="ft-pair-code"><img v-if="qr" :src="qr" width="144" height="144" :alt="zh?'接收链接二维码':'Receive link QR code'"><div><p class="ft-muted">{{zh?'10 分钟内配对 · 仅用于本次传输':'Pair within 10 minutes · One transfer'}}</p><strong class="ft-code">{{state.code.slice(0,5)}} {{state.code.slice(5)}}</strong><div class="ft-actions"><button class="ft-button ft-secondary" @click="copyLink">{{copied?(zh?'链接已复制':'Link copied'):(zh?'复制接收链接':'Copy receive link')}}</button></div><input class="ft-share-link" readonly :value="state.link" :aria-label="zh?'可手动复制的接收链接':'Receive link for manual copying'" @focus="($event.target as HTMLInputElement).select()"></div></div>
  <div v-if="state.status==='shared' && state.share" class="ft-confirm"><p>{{zh?'上传完成，可关闭此页面。知道链接的人可在权限和有效期内领取，请只分享给预期接收者。':'Upload complete. You can close this page. Anyone holding the link can retrieve within the access rules and lifetime; share it only with intended recipients.'}}</p><p>{{zh?'有效至：':'Available until: '}}{{new Date(state.share.expiresAt).toLocaleString()}} · {{zh?'最多领取：':'Retrieval limit: '}}{{state.share.maxDownloads}}</p><input class="ft-share-link" readonly :value="state.link" :aria-label="zh?'临时分享链接':'Temporary share link'" @focus="($event.target as HTMLInputElement).select()"><div class="ft-actions"><button class="ft-button" @click="copyLink">{{copied?(zh?'已复制':'Copied'):(zh?'复制分享链接':'Copy share link')}}</button><button class="ft-text-button" :disabled="revoking" @click="revokeShare">{{zh?'撤销此分享':'Revoke this share'}}</button></div><p v-if="revokeError" role="alert">{{zh?'撤销未完成，请检查登录状态和服务连接后重试。':'Revocation failed. Check sign-in and the service connection, then retry.'}}</p></div>
  <div v-if="state.status==='share-preview' && state.share" class="ft-confirm"><p>{{state.note}} · {{state.summary?.files}} {{zh?'个文件':'files'}} · {{size(state.summary?.totalBytes||'0')}}</p><p>{{zh?'有效至：':'Available until: '}}{{new Date(state.share.expiresAt).toLocaleString()}} · {{zh?'剩余领取次数：':'Retrievals remaining: '}}{{state.share.maxDownloads-state.share.downloads}}</p><p class="ft-muted">{{zh?'确认后占用一次领取次数并计入本次接收额度。中途取消或失败不退回，可先检查剩余额度再确认。':'Confirmation consumes one retrieval and charges your receiving allowance. Cancellation or failure does not refund it. Check your allowance before continuing.'}}</p><button class="ft-button" @click="peer.claimShare">{{zh?'确认领取':'Confirm retrieval'}}</button></div>
  <div v-if="state.status==='confirm' || state.status==='waiting-confirmation'" class="ft-confirm"><p>{{zh?'对方：':'Other person: '}}{{state.name || (zh?'匿名用户':'Guest')}}</p><p v-if="state.summary">{{state.note}} · {{state.summary.files}} {{zh?'个文件':'files'}} · {{state.summary.directories}} {{zh?'个目录':'folders'}} · {{size(state.summary.totalBytes)}}</p><p class="ft-muted">{{zh?'请核对对方身份。双方都确认后才建立文件连接。获准连接时按本项总大小计入双方额度；此后取消或中断不退回额度。':'Check the other person’s identity. Both people must confirm. Authorization charges the full task size to both allowances; later cancellation or interruption does not refund it.'}}</p><button v-if="state.status==='confirm'" class="ft-button" @click="peer.confirm">{{zh?'确认本次配对':'Confirm pairing'}}</button></div>
  <div v-if="state.manifest" class="ft-remote-list"><p>{{state.summary?.files}} {{zh?'个文件':'files'}} · {{size(state.summary?.totalBytes || '0')}}</p><ul class="ft-file-list"><li v-for="entry in state.manifest.entries.slice(0,visible)" :key="entry.relativePath"><span class="ft-file-kind" aria-hidden="true">{{entry.kind==='directory'?'▱':'▤'}}</span><div class="ft-file-name">{{entry.relativePath}}<small>{{entry.kind==='file'?size(entry.sizeBytes):(zh?'目录':'Folder')}}</small></div></li></ul><button v-if="visible<state.manifest.entries.length" ref="more" class="ft-text-button" @click="visible+=100">{{zh?'再显示 100 项':'Show 100 more'}}</button></div>
  <div v-if="state.status==='ready-save'" class="ft-export"><p v-if="state.recovery && (state.recovery.point.bytes!=='0' || state.recovery.point.fileIndex>0)" class="ft-notice">{{zh?'请重新选择原保存文件，或上次自动创建的 transfer- 子文件夹。内容核对通过后才会继续写入。':'Choose the original output file or the previously created transfer- subfolder. Writing continues only after its contents match.'}}<template v-if="state.destinationName"> {{state.destinationName}}</template></p><div class="ft-actions"><button v-if="single" class="ft-button" @click="peer.save('file')">{{zh?'接收并保存文件':'Receive and save file'}}</button><button class="ft-button" :disabled="!support.directoryWrite" @click="peer.save('directory')">{{zh?'接收为文件夹':'Receive as folder'}}</button><button class="ft-button ft-secondary" @click="peer.save('zip')">{{zh?'接收为 ZIP':'Receive as ZIP'}}</button></div><p class="ft-muted">{{support.streamSave?(zh?'边传边写入，逐块校验。保存目录会新建子文件夹，保留层级。':'Stream to disk with chunk verification. Folder output creates a new subfolder and preserves paths.'):(zh?'兼容下载最多 128 MiB（含 ZIP 开销）。超出请分批发送或使用支持流式保存的浏览器。':'Fallback downloads are limited to 128 MiB including ZIP overhead. Split larger transfers or use streaming save support.')}}</p></div>
  <div v-if="state.status==='transferring'" class="ft-file-progress" role="status"><div><p>{{size(state.progress.bytes)}} / {{size(state.progress.totalBytes)}} · {{state.progress.path}}</p><progress :value="percent" max="100" :aria-label="zh?'传输进度':'Transfer progress'"/><p class="ft-muted">{{zh?'当前速度：':'Current speed: '}}{{size(String(Math.max(0,Math.floor(state.speedBytes||0))))}}/s<template v-if="state.etaSeconds!=null"> · {{zh?'预计剩余：':'Estimated remaining: '}}{{state.etaSeconds}} s</template></p><p class="ft-muted">{{state.rateKbps===null?(zh?'当前任务未设置限速':'No configured rate limit'):state.rateKbps+' Kbit/s'}}</p></div></div>
  <p v-if="state.error" class="ft-notice" role="alert">{{errorText}}<template v-if="state.partialDirectory"> {{zh?'部分文件可能已保留在：':'Partial files may remain in: '}}{{state.partialDirectory}}</template></p>
  <p v-if="state.result" class="ft-notice">{{state.result.status==='saved'?(zh?'保存完成：':'Saved: '):(zh?'已交给浏览器下载，请检查下载列表：':'Download requested; check browser downloads: ')}}{{state.result.name}}</p>
  <button v-if="active || recoverable" class="ft-text-button ft-pair-cancel" @click="peer.cancel">{{state.status==='confirm'?(zh?'拒绝本次传输':'Decline transfer'):(zh?'取消并断开连接':'Cancel and disconnect')}}</button>
 </section>
</template>
