const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {JSDOM}=require(process.env.JSDOM_PATH||'jsdom');
const script=fs.readFileSync(path.join(__dirname,'../frontend/public/static/js/academic.js'),'utf8');
function render(t,url){const dom=new JSDOM(`<div><a data-public-language="zh" href="/zh/publications/paper">中文</a><a data-public-language="en" href="/en/publications/paper">EN</a><nav class="academic-nav"><a data-navigation-id="home" href="/zh">Home</a><a data-navigation-id="papers" href="/zh/publications">Papers</a><a data-navigation-id="filter" href="/zh/publications?f.year=2024">Year</a><a data-navigation-id="external" href="https://external.example/zh/publications">External</a></nav></div>`,{url,runScripts:'outside-only'});t.after(()=>dom.window.close());dom.window.eval(script);return dom.window.document;}
test('language preserves detail, repeated parameters and hash without rewriting external origins',t=>{const d=render(t,'https://site.example/zh/publications/paper?q=alpha&f.year=2025&x=1&x=2#citations');const u=new URL(d.querySelector('[data-public-language=en]').href);assert.equal(u.pathname,'/en/publications/paper');assert.equal(u.searchParams.get('q'),'alpha');assert.deepEqual(u.searchParams.getAll('x'),['1','2']);assert.equal(u.hash,'#citations');assert.equal(d.querySelector('[data-navigation-id=papers]').getAttribute('aria-current'),'page');assert.equal(d.querySelector('[data-navigation-id=home]').getAttribute('aria-current'),null);assert.equal(d.querySelector('[data-navigation-id=external]').getAttribute('aria-current'),null);assert.equal(d.querySelector('[data-navigation-id=filter]').getAttribute('aria-current'),null);});
test('filtered navigation matches only appropriate query state',t=>{const d=render(t,'https://site.example/zh/publications?f.year=2024');assert.equal(d.querySelector('[data-navigation-id=filter]').getAttribute('aria-current'),'page');});
test('nonlanguage auth paths retain safe server-rendered fallback',t=>{const d=render(t,'https://site.example/auth/register?token=not-copied');assert.equal(new URL(d.querySelector('[data-public-language=en]').href).pathname,'/en/publications/paper');assert.equal(new URL(d.querySelector('[data-public-language=en]').href).search,'');});
test('module prefix does not mark a different route active',t=>{const d=render(t,'https://site.example/zh/publications-archive');assert.equal(d.querySelector('[data-navigation-id=papers]').getAttribute('aria-current'),null);});
test('failed and already-broken branding images hide while site text remains',t=>{
 const dom=new JSDOM('<a class="academic-brand"><img data-brand-logo src="/media/broken" alt=""><span>Configured site</span></a>',{url:'https://site.example/zh',runScripts:'outside-only'});t.after(()=>dom.window.close());const logo=dom.window.document.querySelector('img');Object.defineProperty(logo,'complete',{value:false,configurable:true});dom.window.eval(script);assert.equal(logo.hidden,false);logo.dispatchEvent(new dom.window.Event('error'));assert.equal(logo.hidden,true);assert.equal(dom.window.document.querySelector('span').textContent,'Configured site');logo.hidden=false;Object.defineProperty(logo,'complete',{value:true});dom.window.eval(script);assert.equal(logo.hidden,true);
});
test('server-normalized detail language link keeps translated return context',t=>{
 const dom=new JSDOM('<a data-public-language="zh" data-language-resolved href="/zh/n/team/person?from=%2Fzh%2Fn%2Fteam%3Fs%3Dencoded">ZH</a>',{url:'https://site.example/en/n/team/person?from=%2Fen%2Fn%2Fteam%3Fs%3Dencoded#bio',runScripts:'outside-only'});t.after(()=>dom.window.close());dom.window.eval(script);
 const u=new URL(dom.window.document.querySelector('a').href);assert.equal(u.searchParams.get('from'),'/zh/n/team?s=encoded');assert.equal(u.hash,'#bio');
});
