const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {JSDOM}=require(process.env.JSDOM_PATH||'jsdom');
const script=fs.readFileSync(path.join(__dirname,'../frontend/public/static/js/public-people.js'),'utf8');
const card=id=>`<article data-person-card data-record-id="${id}"><input data-person-select type="checkbox"><p data-citation-text data-citation-format="citation_gbt">GB/T ${id}</p><button data-copy-citation type="button">Copy one</button><span data-citation-status></span></article>`;
function setup(t,n=2){const dom=new JSDOM(`<html lang="en"><body><form data-person-form><div data-person-selection><input data-person-all type="checkbox"><button data-person-copy type="button">Copy</button><button data-person-clear type="button">Clear</button><span data-person-count></span></div><a data-person-reset></a><select data-copy-format>${['gbt','elsevier','apa','ieee','bibtex'].map(x=>`<option>${x}</option>`).join('')}</select><span data-person-tool-status></span></form><section data-public-content data-public-stream data-table="publications" data-lang="en">${Array.from({length:n},(_,i)=>card('p'+i)).join('')}</section></body></html>`,{url:'https://site.example/en/publications',runScripts:'outside-only'});t.after(()=>dom.window.close());const w=dom.window,d=w.document,requests=[],copied=[];w.fetch=(url,options)=>new Promise((resolve,reject)=>requests.push({url,options,resolve,reject}));Object.defineProperty(w.navigator,'clipboard',{value:{writeText:async value=>copied.push(value)}});w.eval(script);const tick=()=>new Promise(r=>setTimeout(r,0));const choose=value=>{d.querySelector('select').value=value;d.querySelector('select').dispatchEvent(new w.Event('change'));};const all=d.querySelector('[data-person-all]');all.checked=true;all.dispatchEvent(new w.Event('change'));const reply=(index,alter=x=>x)=>{const q=new URL(requests[index].url,w.location.href).searchParams,format=q.get('format');requests[index].resolve({ok:true,headers:{get:()=> 'application/json'},json:async()=>alter({format,rows:q.getAll('uid').reverse().map(uid=>({uid,text:format+' '+uid}))})});};return {w,d,requests,copied,tick,choose,reply,copy:()=>d.querySelector('[data-person-copy]').click()};}
test('100 papers use five serial batches of twenty and retain chosen format and order',async t=>{const f=setup(t,100);f.choose('bibtex');f.copy();assert.equal(f.requests.length,1);for(let i=0;i<5;i++){assert.equal(new URL(f.requests[i].url,f.w.location.href).searchParams.getAll('uid').length,20);f.reply(i);await f.tick();assert.equal(f.requests.length,Math.min(i+2,5));}assert.equal(f.copied[0],Array.from({length:100},(_,i)=>'bibtex p'+i).join('\n\n'));assert.equal(f.d.querySelector('[data-citation-text]').textContent,'GB/T p0');assert(f.d.querySelector('[data-person-all]').checked);});
for(const style of ['elsevier','apa','ieee','bibtex'])test('single entry follows selected '+style,async t=>{const f=setup(t);f.choose(style);f.d.querySelector('[data-copy-citation]').click();assert.equal(f.requests.length,1);f.reply(0);await f.tick();assert.equal(f.copied[0],style+' p0');});
test('one missing citation prevents the entire batch from copying',async t=>{const f=setup(t);f.choose('apa');f.copy();f.reply(0,x=>({...x,rows:[x.rows[0]]}));await f.tick();assert.equal(f.copied.length,0);assert.match(f.d.querySelector('[data-person-tool-status]').textContent,/1 citations are missing/);assert(f.d.querySelector('[data-person-all]').checked);});
test('format changes cancel late results without clearing selection',async t=>{const f=setup(t);f.choose('apa');f.copy();f.choose('ieee');assert(f.requests[0].options.signal.aborted);f.reply(0);await f.tick();assert.equal(f.copied.length,0);assert(f.d.querySelector('[data-person-all]').checked);f.copy();f.reply(1);await f.tick();assert.equal(f.copied[0],'ieee p0\n\nieee p1');});
test('filter reset cancels a pending read and ignores its response',async t=>{const f=setup(t);f.choose('apa');f.copy();f.d.querySelector('section').dispatchEvent(new f.w.CustomEvent('public:querychange',{bubbles:true}));assert(f.requests[0].options.signal.aborted);f.reply(0);await f.tick();assert.equal(f.copied.length,0);});
test('failed read retains selection, retries without cache and rejects wrong response',async t=>{const f=setup(t);f.choose('apa');f.copy();f.requests[0].reject(new Error('offline'));await f.tick();assert.equal(f.copied.length,0);f.copy();f.reply(1,x=>({...x,format:'ieee'}));await f.tick();assert.equal(f.copied.length,0);f.copy();f.reply(2);await f.tick();assert.equal(f.copied.length,1);});
test('denied clipboard exposes correct alternate text for manual copy',async t=>{const f=setup(t);f.w.navigator.clipboard.writeText=async()=>{throw new Error('denied')};f.w.document.execCommand=()=>false;f.choose('apa');f.copy();f.reply(0);await f.tick();const field=f.d.querySelector('.citation-manual');assert(field&&field.readOnly);assert.equal(field.value,'apa p0\n\napa p1');f.choose('ieee');assert.equal(f.d.querySelector('.citation-manual'),null);});
