/* Design fixture interactions in jsdom, not a layout/browser acceptance. */
const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {JSDOM}=require(process.env.JSDOM_PATH||'jsdom');
const root=path.join(__dirname,'../frontend/public/static/design-preview');
function fixture(t,query=''){
 const dom=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8'),{url:'https://preview.example/index.html'+query,runScripts:'outside-only',pretendToBeVisual:true});
 t.after(()=>dom.window.close());
 const w=dom.window,doc=w.document,errors=[];
 w.addEventListener('error',e=>errors.push(e.error));
 w.fetch=()=>{throw Error('Preview must not make requests');};
 w.eval(fs.readFileSync(path.join(root,'preview.js'),'utf8'));
 t.after(()=>assert.deepEqual(errors,[]));
 const $=s=>doc.querySelector(s);
 const click=s=>$(s).click();
 const change=(s,v)=>{const el=$(s);el.value=v;el.dispatchEvent(new w.Event('change',{bubbles:true}));};
 const submit=q=>{$('#search').value=q;$('#filters').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));};
 return {w,doc,$,click,change,submit};
}
test('homepage shows one faculty hero and three compact content groups',t=>{const f=fixture(t);assert.match(f.$('.hero').textContent,/林知远/);assert.equal(f.doc.querySelectorAll('.home-section').length,3);assert.equal(f.doc.querySelectorAll('.hero h1').length,1);assert.ok(!f.$('.hero').textContent.includes('教育'));});
test('missing featured faculty uses site introduction',t=>{const f=fixture(t);f.change('#scenario','no-teacher');assert.match(f.$('.hero h1').textContent,/知识边界/);assert.equal(f.$('.profile-art'),null);});
test('account states protect admin entry in the sample and honor registration scenario',t=>{const f=fixture(t);assert.equal(f.$('[data-action="admin"]'),null);f.change('#scenario','member');assert.equal(f.$('[data-action="login"]'),null);assert.equal(f.$('[data-action="admin"]'),null);f.change('#scenario','admin');assert.ok(f.$('[data-action="admin"]'));f.click('[data-action="logout"]');f.click('[data-action="login"]');assert.match(f.$('#dialog-content').textContent,/未开放注册/);f.click('.dialog-close');f.change('#scenario','registration');f.click('[data-action="login"]');assert.ok(f.$('[data-action="demo-register"]'));});
test('navigation configuration sample removes entries instead of adding fixed fallbacks',t=>{const f=fixture(t);f.change('#scenario','minimal-nav');assert.equal(f.doc.querySelectorAll('header nav a').length,4);assert.equal(f.$('header nav [data-page="projects"]'),null);});
test('teachers numbered ascending, other modules descending',t=>{const f=fixture(t,'?view=teachers');assert.deepEqual([...f.doc.querySelectorAll('.card-index span')].map(e=>e.textContent),['1','2']);f.click('nav [data-page="papers"]');assert.deepEqual([...f.doc.querySelectorAll('.card-index span')].map(e=>e.textContent),['3','2','1']);});
test('expand updates only the current bio and keeps button focus',t=>{const f=fixture(t,'?view=teachers');const b=f.$('[data-expand="t1"]');b.focus();b.click();assert.equal(b.getAttribute('aria-expanded'),'true');assert.equal(f.$('#bio-t1').classList.contains('clamp'),false);assert.ok(f.$('#bio-t2').classList.contains('clamp'));assert.equal(f.doc.activeElement,b);b.click();assert.ok(f.$('#bio-t1').classList.contains('clamp'));});
test('search, category, sort and empty states use sample results consistently',t=>{const f=fixture(t,'?view=papers');f.change('#category','期刊论文');assert.equal(f.doc.querySelectorAll('.content-card').length,2);f.change('#sort','oldest');assert.equal(f.$('.content-card').dataset.id,'p3');f.submit('不存在');assert.ok(f.$('.empty'));assert.ok(f.$('#select-all').disabled);f.click('[data-action="reset"]');assert.equal(f.doc.querySelectorAll('.content-card').length,3);});
test('selection clears when filters change and mixed select-all is indeterminate',t=>{const f=fixture(t,'?view=papers');f.click('[data-select="p1"]');assert.ok(f.$('#select-all').indeterminate);assert.equal(f.$('[data-action="copy"]').disabled,false);f.change('#sort','oldest');assert.match(f.$('#selection-count').textContent,/0/);assert.ok(f.$('[data-action="copy"]').disabled);assert.match(f.$('#notice').textContent,/清空/);});
test('bilingual switch preserves query, selection and focused language control',t=>{const f=fixture(t,'?view=papers&q=林知远&sort=oldest');f.click('[data-select="p3"]');f.click('[data-lang="en"]');assert.equal(f.doc.documentElement.lang,'en');assert.equal(new URL(f.w.location.href).searchParams.get('q'),'林知远');assert.match(f.$('#selection-count').textContent,/1/);assert.equal(f.doc.activeElement.dataset.lang,'en');assert.ok(f.$('[data-select="p3"]').checked);});
test('copy uses ordered public fields, includes corresponding-author mark and excludes tags and actions',async t=>{const f=fixture(t,'?view=papers');let copied='';Object.defineProperty(f.w.navigator,'clipboard',{value:{writeText:async value=>{copied=value;}}});f.click('#select-all');assert.equal(copied,'');f.click('[data-action="copy"]');await Promise.resolve();assert.match(copied,/林知远\*/);assert.ok(copied.indexOf('开放环境')<copied.indexOf('知识引导'));assert.ok(!copied.includes('精选论文'));assert.ok(!copied.includes('查看详情'));});
test('clipboard denial provides manual copy with selected text',async t=>{const f=fixture(t,'?view=projects');Object.defineProperty(f.w.navigator,'clipboard',{value:{writeText:async()=>{throw Error('denied');}}});f.click('#select-all');f.click('[data-action="copy"]');await new Promise(r=>setTimeout(r,0));assert.match(f.$('#copy-fallback').value,/国家自然科学基金/);assert.match(f.$('#copy-fallback').value,/面上项目/);assert.equal(f.doc.activeElement.id,'copy-fallback');});
test('project cards emphasize source and program, without biography text',t=>{const f=fixture(t,'?view=projects');assert.equal(f.doc.querySelectorAll('.project-source').length,2);assert.equal(f.$('.card-bio'),null);});
test('news title and detail open in a new tab, direct detail URL renders correct item',t=>{const f=fixture(t,'?view=news');const a=f.$('.card-main h3 a');assert.equal(a.target,'_blank');assert.equal(a.rel,'noopener');assert.equal(f.$('.card-actions a').target,'_blank');const detail=fixture(t,new URL(a.href).search);assert.match(detail.$('#main h1').textContent,/跨学科/);detail.click('[data-lang="en"]');assert.match(detail.$('#main h1').textContent,/Interdisciplinary/);assert.equal(new URL(detail.w.location.href).searchParams.get('detail'),'n1');});
test('transfer panel toggling preserves DOM file input and link without any requests',t=>{const f=fixture(t,'?view=transfer');const file=new f.w.File(['sample'],'example.jpg',{type:'image/jpeg'});const input=f.$('#file-input');Object.defineProperty(input,'files',{value:[file]});input.dispatchEvent(new f.w.Event('change',{bubbles:true}));f.$('#share-link').value='https://transfer.example/s/demo';f.$('#share-link').dispatchEvent(new f.w.Event('input',{bubbles:true}));f.click('[data-transfer="receive"]');assert.ok(f.$('#send-panel').hidden);f.click('[data-transfer="send"]');assert.ok(f.$('#receive-panel').hidden);assert.equal(f.$('#file-input'),input);assert.equal(f.$('#share-link').value,'https://transfer.example/s/demo');assert.match(f.$('#file-result').textContent,/example.jpg · 1 KB/);f.click('[data-action="demo-send"]');assert.match(f.$('#notice').textContent,/第五步/);});
test('transfer files survive language rerender and display escaped filenames',t=>{const f=fixture(t,'?view=transfer');const file=new f.w.File(['x'],'<img src=x>.jpg');Object.defineProperty(f.$('#file-input'),'files',{value:[file]});f.$('#file-input').dispatchEvent(new f.w.Event('change',{bubbles:true}));f.click('[data-lang="en"]');assert.match(f.$('#file-result').textContent,/<img src=x>.jpg/);assert.equal(f.$('#file-result img'),null);});
test('untrusted query is escaped and invalid module/sort safely default',t=>{const f=fixture(t,'?view=papers&q=%22%3E%3Cimg%20src=x%20onerror=alert(1)%3E&sort=invalid');assert.equal(f.$('#search').value,'"><img src=x onerror=alert(1)>');assert.equal(f.$('#main img'),null);assert.equal(f.$('#sort').value,'default');const bad=fixture(t,'?view=__proto__');assert.ok(bad.$('.hero'));});
test('viewport button changes preview container without losing list state',t=>{const f=fixture(t,'?view=students');f.click('[data-select="s1"]');f.click('#viewport');assert.ok(f.$('.preview-frame').classList.contains('is-narrow'));assert.equal(f.$('#viewport').getAttribute('aria-pressed'),'true');assert.ok(f.$('[data-select="s1"]').checked);});
