const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {JSDOM}=require(process.env.JSDOM_PATH||'jsdom');
const script=fs.readFileSync(path.join(__dirname,'../frontend/public/static/js/public-people.js'),'utf8');
const card=(id,name)=>`<article data-person-card><span>99</span><input data-person-select type="checkbox"><div data-project-text><span>Fund ${id}</span><span> · </span><h2>${name}</h2><span> · </span><span>Amount: CNY 125,000</span></div></article>`;
const form='<form data-person-form><div data-person-selection hidden><input data-person-all type="checkbox"><button data-person-copy type="button">Copy</button><button data-person-clear type="button">Clear</button><span data-person-count></span></div><a data-person-reset></a><span data-person-tool-status></span></form>';
function setup(t,withForm=false){const dom=new JSDOM(`<html lang="en"><body>${withForm?form:''}<section data-public-stream data-public-content data-table="projects" data-lang="en">${card('A','Alpha &lt;b&gt;')}${card('B','Beta')}</section><p id="other">Other text</p></body></html>`,{url:'https://site.example/en/projects',runScripts:'outside-only'});t.after(()=>dom.window.close());const w=dom.window,copied=[];Object.defineProperty(w.navigator,'clipboard',{value:{writeText:async x=>copied.push(x)}});w.eval(script);return {w,d:w.document,copied};}
function select(f,start,so,end,eo){const r=f.d.createRange();r.setStart(start,so);r.setEnd(end,eo);const s=f.w.getSelection();s.removeAllRanges();s.addRange(r);const e=new f.w.Event('copy',{bubbles:true,cancelable:true}),data={};Object.defineProperty(e,'clipboardData',{value:{setData:(k,v)=>data[k]=v}});f.d.dispatchEvent(e);return {e,data};}
test('native project copy emits one paragraph per card, escaped HTML and no ordinal',t=>{const f=setup(t),blocks=f.d.querySelectorAll('[data-project-text]');const {e,data}=select(f,blocks[0],0,blocks[1],blocks[1].childNodes.length);assert(e.defaultPrevented);assert.equal(data['text/plain'],'Fund A · Alpha <b> · Amount: CNY 125,000\n\nFund B · Beta · Amount: CNY 125,000');assert.match(data['text/html'],/Alpha &lt;b&gt;/);assert.doesNotMatch(data['text/plain'],/99/);});
test('partial selection copies only the selected substring, not full fields',t=>{const f=setup(t),node=f.d.querySelector('h2').firstChild;const {data}=select(f,node,1,node,4);assert.equal(data['text/plain'],'lph');});
test('cross-card partial selection clips both ends in document order',t=>{const f=setup(t),nodes=f.d.querySelectorAll('h2');const {data}=select(f,nodes[0].firstChild,2,nodes[1].firstChild,2);assert.equal(data['text/plain'],'pha <b> · Amount: CNY 125,000\n\nFund B · Be');});
test('mixed page selection and non-project selection retain native copy',t=>{const f=setup(t),node=f.d.querySelector('h2').firstChild,other=f.d.querySelector('#other').firstChild;assert.equal(select(f,node,0,other,5).e.defaultPrevented,false);assert.equal(select(f,other,0,other,5).e.defaultPrevented,false);});
test('button copy matches native serialized cards and includes appended selections only',async t=>{const f=setup(t,true);const all=f.d.querySelector('[data-person-all]');all.checked=true;all.dispatchEvent(new f.w.Event('change'));const root=f.d.querySelector('section');root.insertAdjacentHTML('beforeend',card('C','Gamma'));root.dispatchEvent(new f.w.CustomEvent('public:appended'));f.d.querySelector('[data-person-copy]').click();await new Promise(r=>setTimeout(r,0));assert.equal(f.copied[0],'Fund A · Alpha <b> · Amount: CNY 125,000\n\nFund B · Beta · Amount: CNY 125,000');assert.equal(root.lastElementChild.querySelector('input').checked,false);});
test('right-column status copies once after main text with no private fields or extra field newlines',async t=>{
 const f=setup(t,true),blocks=f.d.querySelectorAll('[data-project-text]');
 blocks[0].innerHTML='<div class="project-main"><span>Public fund</span> · <h2>Public title</h2> · <span>Project no.: 73</span></div> <span class="project-status">Status: Active</span>';
 const expected='Public fund · Public title · Project no.: 73 Status: Active';
 const {data}=select(f,blocks[0],0,blocks[0],blocks[0].childNodes.length);
 assert.equal(data['text/plain'],expected);assert.doesNotMatch(data['text/plain'],/Amount|Principal|Members|\n/);
 const input=f.d.querySelector('[data-person-select]');input.checked=true;input.dispatchEvent(new f.w.Event('change',{bubbles:true}));
 f.d.querySelector('[data-person-copy]').click();await new Promise(resolve=>setTimeout(resolve,0));assert.equal(f.copied[0],expected);
 const status=blocks[0].querySelector('.project-status').firstChild;assert.equal(select(f,status,8,status,14).data['text/plain'],'Active');
});
