// Local-only acceptance: starts isolated Node and Cloudflare runtimes, then removes test data.
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,rm,writeFile,readFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {tmpdir} from 'node:os';
import {randomBytes} from 'node:crypto';
import WebSocket from 'ws';
import {DirectPeer} from '../web/files/peer.mjs';
import {collectFiles} from '../web/files/collection.mjs';
const root=fileURLToPath(new URL('../',import.meta.url)),temp=await mkdtemp(resolve(tmpdir(),'ft-runtime-')),token=randomBytes(32).toString('hex');
const wait=ms=>new Promise(r=>setTimeout(r,ms));async function until(fn,describe=()=>'',ms=25000){const end=Date.now()+ms;while(!fn()){if(Date.now()>end)throw new Error('Timeout: '+describe());await wait(30)}}
function disk(){const files=new Map(),dirs=new Set(['']),writers=new Set();function file(path){return{name:path.split('/').at(-1),async getFile(){return new File([files.get(path)||new Uint8Array()],path.split('/').at(-1))},async createWritable({keepExistingData=false}={}){if(writers.has(path))throw Error('writer still locked');writers.add(path);let bytes=keepExistingData?(files.get(path)||new Uint8Array()).slice():new Uint8Array(),position=0,ended=false;const done=()=>{assert.equal(ended,false);ended=true;writers.delete(path)};return{async seek(n){position=n},async truncate(n){const next=new Uint8Array(n);next.set(bytes.subarray(0,n));bytes=next},async write(value){const length=position+value.length;if(length>bytes.length){const next=new Uint8Array(length);next.set(bytes);bytes=next}bytes.set(value,position);position=length},async close(){done();files.set(path,bytes.slice())},async abort(){if(!ended)done()}}}}}
function directory(path=''){return{name:path.split('/').at(-1)||'selected',async getDirectoryHandle(name,{create=false}={}){const next=path+'/'+name;if(!dirs.has(next)){if(!create)throw Object.assign(Error(),{name:'NotFoundError'});dirs.add(next)}return directory(next)},async getFileHandle(name,{create=false}={}){const next=path+'/'+name;if(!files.has(next)){if(!create)throw Object.assign(Error(),{name:'NotFoundError'});files.set(next,new Uint8Array())}return file(next)}}}return{files,dirs,writers,file,directory};}

async function exercise(base){let cookie='',csrf='';
 async function request(path,{method='GET',body,auth=true,origin=base,csrfOverride}={}){const response=await fetch(base+path,{method,headers:{...(auth?{cookie,'x-csrf-token':csrfOverride??csrf}:{}),...(body?{'content-type':'application/json'}:{}),origin},...(body?{body:JSON.stringify(body)}:{})});const set=response.headers.get('set-cookie');if(set&&auth)cookie=set.split(';')[0];return{status:response.status,body:await response.json()}}
 const api='/transfer-api/v1';assert.equal((await request(api+'/auth/status')).body.setupRequired,true);
 assert.equal((await request(api+'/auth/setup',{method:'POST',body:{name:'admin',password:'123456',token},origin:'https://invalid.example'})).status,403);
 assert.equal((await request(api+'/auth/setup',{method:'POST',body:{name:'admin',password:'123456',token}})).status,200);
 assert.equal((await request(api+'/auth/setup',{method:'POST',body:{name:'other',password:'123456',token}})).status,409);
 let result=await request(api+'/auth/login',{method:'POST',body:{name:'admin',password:'123456'}});assert.equal(result.status,200,JSON.stringify(result));csrf=result.body.csrfToken;
 assert.equal((await request(api+'/admin/settings',{method:'PUT',body:{},csrfOverride:'wrong'})).status,403);
 result=await request(api+'/admin/settings');assert.equal(result.status,200,JSON.stringify(result));const snap=result.body;
 Object.assign(snap.settings,{enabled:true,relayEnabled:true,shareEnabled:true,serverVpnPath:'confirmed-outside-vpn',serverOutsideVerified:true,wanRateKbps:null});snap.settings.rules[1].links=['server-relay','temporary-share'];
 assert.equal((await request(api+'/admin/settings',{method:'PUT',body:{revision:snap.revision,settings:snap.settings,managers:snap.managers}})).status,200);
 assert.equal((await request(api+'/admin/accounts',{method:'PUT',body:{action:'create',name:'member',password:'abcdef',role:'member'}})).status,200);
 const peers=[],sockets=[];function peer(){const saved=disk(),scope={isSecureContext:true,crypto,location:{href:base+'/zh/transfer'},WebSocket:class{constructor(){const ws=new WebSocket(base.replace('http','ws')+api+'/signal',{origin:base});sockets.push(ws);return ws}},showSaveFilePicker:async()=>saved.file('/received.bin')};const p=new DirectPeer({scope,ticket:async(role,transport)=>{const r=await request(api+'/pairing-ticket',{method:'PUT',body:{role,transport}});assert.equal(r.status,200,JSON.stringify(r));return r.body}});peers.push(p);return{p,saved}}
 try{
 const a=peer(),b=peer(),bytes=randomBytes(190001);await a.p.create(collectFiles([new File([bytes],'资料.txt')]),'test',null,'server-relay');await until(()=>['waiting-peer','error'].includes(a.p.state.status),()=>JSON.stringify(a.p.state));assert.equal(a.p.state.status,'waiting-peer',JSON.stringify(a.p.state));await b.p.join(a.p.state.link);await until(()=>a.p.state.status==='confirm'&&b.p.state.status==='confirm',()=>JSON.stringify([a.p.state,b.p.state]));a.p.confirm();b.p.confirm();await until(()=>['ready-save','error'].includes(b.p.state.status),()=>JSON.stringify(b.p.state));assert.equal(b.p.state.status,'ready-save',JSON.stringify(b.p.state));await b.p.save('file');await until(()=>b.p.state.status==='complete',()=>JSON.stringify(b.p.state));assert.deepEqual(Buffer.from(b.saved.files.get('/received.bin')),bytes);
 const uploader=peer(),receiver=peer(),large=randomBytes(4400001);const sourceCollection=collectFiles([new File([large],'大文件.bin')]);let pausedUpload=false;const uploadCheckpoint=uploader.p.checkpoint.bind(uploader.p);uploader.p.checkpoint=async point=>{await uploadCheckpoint(point);if(!pausedUpload&&point.fileIndex===0&&point.bytes!=='0'){pausedUpload=true;uploader.p.pause()}};await uploader.p.create(sourceCollection,'R2 chunk test',null,'temporary-share');await until(()=>['paused','shared','error'].includes(uploader.p.state.status),()=>JSON.stringify(uploader.p.state),60000);if(uploader.p.state.status==='paused'){uploader.p.checkpoint=uploadCheckpoint;await uploader.p.resume(sourceCollection)}await until(()=>['shared','error'].includes(uploader.p.state.status),()=>JSON.stringify(uploader.p.state),60000);assert.equal(uploader.p.state.status,'shared',JSON.stringify(uploader.p.state));await receiver.p.join(uploader.p.state.link);await until(()=>['share-preview','error'].includes(receiver.p.state.status),()=>JSON.stringify(receiver.p.state));assert.equal(receiver.p.state.status,'share-preview');receiver.p.claimShare();await until(()=>['ready-save','error'].includes(receiver.p.state.status),()=>JSON.stringify(receiver.p.state));assert.equal(receiver.p.state.status,'ready-save');let pausedDownload=false;const downloadCheckpoint=receiver.p.checkpoint.bind(receiver.p);receiver.p.checkpoint=async point=>{await downloadCheckpoint(point);if(!pausedDownload&&point.fileIndex===0&&point.bytes!=='0'){pausedDownload=true;receiver.p.pause()}};await receiver.p.save('file');if(receiver.p.state.status==='paused'){receiver.p.checkpoint=downloadCheckpoint;await receiver.p.resume()}await until(()=>['complete','error'].includes(receiver.p.state.status),()=>JSON.stringify(receiver.p.state),60000);assert.equal(receiver.p.state.status,'complete',JSON.stringify(receiver.p.state));assert.deepEqual(Buffer.from(receiver.saved.files.get('/received.bin')),large);
 const shares=(await request(api+'/admin/shares')).body;assert.equal(shares.items.length,1);assert.equal(shares.items[0].state,'ready');await request(api+'/admin/shares/action',{method:'PUT',body:{action:'revoke',id:shares.items[0].id}});const cleanup=await request(api+'/admin/shares/action',{method:'PUT',body:{action:'cleanup'}});assert.equal(cleanup.body.count,0,JSON.stringify(cleanup));
 const session=(await request(api+'/session')).body;if(session.capabilities.deployment==='cloudflare'){assert.ok(BigInt(session.policy.cloudBudget.daily.usedBytes)>0n);const value=(await request(api+'/admin/settings')).body;value.settings.cloudDailyBytes='0';const r=await request(api+'/admin/settings',{method:'PUT',body:{revision:value.revision,settings:value.settings,managers:value.managers}});assert.equal(r.status,200);assert.equal((await request(api+'/pairing-ticket',{method:'PUT',body:{role:'send',transport:'server-relay'}})).body.error.code,'FT_CLOUD_BUDGET');assert.equal((await request(api+'/session')).body.policy.links.find(l=>l.id==='server-relay').available,false)}
 assert.equal((await request(api+'/auth/logout',{method:'POST',body:{}})).status,200);assert.equal((await request(api+'/admin/settings')).status,403);
 result=await request(api+'/auth/login',{method:'POST',body:{name:'member',password:'abcdef'}});csrf=result.body.csrfToken;assert.equal(result.status,200);assert.equal((await request(api+'/admin/settings')).status,403);
 console.log('PASS',base,'initialization, CSRF, roles, relay, 4.4 MB share with upload/download resume, revoke, cleanup, logout, cloud quota');
 }finally{peers.forEach(p=>p.stop());sockets.forEach(s=>s.terminate())}
}
let children=[];const localDir='storage/test-'+randomBytes(6).toString('hex');
try{for(const mode of ['node','cloudflare']){const port=mode==='node'?18791:18790,base=`http://127.0.0.1:${port}`;let log='';const args=mode==='node'?['scripts/standalone.mjs']:['node_modules/wrangler/bin/wrangler.js','dev','--local','--ip','127.0.0.1','--port',String(port),'--persist-to',resolve(temp,'cloud-state'),'--var','FT_LOCAL_TEST:true','--var','FT_SETUP_TOKEN:'+token];const child=spawn(process.execPath,args,{cwd:root,env:{...process.env,FT_PORT:String(port),FT_DATA_DIR:localDir,FT_SETUP_TOKEN:token,WRANGLER_SEND_METRICS:'false'},stdio:['ignore','pipe','pipe']});children.push(child);child.stdout.on('data',b=>log+=b);child.stderr.on('data',b=>log+=b);let ready=false;for(let i=0;i<200;i++){if(child.exitCode!==null)throw Error(log);try{ready=(await fetch(base+'/transfer-api/ready')).ok;if(ready)break}catch{}await wait(100)}if(!ready)throw Error(log);console.log('Testing',mode);try{await exercise(base)}catch(e){console.error(log);throw e}child.kill('SIGTERM');await wait(500)}console.log('All standalone runtime checks passed.')}finally{for(const child of children)child.kill('SIGTERM');await wait(500);await rm(resolve(root,localDir),{recursive:true,force:true});await rm(temp,{recursive:true,force:true})}
