export const PAGE_SIZES: readonly number[];
export const MAX_BATCH: number;
export const MAX_EXPORT_ROWS: number;
export const MAX_BACKUP_BYTES: number;
export const MAX_UPLOAD_BYTES: number;
export const RESOURCE_CATALOG: Readonly<Record<string, any>>;
export function getResource(key: string): any;
export function assertPlainObject(value: unknown, code?: string): Record<string, any>;
export function normalizeUid(value: unknown): string;
export function normalizeObjectKey(value: unknown): string;
export function normalizePage(value: unknown): number;
export function normalizePageSize(value: unknown): number;
export function normalizeSearch(value: unknown): string;
export function normalizeDirection(value: unknown): 'asc'|'desc';
export function normalizeFieldValue(field: any, value: unknown, mode?: string): unknown;
export function normalizeRecordInput(resourceKey: string, body: unknown, mode?: string): { values: Record<string, unknown>; secretOperations: Record<string, any> };
export function validateNavigation(values: Record<string, unknown>): Record<string, unknown>;
export function detectMediaSignature(bytes: Uint8Array): { mime: string; extension: string } | null;
export function detectImageDimensions(bytes: Uint8Array, mime: string): { width: number; height: number; pixels: number } | null;
export function validateRichTextDocument(input: unknown): any;
export function renderRichTextDocument(input: unknown, mediaUrl?: (key: string) => string): string;
export function normalizeBatchRequest(resourceKey: string, input: unknown): any;
export function createBackupEnvelope(tables: Record<string, unknown[]>, options?: Record<string, unknown>): any;
export function parseBackupEnvelope(input: unknown): any;
export function redactSensitive(value: unknown): unknown;
export function buildTranslationProviderRequest(provider: string, config: Record<string, unknown>, texts: string[], sourceLang?: string, targetLang?: string): any;
