import assert from 'node:assert/strict'; import { createRequire } from 'node:module'; import test from 'node:test'; import { resolve } from 'node:path'
const output=process.env.STAGE26_CORE_OUTPUT;if(!output)throw new Error('STAGE26_CORE_OUTPUT is required');const require=createRequire(import.meta.url);const {AdminDashboardStore,ADMIN_RECENT_OPERATION_LIMIT}=require(resolve(output,'server/services/admin/dashboard-store.js'));const {emptyPermissionRecord}=require(resolve(output,'server/security/permissions.js'))
function principal(grants=[]){const permissions=emptyPermissionRecord();for(const module of grants)permissions[module]=Object.freeze({view:true,create:false,edit:false,delete:false,export:false});return{sessionUid:'session:test',userUid:'user:test',username:'tester',displayName:'Tester',email:null,roleUid:'role:test',roleName:'Tester',roleLevel:100,roleIsSystem:false,visibilityScopes:new Set(['public']),permissions,mustChangePassword:false}}
function adapter(results){const calls=[];return{calls,kind:'sqlite',metrics:{calls:0,statements:0},async execute(){throw new Error('execute must not be called')},async batch(commands){calls.push(commands);return results}}}
test('no optional permission means no database call',async()=>{const fake=adapter([]);const result=await new AdminDashboardStore(fake).read(principal());assert.equal(fake.calls.length,0);assert.deepEqual(result,{pendingMessages:null,recentOperations:null})})
test('permitted metrics share one bounded batch',async()=>{const fake=adapter([{rows:[{total:4}],changes:0,lastInsertRowid:null},{rows:[{uid:'log:1',actor_name:'Admin',action:'save',module:'news',target_uid:'news:1',summary:'保存动态',status:'success',created_at:'2026-09-01T12:00:00.000Z'}],changes:0,lastInsertRowid:null}]);const result=await new AdminDashboardStore(fake).read(principal(['messages','operation_logs']));assert.equal(fake.calls.length,1);assert.equal(fake.calls[0].length,2);assert.match(fake.calls[0][0].sql,/status = 'new'/);assert.match(fake.calls[0][1].sql,/LIMIT \?/);assert.deepEqual(fake.calls[0][1].params,[ADMIN_RECENT_OPERATION_LIMIT]);assert.equal(result.pendingMessages,4);assert.equal(result.recentOperations.length,1)})
test('unauthorized tables are omitted rather than queried then hidden',async()=>{const fake=adapter([{rows:[{total:2}],changes:0,lastInsertRowid:null}]);const result=await new AdminDashboardStore(fake).read(principal(['messages']));assert.equal(fake.calls[0].length,1);assert.match(fake.calls[0][0].sql,/FROM messages/);assert.equal(result.pendingMessages,2);assert.equal(result.recentOperations,null)})
test('optional blank log text becomes null and malformed output fails closed',async()=>{const blank=adapter([{rows:[{uid:'log:1',actor_name:' ',action:'save',module:'news',target_uid:'',summary:null,status:'success',created_at:'2026-09-01T12:00:00.000Z'}],changes:0,lastInsertRowid:null}]);const result=await new AdminDashboardStore(blank).read(principal(['operation_logs']));assert.equal(result.recentOperations[0].actorName,null);assert.equal(result.recentOperations[0].targetUid,null);const malformed=adapter([{rows:[{total:-1}],changes:0,lastInsertRowid:null}]);await assert.rejects(()=>new AdminDashboardStore(malformed).read(principal(['messages'])),/Invalid admin dashboard count/)})
test('batch result count and activity timestamp are validated',async()=>{await assert.rejects(()=>new AdminDashboardStore(adapter([])).read(principal(['messages'])),/batch result mismatch/);const bad=adapter([{rows:[{uid:'log:1',actor_name:null,action:'save',module:'news',target_uid:null,summary:null,status:null,created_at:'not-a-date'}],changes:0,lastInsertRowid:null}]);await assert.rejects(()=>new AdminDashboardStore(bad).read(principal(['operation_logs'])),/Invalid operation timestamp/)})
test('activity result cannot exceed its declared row budget',async()=>{
  const rows=Array.from({length:ADMIN_RECENT_OPERATION_LIMIT+1},(_,index)=>({uid:`log:${index}`,actor_name:'Admin',action:'save',module:'news',target_uid:null,summary:null,status:'success',created_at:'2026-09-01T12:00:00.000Z'}))
  await assert.rejects(()=>new AdminDashboardStore(adapter([{rows,changes:0,lastInsertRowid:null}])).read(principal(['operation_logs'])),/too many operations/)
})
