import {transferPath,upload} from './portal-core.js?v=0.15.158';
/** 分页仅读取，写操作显式触发；批量写入仅在前一批成功后继续。 */
import {mountTableHeaders} from '/assets/admin/js/native-table-headers.js?v=0.15.38';
const root=document.querySelector('[data-transfer-admin]')||document.querySelector('[data-csrf]'),csrf=root.dataset.csrf,panel=document.querySelector('#task-panel');
const taskMessage=document.querySelector('#task-feedback'),uploadMessage=document.querySelector('#upload-feedback');
let busy=false,reading=false,needsRefresh=false,readVersion=0,filterDirty=false,params=new URLSearchParams(location.search),cacheCursor=null,cacheItems=[],taskHeaders=null;
function bindTaskHeaders(){taskHeaders?.dispose();const area=panel.querySelector('[data-task-headers]');if(area)taskHeaders=mountTableHeaders(area,{query:()=>params,blocked:()=>busy,apply:next=>{params=next;readVersion++;refreshTasks()}})}
async function request(path,options={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),45000);let response;try{response=await fetch(transferPath(path),{...options,signal:controller.signal})}catch(error){throw Error(error.name==='AbortError'?'请求超时，结果尚未确认，请刷新核对后重试':'连接中断，请刷新核对结果后重试')}finally{clearTimeout(timer)}let value;try{value=await response.json()}catch{throw Error('服务响应异常，请刷新核对结果后重试')}if(!response.ok)throw Error(value.error||'操作失败');return value}
async function api(path,data){return request(path,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({_csrf:csrf,...data})})}
const selectedTasks=()=>[...panel.querySelectorAll('.task-select:checked')].map(box=>{const row=box.closest('tr');return {id:row.dataset.id,state:row.dataset.state,stamp:Number(row.dataset.stamp)}});
async function refreshTasks(automatic=false){if(reading){if(!automatic)needsRefresh=true;return}if(automatic&&(busy||filterDirty||selectedTasks().length||(panel.contains(document.activeElement)||taskHeaders?.isOpen)))return;const version=readVersion;reading=true;try{const value=await request('/api/tasks?'+params);if(version!==readVersion||busy||(automatic&&(filterDirty||selectedTasks().length||(panel.contains(document.activeElement)||taskHeaders?.isOpen))))return;taskHeaders?.dispose();panel.innerHTML=value.html;bindTaskHeaders();params.set('page',value.page);history.replaceState(null,'','?'+params+location.hash);filterDirty=false;if(!automatic)taskMessage.textContent='任务列表已刷新。'}catch(error){taskMessage.textContent=error.message}finally{reading=false;if(needsRefresh&&!busy){needsRefresh=false;refreshTasks()}}}
function currentQuery(){return {q:params.get('q')||'',state:params.get('state')||'all'}}
function setBusy(value){busy=value;readVersion++;document.querySelectorAll('#task-panel button,#task-panel input,#task-panel select,#refresh-tasks').forEach(el=>el.disabled=value)}
async function runBatch(data,label){if(busy)return;setBusy(true);let completed=0,skipped=0,error=null;try{let value;do{value=await api('/api/batch',data);completed+=value.completed;skipped+=value.skipped;taskMessage.textContent=`${label}：已完成${completed}项，跳过${skipped}项${value.cursor?'，正在继续下一批…':''}`;if(value.errors.length)throw Error(value.errors[0].error+'（任务 '+value.errors[0].id+'）');data={cursor:value.cursor}}while(value.cursor)}catch(exc){error=exc.message}finally{setBusy(false);await refreshTasks();taskMessage.textContent=`${label}：已完成${completed}项，跳过${skipped}项。`+(error?'已停止：'+error+'。请刷新核对后再次操作。':'');loadUsage()}}
panel.addEventListener('input',e=>{if(e.target.closest('#task-filter'))filterDirty=true});
panel.addEventListener('change',e=>{if(e.target.id==='select-page')panel.querySelectorAll('.task-select').forEach(box=>box.checked=e.target.checked);if(e.target.closest('#task-filter'))filterDirty=true});
panel.addEventListener('submit',e=>{e.preventDefault();if(busy)return;params=new URLSearchParams(new FormData(e.target));readVersion++;refreshTasks()});
panel.addEventListener('click',async e=>{const link=e.target.closest('a[data-page]');if(link){e.preventDefault();if(busy)return;params=new URLSearchParams(new URL(link.href).search);readVersion++;await refreshTasks();return}const button=e.target.closest('button[data-action]');if(button){const row=button.closest('tr'),action=button.dataset.action;if(['revoke','purge'].includes(action)&&!confirm(action==='purge'?'停止这个任务并删除其全部缓存文件？此操作无法恢复文件。':'撤销这个任务？分享链接将立即失效。'))return;if(action==='purge'){await runBatch({action,selected:[{id:row.dataset.id,state:row.dataset.state,stamp:Number(row.dataset.stamp)}]},'清理任务');return}if(busy)return;setBusy(true);let message;try{await api('/api/tasks/'+row.dataset.id+'/control',{action,state:row.dataset.state,stamp:Number(row.dataset.stamp)});message='任务操作已完成。'}catch(error){message=error.message}finally{setBusy(false);await refreshTasks();taskMessage.textContent=message;loadUsage()}return}if(e.target.id==='run-batch'){const scope=panel.querySelector('#batch-scope').value,action=panel.querySelector('#batch-action').value,selected=selectedTasks(),label=panel.querySelector('#batch-action').selectedOptions[0].textContent;if(scope==='all'&&filterDirty){taskMessage.textContent='筛选已修改，请先点击筛选，再操作全部匹配任务。';return}if(scope==='selected'&&!selected.length){taskMessage.textContent='请先选择任务。';return}const count=scope==='selected'?selected.length:e.target.dataset.total;if(!confirm(`${label}：${scope==='all'?'全部匹配范围':'所选'}共${count}条中的可操作任务？${action==='purge'?'文件删除后无法恢复。':''}`))return;await runBatch({action,...(scope==='selected'?{selected}:{query:currentQuery()})},label)}});
document.querySelector('#refresh-tasks').addEventListener('click',()=>refreshTasks());
setInterval(()=>{if(document.querySelector('#auto-refresh').checked&&!document.hidden)refreshTasks(true)},10000);
async function loadUsage(){if(!document.querySelector('#usage'))return;try{const value=await request('/api/usage');document.querySelector('#usage').textContent=['daily','weekly','monthly'].map((key,index)=>`${['今日','本周','本月'][index]}已用及预留 ${value[key].charged_and_reserved} 字节 / ${value[key].limit===null?'不限':value[key].limit+' 字节'}`).join('；')}catch{document.querySelector('#usage').textContent='启用传输并获得权限后显示本账号流量额度。'}}
import {mountSettings} from './settings.js?v=0.15.96';
mountSettings({api,request,loadUsage});
document.querySelector('#send')?.addEventListener('click',async e=>{
 const file=document.querySelector('#file').files[0];if(!file){uploadMessage.textContent='请先选择文件。';return}
 e.target.disabled=true;document.querySelector('#share').hidden=true;
 const key='transfer-portal:'+JSON.stringify([root.dataset.user,file.name,file.size,file.lastModified]);
 const save=value=>{try{sessionStorage.setItem(key,JSON.stringify(value))}catch{}};
 try{let saved;try{saved=JSON.parse(sessionStorage.getItem(key)||'null')}catch{}
 if(saved?.uncertain)throw Error('上次创建结果未知，请先核对任务列表；可前往快传首页确认后重新创建。');
 const result=await upload({file,current:saved?.current,csrf,maxBytes:Number(document.querySelector('#file').dataset.maxFile||209715200),
 call:async(path,options)=>{if(path==='/api/tasks'&&options?.method==='POST')save({uncertain:true});return request(path,options)},
 created:current=>save({current}),progress:offset=>{uploadMessage.textContent='已确认 '+Math.round(offset/file.size*100)+'%'}});
 const link=document.querySelector('#share');link.href=transferPath('/s/')+result.current.token;link.hidden=false;
 uploadMessage.textContent='发送完成。分享受有效期、权限和次数限制。';await refreshTasks();loadUsage();
 }catch(error){uploadMessage.textContent=error.message}finally{e.target.disabled=false}
});
const cacheMessage=document.querySelector('#cache-feedback'),cacheParams=new URLSearchParams(),cacheRoot=document.querySelector('[data-cache-headers]');
const cacheHeaders=cacheRoot?mountTableHeaders(cacheRoot,{query:()=>cacheParams,blocked:()=>document.querySelector('#cache-scan').disabled,apply:next=>{[...cacheParams.keys()].forEach(key=>cacheParams.delete(key));next.forEach((value,key)=>cacheParams.set(key,value));drawCache();cacheHeaders.paint()}}):null;
function drawCache(){const term=(cacheParams.get('q')||'').toLocaleLowerCase(),sort=cacheParams.get('sort'),direction=cacheParams.get('direction')==='desc'?-1:1;const visible=cacheItems.filter(item=>item.key.toLocaleLowerCase().includes(term));if(sort)visible.sort((a,b)=>direction*(sort==='size'?(Number(a.size??-1)-Number(b.size??-1)):a.key.localeCompare(b.key)));document.querySelector('#cache-rows').replaceChildren(...visible.map(item=>cacheRow(item,cacheItems.indexOf(item))));cacheMessage.textContent=`本批显示${visible.length}/${cacheItems.length}个文件${cacheCursor?'，可继续下一批':'，已到目录末尾'}。`;document.querySelector('#cache-selected').disabled=!visible.some(item=>item.token);}

function cacheRow(item,index){const row=document.createElement('tr');const select=document.createElement('td'),name=document.createElement('td'),size=document.createElement('td'),actions=document.createElement('td');name.textContent=item.key;size.textContent=item.size??'未知';if(item.token){const box=document.createElement('input');box.type='checkbox';box.dataset.index=index;box.className='cache-select';box.setAttribute('aria-label','选择'+item.key);select.append(box);const button=document.createElement('button');button.className='btn btn-outline-danger btn-sm';button.textContent=item.pending?'重试删除':'删除';button.addEventListener('click',()=>deleteCache([item]));actions.append(button)}else{actions.textContent=item.error||(item.protected?'属于任务 '+item.task+'，请从任务列表清理':'不可操作')}row.append(select,name,size,actions);return row}
async function scanCache(next=false){const button=document.querySelector('#cache-scan'),nextButton=document.querySelector('#cache-next');button.disabled=nextButton.disabled=true;try{const query=new URLSearchParams({area:document.querySelector('#cache-area').value});if(next&&cacheCursor)query.set('cursor',cacheCursor);const value=await request('/api/cache?'+query);cacheItems=value.objects;cacheCursor=value.cursor;drawCache();nextButton.hidden=!cacheCursor}catch(error){cacheMessage.textContent=error.message}finally{button.disabled=nextButton.disabled=false}}
async function deleteCache(items){if(!items.length){cacheMessage.textContent='请先选择文件。';return}if(!confirm(`删除这${items.length}个缓存文件？此操作无法恢复。`))return;document.querySelectorAll('#cache-rows button,#cache-selected,#cache-next,#cache-scan,#cache-area').forEach(x=>x.disabled=true);let done=0;try{for(const item of items){await api('/api/cache/delete',{token:item.token});done++;cacheMessage.textContent=`已删除${done}/${items.length}个文件…`}await scanCache();cacheMessage.textContent=`已删除${done}个文件，目录已从第一批重新扫描。`}catch(error){cacheMessage.textContent=`已删除${done}个；已停止：${error.message}。请重新扫描，或切换“删除待重试”。`}finally{document.querySelectorAll('#cache-rows button,#cache-selected,#cache-next,#cache-scan,#cache-area').forEach(x=>x.disabled=false)}}
document.querySelector('#cache-scan')?.addEventListener('click',()=>scanCache());document.querySelector('#cache-next')?.addEventListener('click',()=>scanCache(true));document.querySelector('#cache-area')?.addEventListener('change',()=>scanCache());document.querySelector('#cache-selected')?.addEventListener('click',()=>deleteCache([...document.querySelectorAll('.cache-select:checked')].map(x=>cacheItems[Number(x.dataset.index)])));
bindTaskHeaders();loadUsage();
