import {codeCard} from './portal-codes.js?v=0.15.96';
import {t as tr,joinText,errorText,setText,setAttr} from './transfer-i18n.js?v=0.15.96';
import {shareURL,bytes,request,upload,transferPath} from './portal-core.js?v=0.15.96';
const root=document.querySelector('[data-portal]'),$=id=>document.getElementById(id),user=root.dataset.user,csrf=root.dataset.csrf,maxBytes=Number(root.dataset.maxFile);
const shortCode=codeCard($('offline-code-host'));
let file=null,current=null,busy=false,pause=false,uncertainCreate=false,key='',storageOK=true;
const message=text=>{setText($('feedback'),text)};
setText($('limit'),Number.isSafeInteger(maxBytes)&&maxBytes>0?joinText(tr("单文件上限 "),bytes(maxBytes)):tr("暂时无法取得文件上限，请刷新后重试。"));
function readSaved(){try{return JSON.parse(sessionStorage.getItem(key)||'null')}catch{storageOK=false;return null}}
function save(value){try{sessionStorage.setItem(key,JSON.stringify(value))}catch{storageOK=false}}
function select(next){if(busy||!user||!next)return;if(current&&file&&next!==file&&!confirm(tr("切换文件会保留原任务与已预留额度，不会撤销原任务。继续？")))return;file=next;key='transfer-portal:'+JSON.stringify([user,file.name,file.size,file.lastModified]);const saved=readSaved();current=saved?.current||null;uncertainCreate=!!saved?.uncertain;setText($('file-info'),file.name+' · '+bytes(file.size));$('progress').value=0;$('result').hidden=true;shortCode.clear();$('send').disabled=uncertainCreate;$('new-task').hidden=!uncertainCreate;message(uncertainCreate?tr("上次创建结果未知。请先到原任务页面核对，避免重复占用额度。"):current?tr("已找到本标签页续传记录；点击继续后校验原文件。"):tr("文件已选择，点击开始发送。"))}
$('file').addEventListener('change',()=>select($('file').files[0]));
for(const type of ['dragover','dragleave','drop'])$('drop').addEventListener(type,event=>{event.preventDefault();$('drop').classList.toggle('dragging',type==='dragover');if(type==='drop'){if(event.dataTransfer.files.length!==1){message(tr("请一次选择一个文件。"));return}select(event.dataTransfer.files[0])}});
root.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>{const view=button.dataset.view;root.querySelectorAll('[data-view]').forEach(x=>setAttr(x,'aria-pressed',String(x===button)));root.querySelectorAll('[data-area]').forEach(x=>x.hidden=view!=='all'&&view!==x.dataset.area);root.querySelectorAll('[data-direction-panels]').forEach(x=>x.classList.toggle('single',view!=='all'))}));
async function usage(){if(!user)return;try{const value=await request('/api/usage');setText($('usage'),['daily','weekly','monthly'].map((key,i)=>tr("{0}可用：{1}",[[tr("今日"),tr("本周"),tr("本月")][i],value[key].remaining===null?tr("不限"):bytes(value[key].remaining)])).reduce((a,b)=>a?joinText(joinText(a,' · '),b):b,''))}catch(error){setText($('usage'),errorText(error.message))}}
$('send').addEventListener('click',async()=>{if(busy||!user||uncertainCreate)return;if(!file){message(tr("请先选择文件。"));return}if(!Number.isSafeInteger(maxBytes)||maxBytes<=0||file.size<1||file.size>maxBytes){message(tr("文件为空、超过上限，或上限配置尚未取得。"));return}busy=true;pause=false;$('send').disabled=$('file').disabled=true;$('pause').disabled=false;$('result').hidden=true;shortCode.clear();message(tr("正在校验并发送，请保留当前页面。"));try{const result=await upload({file,current,csrf,maxBytes,call:async(path,options)=>{if(path==='/api/tasks'&&options?.method==='POST'){uncertainCreate=true;save({uncertain:true})}return request(path,options)},created:value=>{current=value;uncertainCreate=false;save({current})},progress:(offset,size)=>{$('progress').value=offset/size*100;message(tr("已发送 {0} / {1}（{2}%）",[bytes(offset),bytes(size),Math.floor(offset/size*100)]))},stopped:()=>pause});current=result.current;if(result.complete){const link=shareURL(transferPath('/s/'+current.token),location.origin);$('share').value=link;$('result').hidden=false;shortCode.show({mode:'offline',target:current.id});message(joinText(tr("上传完成，可以分享链接。"),!storageOK?tr("浏览器未允许保存续传记录，请保留本页面。"):''));if(!$('recent').querySelector(`[data-task="${current.id}"]`)){const li=document.createElement('li');li.dataset.task=current.id;setText(li,file.name+' · '+bytes(file.size));$('recent').prepend(li);while($('recent').children.length>10)$('recent').lastElementChild.remove()}}else message(tr("已暂停。继续发送会核对已上传内容；任务仍占用预留额度。"))}catch(error){message(joinText(errorText(error.message),uncertainCreate?tr(" 创建结果尚未确认，请先到原任务页面核对。"):''))}finally{busy=false;$('send').disabled=uncertainCreate;$('new-task').hidden=!uncertainCreate;$('file').disabled=false;$('pause').disabled=true;usage()}});
$('pause').addEventListener('click',()=>{pause=true;$('pause').disabled=true;message(tr("将在当前请求完成后暂停，不会重复发送当前分块。"))});
$('copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('share').value);message(tr("分享链接已复制。"))}catch{$('share').focus();$('share').select();message(tr("请复制已选中的分享链接。"))}});
$('receive').addEventListener('submit',event=>{event.preventDefault();if(root.dataset.receiving==='true'){setText($('receive-feedback'),tr("请先暂停并取消当前逐块接收，再打开其他下载。"));return}try{const url=shareURL($('receive-link').value.trim(),location.origin);setText($('receive-feedback'),tr("已请求下载；是否成功请查看浏览器下载记录或服务器提示。"));location.assign(url)}catch(error){setText($('receive-feedback'),errorText(error.message))}});
window.addEventListener('beforeunload',event=>{if(busy){event.preventDefault();event.returnValue=''}});
usage();

$('new-task').addEventListener('click',()=>{if(busy||!uncertainCreate)return;if(!confirm(tr("请先在原任务页面核对创建结果。重新创建可能增加一个任务并再次预留额度；这不会删除或撤销原任务。确认已核对并创建新任务？")))return;current=null;uncertainCreate=false;save({});$('new-task').hidden=true;$('send').disabled=false;message(tr("已清除本地待确认标记。点击开始发送创建新任务。"))});
