import { randomBytes, randomUUID, createHash, timingSafeEqual, webcrypto } from 'node:crypto';
import { settingsError } from '../shared/settings.mjs';
const token=()=>randomBytes(32).toString('base64url');
const hash=s=>createHash('sha256').update(s).digest('hex');
const equal=(a,b)=>typeof a==='string'&&typeof b==='string'&&timingSafeEqual(Buffer.from(hash(a)),Buffer.from(hash(b)));
export function installAccounts(db){db.exec(`CREATE TABLE IF NOT EXISTS local_accounts(uid TEXT PRIMARY KEY,name TEXT UNIQUE NOT NULL,salt TEXT NOT NULL,password TEXT NOT NULL,role TEXT NOT NULL,disabled INTEGER NOT NULL DEFAULT 0) STRICT;
CREATE TABLE IF NOT EXISTS local_sessions(token TEXT PRIMARY KEY,uid TEXT NOT NULL,csrf TEXT NOT NULL,expires INTEGER NOT NULL) STRICT;
CREATE INDEX IF NOT EXISTS local_session_expiry ON local_sessions(expires);
CREATE TABLE IF NOT EXISTS local_attempts(key TEXT PRIMARY KEY,count INTEGER NOT NULL,until INTEGER NOT NULL) STRICT;`);}
async function derive(password,salt){const key=await webcrypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);return Buffer.from(await webcrypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:Buffer.from(salt,'hex'),iterations:100000},key,256)).toString('hex');}
export function createAccounts(db,storage,{setupToken='',secure=true,atomic=fn=>{db.exec('BEGIN IMMEDIATE');try{const r=fn();db.exec('COMMIT');return r}catch(e){db.exec('ROLLBACK');throw e}}}={}){
 const cookie=(name,value,age)=>`${name}=${value}; Path=/; HttpOnly; SameSite=Strict; Max-Age=${age}${secure?'; Secure':''}`;
 const cookies=req=>Object.fromEntries((req.headers.get('cookie')||'').split(';').map(x=>x.trim().split('=')));
 function limited(key){atomic(()=>{const now=Date.now();db.prepare('DELETE FROM local_attempts WHERE until<=?').run(now);const row=db.prepare('SELECT * FROM local_attempts WHERE key=?').get(key);if(row?.count>=10||!row&&db.prepare('SELECT COUNT(*) n FROM local_attempts').get().n>=5000)throw settingsError('FT_TOO_MANY_ATTEMPTS',429);db.prepare('INSERT INTO local_attempts VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1').run(key,now+900000)});}
 function state(req){const c=cookies(req),row=/^[A-Za-z0-9_-]{43}$/.test(c.ft_session||'')?db.prepare('SELECT a.*,s.csrf FROM local_sessions s JOIN local_accounts a ON a.uid=s.uid WHERE s.token=? AND s.expires>? AND a.disabled=0').get(hash(c.ft_session),Date.now()):null;
 const guest=/^guest:[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(c.ft_guest||'')?c.ft_guest:'guest:'+randomUUID();
 return {identity:row?{kind:'user',uid:row.uid,name:row.name,roleId:row.role,roleName:row.role,mustChangePassword:false,sessionVersion:1}:{kind:'anonymous',uid:guest,name:null,roleId:null,roleName:null,sessionVersion:null,mustChangePassword:false},csrf:row?.csrf||'',headers:row||guest===c.ft_guest?{}:{'set-cookie':cookie('ft_guest',guest,2592000)}};}
 async function create(input,initial=false){if(!input||typeof input.name!=='string'||!input.name.trim()||/[\u0000-\u001f]/.test(input.name)||input.name.trim().length>64||typeof input.password!=='string'||input.password.length<6||input.password.length>256||!['member','admin'].includes(input.role||'member'))throw settingsError('FT_VALIDATION',422);const salt=randomBytes(16).toString('hex'),password=await derive(input.password,salt),uid=randomUUID(),role=initial?'admin':input.role||'member';
 atomic(()=>{if(initial&&db.prepare('SELECT COUNT(*) n FROM local_accounts').get().n)throw settingsError('FT_SETUP_COMPLETE',409);if(db.prepare('SELECT uid FROM local_accounts WHERE name=?').get(input.name.trim()))throw settingsError('FT_ACCOUNT_EXISTS',409);db.prepare('INSERT INTO local_accounts VALUES(?,?,?,?,?,0)').run(uid,input.name.trim(),salt,password,role);if(role==='admin'){db.prepare("INSERT INTO admin_grants VALUES(?,?,?)").run(uid,new Date().toISOString(),'standalone-account');db.prepare('UPDATE tool_settings SET revision=revision+1 WHERE id=1').run()}});
 return{uid,name:input.name.trim(),role};}
 storage.isIdentityActive=identity=>identity.kind!=='user'||!!db.prepare('SELECT 1 FROM local_sessions s JOIN local_accounts a ON a.uid=s.uid WHERE a.uid=? AND a.disabled=0 AND s.expires>?').get(identity.uid,Date.now());
 return {state,create,needsSetup:()=>!db.prepare('SELECT COUNT(*) n FROM local_accounts').get().n,
 async handle(req,path,input,current){
 if(path.endsWith('/status'))return {body:{setupRequired:this.needsSetup(),authenticated:current.identity.kind==='user',csrfToken:current.csrf,user:current.identity.kind==='user'?current.identity:null}};
 if(path.endsWith('/setup')){limited('setup');if(!setupToken||!equal(input?.token,setupToken))throw settingsError('FT_AUTH_REQUIRED',401);return{body:await create(input,true)}};
 if(path.endsWith('/login')){limited('login:'+hash(req.headers.get('cf-connecting-ip')||req.headers.get('x-ft-client-ip')||'local'));limited('name:'+hash(String(input?.name).slice(0,64)));const row=db.prepare('SELECT * FROM local_accounts WHERE name=?').get(String(input?.name||'').trim());const value=await derive(String(input?.password||'').slice(0,256),row?.salt||'00'.repeat(16));if(!row||row.disabled||!equal(row.password,value))throw settingsError('FT_LOGIN_FAILED',401);const secret=token(),csrf=token();atomic(()=>{db.prepare('DELETE FROM local_sessions WHERE expires<=? OR uid=?').run(Date.now(),row.uid);db.prepare('INSERT INTO local_sessions VALUES(?,?,?,?)').run(hash(secret),row.uid,csrf,Date.now()+86400000)});return{body:{authenticated:true,csrfToken:csrf},headers:{'set-cookie':cookie('ft_session',secret,86400)}}}
 if(path.endsWith('/logout')){const secret=cookies(req).ft_session;if(secret)db.prepare('DELETE FROM local_sessions WHERE token=?').run(hash(secret));return{body:{authenticated:false},headers:{'set-cookie':cookie('ft_session','',0)}}}
 throw settingsError('FT_NOT_FOUND',404);
 },list:()=>db.prepare('SELECT uid,name,role,disabled FROM local_accounts ORDER BY name').all(),
 async update(input,actor){if(input.action==='create')return create(input);if(input.action!=='disable'||typeof input.uid!=='string'||typeof input.disabled!=='boolean'||input.uid===actor)throw settingsError('FT_VALIDATION',422);db.prepare('UPDATE local_accounts SET disabled=? WHERE uid=?').run(input.disabled?1:0,input.uid);db.prepare('DELETE FROM local_sessions WHERE uid=?').run(input.uid);return{updated:true};}
 };
}
