import {rtcAdapters} from './rtc-fixture.mjs';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import WebSocket from 'ws';
import {readFileSync,readdirSync,writeFileSync,symlinkSync,unlinkSync} from 'node:fs';
import {join} from 'node:path';
import {DirectPeer,readShareToken,transferHint} from '../web/files/peer.mjs';
import {collectFiles} from '../web/files/collection.mjs';
import {createPairing} from '../server/pairing.mjs';
import {openStorage} from '../server/storage.mjs';
import {fixture} from './helpers.mjs';
import {usagePeriods} from '../server/usage.mjs';
import {publicNetworks,safeWanDescription,validateWanRoute,transportReadiness,stunServers} from '../shared/network.mjs';
import {defaultSettings,publicPolicy} from '../shared/settings.mjs';
import {prepareTransfer} from '../web/files/direct.mjs';
const identity=id=>({kind:'user',uid:id,name:id,roleId:'staff',roleName:'Staff',sessionVersion:'s-'+id,mustChangePassword:false});
async function waitFor(fn,details=()=>'',timeout=7000){const end=Date.now()+timeout;while(!fn()){if(Date.now()>end)throw Error('flow timeout '+details());await new Promise(ok=>setTimeout(ok,10))}}
async function context(t,patch={}){
 const cleanups=[],{config,root}=fixture({after:fn=>cleanups.push(fn)}),store=openStorage(config);store.setManager('owner',true);const snap=store.readSettings();Object.assign(snap.settings,{enabled:true,lanVerified:true,lanNetworks:'192.168.1.0/24',relayEnabled:true,shareEnabled:true,serverVpnPath:'confirmed-outside-vpn',serverOutsideVerified:true,wanRateKbps:null,...patch});snap.settings.rules[1].links=['lan-direct','wan-direct','server-relay','temporary-share'];store.saveSettings({revision:snap.revision,settings:snap.settings,managers:snap.managers},'owner');
 function sample(daily='0',monthly='0'){const at=Date.now(),settings=store.readSettings().settings,periods=usagePeriods(at,settings.vpnTimeZone);store.vpn.observe({kind:'snapshot',sourceId:settings.vpnSourceId,observedAt:at,timeZone:settings.vpnTimeZone,billing:settings.vpnBilling,daily:{...periods.daily,usedBytes:daily},monthly:{...periods.monthly,usedBytes:monthly}},store.readSettings().revision,at)}
 if(patch.vpnMeterSource==='snapshot')sample();
 const pairing=createPairing(store),server=createServer();server.on('upgrade',pairing.upgrade);await new Promise(ok=>server.listen(0,'127.0.0.1',ok));const sockets=[],peers=[];
 function peer(id){const chunks=[],saved={closed:false,aborted:false};const scope={isSecureContext:true,crypto,location:{href:'https://teacher.example/zh/transfer'},WebSocket:class{constructor(){const ws=new WebSocket(`ws://127.0.0.1:${server.address().port}/transfer-api/v1/signal`);sockets.push(ws);return ws}},showSaveFilePicker:async()=>({name:'received.bin',createWritable:async()=>({write:async b=>chunks.push(b.slice()),close:async()=>{saved.closed=true},abort:async()=>{saved.aborted=true}})})};const p=new DirectPeer({scope,ticket:async(role,transport)=>pairing.issue(identity(id),{role,transport})});peers.push(p);return{p,chunks,saved,scope}}
 t.after(async()=>{peers.forEach(p=>p.stop());sockets.forEach(ws=>ws.terminate());await pairing.close();await new Promise(ok=>server.close(ok));store.close();cleanups.forEach(fn=>fn())});return{store,config,root,pairing,peer,sample};
}
async function pair(c,bytes){const a=c.peer('sender'),b=c.peer('receiver');await a.p.create(collectFiles([new File([bytes],'original.bin')]),'relay',null,'server-relay');await waitFor(()=>['waiting-peer','error'].includes(a.p.state.status));assert.equal(a.p.state.status,'waiting-peer',JSON.stringify(a.p.state));await b.p.join(a.p.state.link);await waitFor(()=>a.p.state.status==='confirm'&&b.p.state.status==='confirm',()=>JSON.stringify({a:a.p.state,b:b.p.state}));a.p.confirm();b.p.confirm();await waitFor(()=>['ready-save','error'].includes(b.p.state.status)||a.p.state.status==='error',()=>JSON.stringify({a:a.p.state,b:b.p.state}));assert.equal(b.p.state.status,'ready-save',JSON.stringify({a:a.p.state,b:b.p.state}));return{a,b}}
test('public CIDRs and STUN configuration reject private, reserved, broad, malformed or credential-bearing endpoints',()=>{assert.equal(publicNetworks('8.8.8.0/24\n1.1.1.1/32').length,2);for(const value of ['0.0.0.0/0','192.168.1.0/24','127.0.0.1/32','198.51.100.1/32','8.8.8.1/24','8.8.8.0/24/extra'])assert.throws(()=>publicNetworks(value));assert.deepEqual(stunServers('stun:stun.example.org:3478'),[{urls:'stun:stun.example.org:3478'}]);for(const value of ['https://x','turn:x','stun:a@b','stun:x:65536'])assert.throws(()=>stunServers(value))});
test('WAN descriptions retain only verified public UDP host/srflx candidates and reciprocal public routes',()=>{const networks=publicNetworks('8.8.8.0/24');const d={type:'offer',sdp:'v=0\r\nm=application 9 UDP/DTLS/SCTP webrtc-datachannel\r\na=fingerprint:sha-256 AB:CD\r\na=candidate:1 1 udp 1 192.168.1.2 5000 typ host\r\na=candidate:2 1 udp 1 8.8.8.2 6000 typ srflx raddr 192.168.1.2 rport 5000\r\na=candidate:3 1 udp 1 1.1.1.1 7000 typ relay\r\n'};const safe=safeWanDescription(d,networks);assert.ok(!safe.sdp.includes('candidate:1'));assert.ok(!safe.sdp.includes('candidate:3'));assert.ok(safe.sdp.includes('typ srflx'));const point={address:'8.8.8.2',port:6000,type:'srflx',protocol:'udp'};assert.ok(validateWanRoute({local:point,remote:{...point,address:'8.8.8.3'}},networks));assert.throws(()=>validateWanRoute({local:point,remote:{...point,address:'192.168.1.2'}},networks))});
test('server paths require verification or available VPN protection and direct paths remain separate',()=>{const s={...defaultSettings(),enabled:true,relayEnabled:true};assert.equal(transportReadiness(s,'server-relay'),'FT_VPN_PATH_UNKNOWN');s.serverVpnPath='confirmed-outside-vpn';assert.equal(transportReadiness(s,'server-relay'),'FT_SERVER_UNVERIFIED');s.serverOutsideVerified=true;assert.equal(transportReadiness(s,'server-relay'),null);s.serverVpnPath='confirmed-vpn';assert.equal(transportReadiness(s,'server-relay',{reason:'FT_VPN_DAILY'}),'FT_VPN_DAILY')});
test('two real WebSocket controllers relay and verify file bytes without a WebRTC implementation',async t=>{const c=await context(t),bytes=Uint8Array.from({length:160001},(_,i)=>i%251),{a,b}=await pair(c,bytes);assert.equal(a.p.connection,null);await b.p.save('file');await waitFor(()=>a.p.state.status==='complete'&&b.p.state.status==='complete',()=>JSON.stringify({a:a.p.state,b:b.p.state}));assert.deepEqual(Buffer.concat(b.chunks),Buffer.from(bytes));assert.equal(b.saved.closed,true);assert.equal(c.store.usage.snapshot(identity('sender'),c.store.readSettings().settings).personal.daily.usedBytes,'160001')});
test('metered relay preissues actual bounded traffic grants and refuses strict mode',async t=>{const c=await context(t,{serverVpnPath:'confirmed-vpn',vpnMeterSource:'snapshot',vpnScopeVerified:true,vpnProtectionMode:'estimate',vpnDailyBytes:'10000000',vpnMonthlyBytes:'20000000',vpnReserveBytes:'0'});const {a,b}=await pair(c,new Uint8Array(32001));assert.ok(BigInt(c.store.vpn.view().pendingBytes)>0n);await b.p.save('file');await waitFor(()=>b.p.state.status==='complete');const before=c.store.readSettings();before.settings.vpnProtectionMode='strict';c.store.saveSettings({revision:before.revision,settings:before.settings,managers:before.managers},'owner');assert.throws(()=>c.pairing.issue(identity('new'),{role:'send',transport:'server-relay'}),/FT_VPN_HARD_GATE_REQUIRED/)});
test('meter loss stops a relay before another file read and never silently chooses a different transport',async t=>{const c=await context(t,{serverVpnPath:'confirmed-vpn',vpnMeterSource:'snapshot',vpnScopeVerified:true,vpnProtectionMode:'estimate',vpnDailyBytes:'10000000',vpnMonthlyBytes:'20000000',vpnReserveBytes:'0'});const {a,b}=await pair(c,new Uint8Array(90001));c.store.vpn.fail();await b.p.save('file');await waitFor(()=>b.p.state.status==='error');assert.equal(b.p.state.transport,'server-relay');assert.equal(b.saved.closed,false);assert.equal(Buffer.concat(b.chunks).length,0)});
test('temporary share upload, offline sender, later file download and claim count are real storage operations',async t=>{const c=await context(t),a=c.peer('owner'),bytes=Uint8Array.from({length:95001},(_,i)=>i%251);await a.p.create(collectFiles([new File([bytes],'资料.bin')]),'later',null,'temporary-share');await waitFor(()=>['shared','error'].includes(a.p.state.status),()=>JSON.stringify(a.p.state));assert.equal(a.p.state.status,'shared',JSON.stringify(a.p.state));assert.equal(readShareToken(a.p.state.link).length,43);assert.equal(transferHint(a.p.state.link),'temporary-share');assert.deepEqual(readFileSync(join(c.config.dataPath,'temporary',a.p.state.share.id,'0')),Buffer.from(bytes));const link=a.p.state.link;a.p.stop();const b=c.peer('receiver');await b.p.join(link);await waitFor(()=>['share-preview','error'].includes(b.p.state.status));assert.equal(b.p.state.status,'share-preview',JSON.stringify(b.p.state));assert.equal(c.store.shares.list().items[0].downloads,0);b.p.claimShare();await waitFor(()=>['ready-save','error'].includes(b.p.state.status));assert.equal(b.p.state.status,'ready-save',JSON.stringify(b.p.state));await b.p.save('file');await waitFor(()=>['complete','error'].includes(b.p.state.status));assert.equal(b.p.state.status,'complete',JSON.stringify(b.p.state));assert.deepEqual(Buffer.concat(b.chunks),Buffer.from(bytes));assert.throws(()=>c.store.shares.info(readShareToken(link)),/FT_SHARE_UNAVAILABLE/)});
test('storage budget reservations prevent simultaneous uploads and revoke/expiry cleanup releases only removed files',async t=>{const c=await context(t,{temporaryStorageBytes:'300000'}),prepared=await prepareTransfer(collectFiles([new File(['content'],'one.txt')]));const a=c.store.shares.create(identity('one'),prepared.summary,'');assert.throws(()=>c.store.shares.create(identity('two'),prepared.summary,''),/FT_STORAGE_FULL/);assert.throws(()=>c.store.shares.revoke(a.id,identity('two')),/FT_FORBIDDEN/);c.store.shares.revoke(a.id,identity('one'));const result=await c.store.shares.cleanup();assert.equal(result.removed,1);assert.equal(c.store.shares.list().reservedBytes,'0');assert.equal(readdirSync(join(c.config.dataPath,'temporary')).length,0)});
test('interrupted upload and completed share survive recovery with correct cleanup and revoked access',async t=>{const c=await context(t),prepared=await prepareTransfer(collectFiles([new File(['keep'],'one.txt')]));const complete=c.store.shares.create(identity('one'),prepared.summary,'');await c.store.shares.store(complete.id,prepared.bundle,new AbortController().signal);const partial=c.store.shares.create(identity('one'),prepared.summary,'');writeFileSync(join(c.config.dataPath,'temporary',partial.id,'0'),'partial');await c.store.shares.recover();assert.equal(c.store.shares.list().count,1);assert.equal(c.store.shares.info(complete.token).id,complete.id);assert.throws(()=>c.store.shares.info(partial.token),/FT_SHARE_UNAVAILABLE/);c.store.shares.revoke(complete.id,identity('owner'),true);assert.throws(()=>c.store.shares.info(complete.token),/FT_SHARE_UNAVAILABLE/);assert.equal((await c.store.shares.cleanup()).removed,1)});

test('WAN controllers map selected private host stats to advertised verified srflx candidates before sending bytes',async t=>{const c=await context(t,{wanVerified:true,wanNetworks:'8.8.8.0/24',stunUrls:'stun:stun.example.org:3478'}),a=c.peer('sender'),b=c.peer('receiver'),RTC=rtcAdapters({wan:true,iceServers:[{urls:'stun:stun.example.org:3478'}]});a.scope.RTCPeerConnection=b.scope.RTCPeerConnection=RTC;const bytes=new Uint8Array([1,2,3,4]);await a.p.create(collectFiles([new File([bytes],'small.bin')]),'',null,'wan-direct');await waitFor(()=>a.p.state.status==='waiting-peer'||a.p.state.status==='error');assert.equal(a.p.state.status,'waiting-peer',JSON.stringify(a.p.state));await b.p.join(a.p.state.link);await waitFor(()=>a.p.state.status==='confirm'&&b.p.state.status==='confirm');a.p.confirm();b.p.confirm();await waitFor(()=>['ready-save','error'].includes(b.p.state.status)||a.p.state.status==='error');assert.equal(b.p.state.status,'ready-save',JSON.stringify({a:a.p.state,b:b.p.state}));await b.p.save('file');await waitFor(()=>b.p.state.status==='complete'||b.p.state.status==='error');assert.equal(b.p.state.status,'complete',JSON.stringify(b.p.state));assert.deepEqual(Buffer.concat(b.chunks),Buffer.from(bytes));assert.equal(b.p.state.transport,'wan-direct')});
test('share storage and receiver preserve nested directories, empty folders and empty files',async t=>{const c=await context(t),a=c.peer('sender');const f=new File(['nested'],'文件.txt');Object.defineProperty(f,'webkitRelativePath',{value:'资料/子目录/文件.txt'});const empty=new File([],'空文件.txt');Object.defineProperty(empty,'webkitRelativePath',{value:'资料/空文件.txt'});const bundle=collectFiles([f,empty],{directory:true});bundle.manifest.entries.push({relativePath:'资料/空目录',kind:'directory',sizeBytes:'0',modifiedAt:null});await a.p.create(bundle,'folders',null,'temporary-share');await waitFor(()=>['shared','error'].includes(a.p.state.status));assert.equal(a.p.state.status,'shared',JSON.stringify(a.p.state));const b=c.peer('receiver'),folders=new Set(['']),output=new Map();function directory(path=''){return{name:path.split('/').at(-1)||'root',async getDirectoryHandle(name,options={}){const key=path+'/'+name;if(!folders.has(key)&&!options.create)throw Object.assign(Error(),{name:'NotFoundError'});folders.add(key);return directory(key)},async getFileHandle(name,options={}){const key=path+'/'+name;if(!output.has(key)&&!options.create)throw Object.assign(Error(),{name:'NotFoundError'});output.set(key,[]);return{async createWritable(){return{async write(bytes){output.get(key).push(Buffer.from(bytes))},async close(){},async abort(){}}}}}}}b.scope.showDirectoryPicker=async()=>directory();await b.p.join(a.p.state.link);await waitFor(()=>b.p.state.status==='share-preview');b.p.claimShare();await waitFor(()=>['ready-save','error'].includes(b.p.state.status));assert.equal(b.p.state.status,'ready-save',JSON.stringify(b.p.state));await b.p.save('directory');await waitFor(()=>['complete','error'].includes(b.p.state.status));assert.equal(b.p.state.status,'complete',JSON.stringify(b.p.state));assert.ok([...folders].some(x=>x.endsWith('/资料/空目录')));assert.equal(Buffer.concat([...output].find(([key])=>key.endsWith('/子目录/文件.txt'))[1]).toString(),'nested');assert.equal(Buffer.concat([...output].find(([key])=>key.endsWith('/空文件.txt'))[1]).length,0)});
test('quota denial does not consume a share retrieval and revocation blocks its live download',async t=>{const c=await context(t),prepared=await prepareTransfer(collectFiles([new File(['value'],'one.txt')]));const share=c.store.shares.create(identity('sender'),prepared.summary,'');await c.store.shares.store(share.id,prepared.bundle,new AbortController().signal);const snap=c.store.readSettings();snap.settings.rules[1].dailyBytes='0';c.store.saveSettings({revision:snap.revision,settings:snap.settings,managers:snap.managers},'owner');const b=c.peer('receiver');await b.p.join(share.token,null,'temporary-share');await waitFor(()=>b.p.state.status==='share-preview'||b.p.state.status==='error');assert.equal(b.p.state.status,'share-preview');b.p.claimShare();await waitFor(()=>b.p.state.status==='error');assert.equal(c.store.shares.list().items[0].downloads,0);const s=c.store.readSettings();s.settings.rules[1].dailyBytes=null;c.store.saveSettings({revision:s.revision,settings:s.settings,managers:s.managers},'owner');await b.p.join(share.token,null,'temporary-share');await waitFor(()=>b.p.state.status==='share-preview');b.p.claimShare();await waitFor(()=>b.p.state.status==='ready-save'||b.p.state.status==='error');assert.equal(b.p.state.status,'ready-save',JSON.stringify(b.p.state));c.store.shares.revoke(share.id,identity('owner'),true);await b.p.save('file');await waitFor(()=>b.p.state.status==='error');assert.equal(b.saved.closed,false)});

test('expired shares deny new access immediately and cleanup releases only successfully deleted storage',async t=>{const c=await context(t),prepared=await prepareTransfer(collectFiles([new File(['expired'],'one.txt')])),share=c.store.shares.create(identity('sender'),prepared.summary,'');await c.store.shares.store(share.id,prepared.bundle,new AbortController().signal);assert.throws(()=>c.store.shares.info(share.token,share.expiresAt),/FT_SHARE_UNAVAILABLE/);assert.throws(()=>c.store.shares.check(share.id,share.expiresAt),/FT_SHARE_UNAVAILABLE/);assert.equal((await c.store.shares.cleanup(new Set([share.id]),share.expiresAt)).removed,0);assert.ok(BigInt(c.store.shares.list().reservedBytes)>0n);assert.equal((await c.store.shares.cleanup(new Set(),share.expiresAt)).removed,1);assert.equal(c.store.shares.list().reservedBytes,'0')});
test('private share readers refuse a substituted symlink and cleanup never deletes its external target',async t=>{const c=await context(t),prepared=await prepareTransfer(collectFiles([new File(['private'],'one.txt')])),share=c.store.shares.create(identity('sender'),prepared.summary,'');await c.store.shares.store(share.id,prepared.bundle,new AbortController().signal);const target=join(c.root,'external.txt'),path=join(c.config.dataPath,'temporary',share.id,'0');writeFileSync(target,'private');unlinkSync(path);symlinkSync(target,path);const source=c.store.shares.bundle(share.id).sources.get('one.txt');await assert.rejects(async()=>{for await(const bytes of source(new AbortController().signal))assert.fail('must not read external bytes')},/FT_SERVER_STORAGE/);c.store.shares.revoke(share.id,identity('sender'));assert.equal((await c.store.shares.cleanup()).removed,1);assert.equal(readFileSync(target,'utf8'),'private')});
