import { test } from 'node:test';
import assert from 'node:assert/strict';
import { generateKeyPairSync } from 'node:crypto';
import { createServer } from 'node:http';
import WebSocket from 'ws';
import { createPairing } from '../server/pairing.mjs';
import { createService } from '../server/service.mjs';
import { openStorage } from '../server/storage.mjs';
import { signBridgeToken, identityFromSession } from '../server/bridge-token.mjs';
import { defaultSettings } from '../shared/settings.mjs';
import { ROUTES } from '../shared/contracts.mjs';
import { fixture } from './helpers.mjs';

const sender={kind:'user',uid:'sender',name:'Sender',roleId:'staff',roleName:'Staff',sessionVersion:'session-s',mustChangePassword:false};
const receiver={...sender,uid:'receiver',name:'Receiver',sessionVersion:'session-r'};
const summary={files:1,directories:0,totalBytes:'12',maxFileBytes:'12',manifestHash:'a'.repeat(64)};
function settings(){return{...defaultSettings(),enabled:true,lanVerified:true,lanNetworks:'192.168.1.0/24'}}
function inbox(ws){const queue=[];const waiting=[];ws.on('message',data=>{const value=JSON.parse(data.toString());if(waiting.length)waiting.shift()(value);else queue.push(value)});return async()=>{if(queue.length)return queue.shift();let timer;try{return await new Promise((resolve,reject)=>{timer=setTimeout(()=>reject(Error('message timeout')),2000);waiting.push(resolve)})}finally{clearTimeout(timer)}}}
async function context(t){let current={revision:1,settings:settings()};let time=Date.now();const cleanups=[];const {config}=fixture({after:fn=>cleanups.push(fn)});const store=openStorage(config);const pairing=createPairing({readSettings:()=>current,usage:store.usage},{now:()=>time});const server=createServer();server.on('upgrade',pairing.upgrade);await new Promise(ok=>server.listen(0,'127.0.0.1',ok));const clients=[];
 t.after(async()=>{clients.forEach(ws=>ws.terminate());pairing.close();await new Promise(ok=>server.close(ok));store.close();cleanups.forEach(fn=>fn())});
 async function open(identity,role,ticket){const ws=new WebSocket(`ws://127.0.0.1:${server.address().port}${ROUTES.signal}`);clients.push(ws);const next=inbox(ws);await new Promise((ok,fail)=>{ws.once('open',ok);ws.once('error',fail)});const token=ticket||pairing.issue(identity,{role}).ticket;ws.send(JSON.stringify({type:'auth',ticket:token}));return{ws,next,send:value=>ws.send(JSON.stringify(value)),token}}
 return{pairing,open,usage:store.usage,now:()=>time,current:()=>current,advance:ms=>{time+=ms},change:()=>{current={...current,revision:current.revision+1}}};
}
async function room(t){const c=await context(t);const a=await c.open(sender,'send'),b=await c.open(receiver,'receive');assert.equal((await a.next()).type,'authenticated');assert.equal((await b.next()).type,'authenticated');a.send({type:'create',summary,note:'测试'});const created=await a.next();b.send({type:'join',code:created.code});assert.equal((await b.next()).type,'invitation');assert.equal((await a.next()).type,'request');return{...c,a,b,created}}
test('pairing requires a one-use ticket issued for the current verified identity',async t=>{const c=await context(t);const a=await c.open(sender,'send');assert.equal((await a.next()).type,'authenticated');const replay=await c.open(sender,'send',a.token);assert.equal((await replay.next()).code,'FT_AUTH_REQUIRED');assert.throws(()=>c.pairing.issue(identityFromSession(null),{role:'send'}),/FT_ACCESS_DENIED/);assert.throws(()=>c.pairing.issue(sender,{role:'send',admin:true}),/FT_PROTOCOL/)});
test('both people must confirm; a receiver cancellation closes the sender task',async t=>{const{a,b}=await room(t);a.send({type:'confirm'});assert.equal((await a.next()).type,'waiting-confirmation');b.send({type:'cancel'});assert.equal((await a.next()).reason,'FT_CANCELLED');assert.equal((await b.next()).reason,'FT_CANCELLED')});
test('descriptions before both confirmations are rejected and cannot establish a file channel',async t=>{const{a,b}=await room(t);a.send({type:'description',description:{type:'offer',sdp:'bad'}});assert.equal((await a.next()).code,'FT_CONFIRM_REQUIRED');assert.equal((await b.next()).reason,'FT_CONFIRM_REQUIRED')});
test('paired clients receive a grant only after reciprocal selected LAN routes pass and rates are combined',async t=>{const c=await room(t);c.current().settings.rules[1].lanRateKbps=1200;c.a.send({type:'confirm'});await c.a.next();c.b.send({type:'confirm'});assert.equal((await c.a.next()).type,'paired');assert.equal((await c.b.next()).type,'paired');const a={address:'192.168.1.2',port:5000,type:'host',protocol:'udp'},b={...a,address:'192.168.1.3',port:6000};c.a.send({type:'route',route:{local:a,remote:b}});c.b.send({type:'route',route:{local:b,remote:a}});assert.equal((await c.a.next()).rateKbps,1200);assert.equal((await c.b.next()).type,'authorized');c.b.send({type:'complete'});assert.equal((await c.a.next()).reason,'FT_COMPLETE')});
test('unknown and non-reciprocal selected routes are blocked before the transfer grant',async t=>{const{a,b}=await room(t);a.send({type:'confirm'});await a.next();b.send({type:'confirm'});await a.next();await b.next();a.send({type:'route',route:{local:{address:'hidden.local',port:1,type:'host',protocol:'udp'},remote:{address:'192.168.1.3',port:2,type:'host',protocol:'udp'}}});assert.equal((await a.next()).code,'FT_ROUTE_UNKNOWN');assert.equal((await b.next()).reason,'FT_ROUTE_UNKNOWN')});
test('settings revision changes revoke existing tickets and paired sessions instead of keeping old rules',async t=>{const c=await room(t);c.change();c.a.send({type:'confirm'});assert.equal((await c.a.next()).code,'FT_POLICY_CHANGED');assert.equal((await c.b.next()).reason,'FT_POLICY_CHANGED')});
test('ticket expiry and authorization lease expiry are enforced on the server',async t=>{const c=await context(t);const token=c.pairing.issue(sender,{role:'send'}).ticket;c.advance(30001);const a=await c.open(sender,'send',token);assert.equal((await a.next()).code,'FT_AUTH_REQUIRED');const b=await c.open(sender,'send');await b.next();c.advance(45001);b.send({type:'create',summary,note:''});assert.equal((await b.next()).code,'FT_AUTH_EXPIRED')});
test('pairing code expires after ten minutes even when account leases are renewed',async t=>{const c=await room(t);c.advance(600001);c.a.send({type:'renew',ticket:c.pairing.issue(sender,{role:'send'}).ticket});assert.equal((await c.a.next()).code,'FT_PAIRING_EXPIRED');assert.equal((await c.b.next()).reason,'FT_PAIRING_EXPIRED')});
test('per-task size and concurrency are checked before publishing a code',async t=>{const c=await context(t);c.current().settings.rules[1].concurrency=1;c.current().settings.rules[1].maxFileBytes='5';const a=await c.open(sender,'send');await a.next();a.send({type:'create',summary,note:''});assert.equal((await a.next()).code,'FT_FILE_SIZE_LIMIT');c.current().settings.rules[1].maxFileBytes=null;const b=await c.open(sender,'send');await b.next();b.send({type:'create',summary,note:''});await b.next();const d=await c.open({...sender,sessionVersion:'another-login'},'send');await d.next();d.send({type:'create',summary,note:''});assert.equal((await d.next()).code,'FT_CONCURRENCY')});
test('signed HTTP ticket issuance binds method, body and single-use host nonce',async t=>{const{config}=fixture(t);const keys=generateKeyPairSync('ed25519');const store=openStorage(config);store.setManager('sender',true);const snap=store.readSettings();store.saveSettings({revision:snap.revision,settings:settings(),managers:['sender']},'sender');store.close();const service=createService({...config,port:0,bridgePublicKey:keys.publicKey.export({type:'spki',format:'der'}).toString('base64')});const address=await service.listen();t.after(()=>service.close());const origin=`http://127.0.0.1:${address.port}`;const body=JSON.stringify({role:'send'}),token=signBridgeToken(keys.privateKey,sender,ROUTES.ticket,{method:'PUT',body});const request=(value=body)=>fetch(origin+ROUTES.ticket,{method:'PUT',headers:{'content-type':'application/json',authorization:'Bearer '+token},body:value});assert.equal((await request(JSON.stringify({role:'receive'}))).status,401);const response=await request();assert.equal(response.status,200);const issued=await response.json();assert.equal(issued.ticket.length,43);assert.equal(issued.signalPath,ROUTES.signal);assert.equal((await request()).status,401);assert.equal((await fetch(origin+ROUTES.ticket)).status,405)});

test('task rate requests can only lower the server-combined role cap',async t=>{
 const c=await context(t);c.current().settings.rules[1].lanRateKbps=1000;
 const a=await c.open(sender,'send'),b=await c.open(receiver,'receive');await a.next();await b.next();
 a.send({type:'create',summary,note:'',rateKbps:9000});const created=await a.next();b.send({type:'join',code:created.code,rateKbps:300});await b.next();await a.next();a.send({type:'confirm'});await a.next();b.send({type:'confirm'});await a.next();await b.next();
 const local={address:'192.168.1.2',port:5000,type:'host',protocol:'udp'},remote={...local,address:'192.168.1.3',port:6000};a.send({type:'route',route:{local,remote}});b.send({type:'route',route:{local:remote,remote:local}});assert.equal((await a.next()).rateKbps,300);assert.equal((await b.next()).rateKbps,300);
});
test('daily allowance rejects a sender before code publication and a receiver before invitation',async t=>{
 const c=await context(t);c.current().settings.rules[1].dailyBytes='11';const a=await c.open(sender,'send');await a.next();a.send({type:'create',summary,note:''});assert.equal((await a.next()).code,'FT_QUOTA_DAILY');
 c.current().settings.rules[1].dailyBytes='12';const b=await c.open(sender,'send');await b.next();b.send({type:'create',summary,note:''});const created=await b.next();assert.equal(created.type,'created');
 c.current().settings.rules[1].dailyBytes='11';const r=await c.open(receiver,'receive');await r.next();r.send({type:'join',code:created.code});assert.equal((await r.next()).code,'FT_QUOTA_DAILY');assert.equal(c.usage.snapshot(receiver,c.current().settings,c.now()).personal.daily.reservedBytes,'0');
});
test('an invalid task rate is rejected before any reservation',async t=>{const c=await context(t);const a=await c.open(sender,'send');await a.next();a.send({type:'create',summary,note:'',rateKbps:0});assert.equal((await a.next()).code,'FT_PROTOCOL');assert.equal(c.usage.snapshot(sender,c.current().settings,c.now()).personal.activeTasks,0)});
