import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { pullGuard } from '../server/pull-guard.mjs';
import { prepareTransfer } from '../web/files/direct.mjs';
import { collectFiles } from '../web/files/collection.mjs';
import { encodeWire,decodeWire } from '../shared/wire.mjs';
const request=(guard,value)=>guard.request(JSON.stringify(value));
function frame(id,index,offset,data){const b=new Uint8Array(48+data.length),v=new DataView(b.buffer);v.setUint32(0,id);v.setInt32(4,index);v.setBigUint64(8,BigInt(offset));b.set(createHash('sha256').update(data).digest(),16);b.set(data,48);return b.buffer;}
async function fixture(){const p=await prepareTransfer(collectFiles([new File(['data'],'one.txt')])),g=pullGuard(p.summary),manifest=Buffer.from(JSON.stringify(p.bundle.manifest));request(g,{type:'manifest-info',id:1});g.response(JSON.stringify({type:'manifest-info',id:1,bytes:manifest.length}));request(g,{type:'read',id:2,index:-1,offset:'0',length:manifest.length});g.response(frame(2,-1,0,manifest));return g;}
test('relay guard refuses unsolicited, duplicate, out-of-order and excessive reads before forwarding',async()=>{const g=await fixture();assert.equal(g.complete(),false);assert.throws(()=>g.response('unexpected'),/FT_PROTOCOL/);for(const value of [{id:4,type:'read',index:0,offset:'0',length:4},{id:3,type:'read',index:1,offset:'0',length:4},{id:3,type:'read',index:0,offset:'1',length:3},{id:3,type:'read',index:0,offset:'0',length:5},{id:3,type:'finish',index:0}])assert.throws(()=>request(g,value),/FT_PROTOCOL/);request(g,{id:3,type:'read',index:0,offset:'0',length:4});assert.throws(()=>request(g,{id:4,type:'read',index:0,offset:'0',length:4}),/FT_PROTOCOL/);const bad=frame(3,0,0,Buffer.from('data'));new Uint8Array(bad)[48]^=1;assert.throws(()=>g.response(bad),/FT_INTEGRITY/);assert.equal(g.complete(),false)});
test('relay guard requires a correct final chained digest and bounded canonical wire frames',async()=>{const g=await fixture();request(g,{id:3,type:'read',index:0,offset:'0',length:4});g.response(frame(3,0,0,Buffer.from('data')));request(g,{id:4,type:'finish',index:0});assert.throws(()=>g.response(JSON.stringify({id:4,type:'finish',index:0,size:'4',chain:'a'.repeat(64)})),/FT_INTEGRITY/);assert.equal(g.complete(),false);assert.throws(()=>encodeWire(new Uint8Array(16385)),/FT_PROTOCOL/);for(const value of [{binary:true,data:'Zg'},{binary:true,data:'!!!!'},{binary:false,data:'x',extra:true}])assert.throws(()=>decodeWire(value),/FT_PROTOCOL/)});
