import {usagePeriods} from '../server/usage.mjs';
import {rtcAdapters} from './rtc-fixture.mjs';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import WebSocket from 'ws';
import {fixture} from './helpers.mjs';
import {openStorage} from '../server/storage.mjs';
import {createPairing} from '../server/pairing.mjs';
import {DirectPeer} from '../web/files/peer.mjs';
import {collectFiles} from '../web/files/collection.mjs';
import {prepareTransfer} from '../web/files/direct.mjs';
import {initialPoint,samePoint} from '../shared/recovery.mjs';
import {recoveryHistory} from '../web/files/recovery-history.mjs';
const identity=uid=>({kind:'user',uid,name:uid,roleId:'staff',roleName:'Staff',sessionVersion:'s-'+uid,mustChangePassword:false});
async function wait(fn,details=()=>'',ms=12000){const end=Date.now()+ms;while(!fn()){if(Date.now()>end)throw Error('timeout '+details());await new Promise(ok=>setTimeout(ok,5))}}
function disk(){const files=new Map(),dirs=new Set(['']),writers=new Set();function file(path){return{name:path.split('/').at(-1),async getFile(){return new File([files.get(path)||new Uint8Array()],path.split('/').at(-1))},async createWritable({keepExistingData=false}={}){if(writers.has(path))throw Error('writer still locked');writers.add(path);let bytes=keepExistingData?(files.get(path)||new Uint8Array()).slice():new Uint8Array(),position=0,ended=false;const done=()=>{assert.equal(ended,false);ended=true;writers.delete(path)};return{async seek(n){position=n},async truncate(n){const next=new Uint8Array(n);next.set(bytes.subarray(0,n));bytes=next},async write(value){const length=position+value.length;if(length>bytes.length){const next=new Uint8Array(length);next.set(bytes);bytes=next}bytes.set(value,position);position=length},async close(){done();files.set(path,bytes.slice())},async abort(){if(!ended)done()}}}}}
function directory(path=''){return{name:path.split('/').at(-1)||'selected',async getDirectoryHandle(name,{create=false}={}){const next=path+'/'+name;if(!dirs.has(next)){if(!create)throw Object.assign(Error(),{name:'NotFoundError'});dirs.add(next)}return directory(next)},async getFileHandle(name,{create=false}={}){const next=path+'/'+name;if(!files.has(next)){if(!create)throw Object.assign(Error(),{name:'NotFoundError'});files.set(next,new Uint8Array())}return file(next)}}}return{files,dirs,writers,file,directory};}
async function setup(t,patch={}){const cleanup=[],{config}=fixture({after:f=>cleanup.push(f)});let store=openStorage(config),pairing;store.setManager('owner',true);const s=store.readSettings();Object.assign(s.settings,{enabled:true,lanVerified:true,lanNetworks:'192.168.1.0/24',relayEnabled:true,shareEnabled:true,serverVpnPath:'confirmed-outside-vpn',serverOutsideVerified:true,wanRateKbps:null,checkpointMiB:1,automaticRetries:0,...patch});s.settings.rules[1].links=['lan-direct','wan-direct','server-relay','temporary-share'];store.saveSettings({revision:s.revision,settings:s.settings,managers:s.managers},'owner');if(patch.vpnMeterSource==='snapshot'){const at=Date.now(),periods=usagePeriods(at,s.settings.vpnTimeZone);store.vpn.observe({kind:'snapshot',sourceId:s.settings.vpnSourceId,observedAt:at,timeZone:s.settings.vpnTimeZone,billing:s.settings.vpnBilling,daily:{...periods.daily,usedBytes:'0'},monthly:{...periods.monthly,usedBytes:'0'}},store.readSettings().revision,at);}pairing=createPairing(store);const server=createServer(),peers=[],sockets=[];server.on('upgrade',(...args)=>pairing.upgrade(...args));await new Promise(ok=>server.listen(0,'127.0.0.1',ok));let networkBytes=0;
const c={get store(){return store},peer(uid,saved=disk()){const scope={isSecureContext:true,crypto,location:{href:'https://teacher.invalid/zh/transfer'},showSaveFilePicker:async()=>saved.file('/output.bin'),showDirectoryPicker:async()=>saved.directory(),WebSocket:class{constructor(){const socket=new WebSocket(`ws://127.0.0.1:${server.address().port}/transfer-api/v1/signal`);sockets.push(socket);socket.on('message',buffer=>{const data=JSON.parse(buffer.toString());if(data.type==='relay'&&data.wire.binary){const frame=Buffer.from(data.wire.data,'base64');if(frame.readInt32BE(4)>=0)networkBytes+=frame.length-48}});return socket}}};const p=new DirectPeer({scope,ticket:(role,transport)=>pairing.issue(identity(uid),{role,transport})});peers.push(p);return{p,saved,scope}},get networkBytes(){return networkBytes},async restart(){await pairing.close();store.close();store=openStorage(config);store.recovery.recover();await store.shares.recover();pairing=createPairing(store);}};
t.after(async()=>{peers.forEach(p=>p.stop());sockets.forEach(s=>s.terminate());await pairing.close();await new Promise(ok=>server.close(ok));store.close();cleanup.forEach(fn=>fn())});return c;}
const bytes=()=>Uint8Array.from({length:1400001},(_,i)=>i%251);
async function online(c,bundle,transport='server-relay'){const a=c.peer('sender'),b=c.peer('receiver');if(['lan-direct','wan-direct'].includes(transport)){const RTC=rtcAdapters({wan:transport==='wan-direct'});a.scope.RTCPeerConnection=b.scope.RTCPeerConnection=RTC;}await a.p.create(bundle,'',null,transport);await wait(()=>a.p.state.status==='waiting-peer');await b.p.join(a.p.state.link);await wait(()=>a.p.state.status==='confirm'&&b.p.state.status==='confirm');a.p.confirm();b.p.confirm();await wait(()=>b.p.state.status==='ready-save',()=>JSON.stringify({a:a.p.state,b:b.p.state}));return{a,b};}
function pauseAfterCheckpoint(peer){let once=true;const original=peer.checkpoint.bind(peer);peer.checkpoint=async point=>{await original(point);if(once&&point.bytes!=='0'&&point.fileIndex===0){once=false;peer.pause();}};return()=>{peer.checkpoint=original};}
test('relay resumes a committed partial file without retransmitting its prefix or charging personal allowance twice',async t=>{const c=await setup(t),data=bytes(),bundle=collectFiles([new File([data],'one.bin')]),{a,b}=await online(c,bundle),restore=pauseAfterCheckpoint(b.p);await b.p.save('file');await wait(()=>a.p.state.status==='paused'&&b.p.state.status==='paused');const saved=b.p.recovery.point;assert.ok(BigInt(saved.bytes)>=1048576n);assert.equal(b.saved.files.get('/output.bin').length,Number(saved.bytes));restore();await Promise.all([a.p.resume(),b.p.resume()]);await wait(()=>b.p.state.status==='complete'&&a.p.state.status==='complete',()=>JSON.stringify({a:a.p.state,b:b.p.state}));assert.deepEqual(b.saved.files.get('/output.bin'),data);assert.equal(c.networkBytes,data.length);assert.equal(c.store.usage.snapshot(identity('receiver'),c.store.readSettings().settings).personal.daily.usedBytes,String(data.length));assert.equal(b.saved.writers.size,0)});
test('service restart preserves paired task ownership and checkpoint while avoiding duplicate authorization',async t=>{const c=await setup(t),data=bytes(),{a,b}=await online(c,collectFiles([new File([data],'one.bin')])),restore=pauseAfterCheckpoint(b.p);await b.p.save('file');await wait(()=>a.p.state.status==='paused');const task=b.p.recovery.task;await c.restart();restore();await Promise.all([a.p.resume(),b.p.resume()]);await wait(()=>b.p.state.status==='complete',()=>JSON.stringify({a:a.p.state,b:b.p.state}));assert.deepEqual(b.saved.files.get('/output.bin'),data);assert.equal(c.store.recovery.get(task).state,'complete');assert.equal(c.store.usage.snapshot(identity('sender'),c.store.readSettings().settings).personal.daily.usedBytes,String(data.length))});
test('changed local destination prefix is rejected before receiving additional file bytes',async t=>{const c=await setup(t),{a,b}=await online(c,collectFiles([new File([bytes()],'one.bin')])),restore=pauseAfterCheckpoint(b.p);await b.p.save('file');await wait(()=>a.p.state.status==='paused');restore();const before=c.networkBytes;b.saved.files.get('/output.bin')[0]^=1;await Promise.all([a.p.resume(),b.p.resume()]);await wait(()=>b.p.state.status==='error');assert.equal(b.p.state.error,'FT_CHECKPOINT_INVALID');assert.equal(c.networkBytes,before)});
test('temporary upload resumes after restart and keeps its original send allowance',async t=>{const c=await setup(t),a=c.peer('sender'),data=bytes();let once=true;const original=a.p.message.bind(a.p);a.p.message=async message=>{await original(message);if(message.type==='checkpoint'&&once&&message.point.fileIndex===0&&message.point.bytes!=='0'){once=false;a.p.pause()}};await a.p.create(collectFiles([new File([data],'one.bin')]),'',null,'temporary-share');await wait(()=>a.p.state.status==='paused',()=>JSON.stringify(a.p.state));const task=a.p.recovery.task,id=c.store.recovery.get(task).extra.shareId;await c.restart();assert.equal(c.store.shares.list().items.find(x=>x.id===id).state,'uploading');await a.p.resume();await wait(()=>['shared','error'].includes(a.p.state.status),()=>JSON.stringify(a.p.state));assert.equal(a.p.state.status,'shared',JSON.stringify(a.p.state));assert.equal(c.store.usage.snapshot(identity('sender'),c.store.readSettings().settings).personal.daily.usedBytes,String(data.length));const b=c.peer('receiver');await b.p.join(a.p.state.link);await wait(()=>b.p.state.status==='share-preview');b.p.claimShare();await wait(()=>b.p.state.status==='ready-save');await b.p.save('file');await wait(()=>b.p.state.status==='complete');assert.deepEqual(b.saved.files.get('/output.bin'),data)});
test('one-count temporary retrieval can resume without consuming another count or receiving allowance',async t=>{const c=await setup(t),a=c.peer('sender'),data=bytes();await a.p.create(collectFiles([new File([data],'one.bin')]),'',null,'temporary-share');await wait(()=>a.p.state.status==='shared',()=>JSON.stringify(a.p.state));const b=c.peer('receiver');await b.p.join(a.p.state.link);await wait(()=>b.p.state.status==='share-preview');b.p.claimShare();await wait(()=>b.p.state.status==='ready-save');const restore=pauseAfterCheckpoint(b.p);await b.p.save('file');assert.equal(b.p.state.status,'paused');restore();await b.p.resume();await wait(()=>['complete','error'].includes(b.p.state.status),()=>JSON.stringify(b.p.state));assert.equal(b.p.state.status,'complete',JSON.stringify(b.p.state));assert.deepEqual(b.saved.files.get('/output.bin'),data);assert.equal(c.store.shares.list().items[0].downloads,1);assert.equal(c.store.usage.snapshot(identity('receiver'),c.store.readSettings().settings).personal.daily.usedBytes,String(data.length))});
test('persisted metadata is bounded, identity-scoped and contains no file contents or handles',async()=>{const items=new Map(),history=recoveryHistory({localStorage:{getItem:key=>items.get(key),setItem:(key,value)=>items.set(key,value)}}),prepared=await prepareTransfer(collectFiles([new File(['secret-file-content'],'private-name.txt')])) ,record={task:'task',token:'a'.repeat(43),transport:'server-relay',point:initialPoint(),summary:prepared.summary,expiresAt:Date.now()+60000};assert.equal(history.put('one','send',record),true);assert.equal(history.list('two').length,0);assert.equal(history.list('one').length,1);assert.ok(![...items.values()][0].includes('private-name'));assert.ok(![...items.values()][0].includes('secret-file-content'));history.remove('one','task','send');assert.equal(history.list('one').length,0);assert.equal(recoveryHistory({localStorage:{getItem(){throw Error('denied')},setItem(){throw Error('denied')}}}).put('one','send',record),false)});

test('connection loss automatically rejoins the same relay and continues with the retained disk handle',async t=>{const c=await setup(t,{automaticRetries:3}),data=bytes(),{a,b}=await online(c,collectFiles([new File([data],'one.bin')]));let once=true;const original=b.p.checkpoint.bind(b.p);b.p.checkpoint=async point=>{await original(point);if(once&&point.bytes!=='0'&&point.fileIndex===0){once=false;b.p.socket.terminate()}};await b.p.save('file');await wait(()=>b.p.state.status==='complete'&&a.p.state.status==='complete',()=>JSON.stringify({a:a.p.state,b:b.p.state}));assert.equal(b.p.state.retryCount,1);assert.equal(b.p.state.transport,'server-relay');assert.deepEqual(b.saved.files.get('/output.bin'),data);assert.equal(c.store.usage.snapshot(identity('receiver'),c.store.readSettings().settings).personal.daily.usedBytes,String(data.length))});
test('LAN and verified WAN reconnect through fresh reciprocal RTC routes while preserving the saved prefix',async t=>{for(const transport of ['lan-direct','wan-direct']){const c=await setup(t,{wanVerified:true,wanNetworks:'8.8.8.0/24'}),data=bytes(),{a,b}=await online(c,collectFiles([new File([data],'one.bin')]),transport),restore=pauseAfterCheckpoint(b.p);await b.p.save('file');await wait(()=>a.p.state.status==='paused');restore();await Promise.all([a.p.resume(),b.p.resume()]);await wait(()=>b.p.state.status==='complete',()=>JSON.stringify({a:a.p.state,b:b.p.state}));assert.deepEqual(b.saved.files.get('/output.bin'),data);assert.equal(b.p.state.transport,transport)}});
test('folder recovery skips verified complete files, resumes the current file and keeps empty directories',async t=>{const c=await setup(t),large=new File([bytes()],'b.bin',{lastModified:10}),small=new File(['before'],'a.txt',{lastModified:10});Object.defineProperty(large,'webkitRelativePath',{value:'资料/b.bin'});Object.defineProperty(small,'webkitRelativePath',{value:'资料/a.txt'});const bundle=collectFiles([large,small],{directory:true});bundle.manifest.entries.push({relativePath:'资料/空目录',kind:'directory',sizeBytes:'0',modifiedAt:null});const{a,b}=await online(c,bundle);let once=true;const original=b.p.checkpoint.bind(b.p);b.p.checkpoint=async point=>{await original(point);if(once&&point.fileIndex===1&&BigInt(point.offset)>0n){once=false;b.p.pause()}};await b.p.save('directory');await wait(()=>a.p.state.status==='paused');const folder=b.p.saveContext.handle.name;await Promise.all([a.p.resume(),b.p.resume()]);await wait(()=>b.p.state.status==='complete',()=>JSON.stringify(b.p.state));assert.equal(b.p.saveContext.handle.name,folder);assert.deepEqual([...b.saved.files].find(([name])=>name.endsWith('/b.bin'))[1],bytes());assert.equal(Buffer.from([...b.saved.files].find(([name])=>name.endsWith('/a.txt'))[1]).toString(),'before');assert.ok([...b.saved.dirs].some(path=>path.endsWith('/资料/空目录')))});
test('recovery token cannot be attached under another user identity and policy changes reject the old task',async t=>{const c=await setup(t),{a,b}=await online(c,collectFiles([new File([bytes()],'one.bin')]));pauseAfterCheckpoint(b.p);await b.p.save('file');await wait(()=>a.p.state.status==='paused');const record={...b.p.recovery,role:'receive'},other=c.peer('intruder');await other.p.resume(null,record);await wait(()=>other.p.state.status==='error');assert.equal(other.p.state.error,'FT_RECOVERY_UNAVAILABLE');const s=c.store.readSettings();s.settings.rules[1].receive=false;c.store.saveSettings({revision:s.revision,settings:s.settings,managers:s.managers},'owner');await b.p.resume();await wait(()=>b.p.state.status==='error');assert.equal(b.p.state.error,'FT_ACCESS_DENIED');assert.ok(!c.store.usage.snapshot(identity('intruder'),c.store.readSettings().settings).personal.activeTasks)});

test('new controllers restore serialized metadata after reload and require explicit destination selection',async t=>{const c=await setup(t),data=bytes(),bundle=collectFiles([new File([data],'one.bin',{lastModified:10})]),{a,b}=await online(c,bundle);pauseAfterCheckpoint(b.p);await b.p.save('file');await wait(()=>a.p.state.status==='paused');const ar=JSON.parse(JSON.stringify({...a.p.recovery,role:'send'})),br=JSON.parse(JSON.stringify({...b.p.recovery,role:'receive',kind:'file',destinationName:'output.bin'}));a.p.stop();b.p.stop();const nextA=c.peer('sender'),nextB=c.peer('receiver',b.saved);await Promise.all([nextA.p.resume(bundle,ar),nextB.p.resume(null,br)]);await wait(()=>nextB.p.state.status==='ready-save',()=>JSON.stringify({a:nextA.p.state,b:nextB.p.state}));assert.equal(nextB.p.saveContext,null);await nextB.p.save('file');await wait(()=>nextB.p.state.status==='complete');assert.deepEqual(b.saved.files.get('/output.bin'),data);assert.equal(c.store.usage.snapshot(identity('receiver'),c.store.readSettings().settings).personal.daily.usedBytes,String(data.length))});
test('lost checkpoint acknowledgement retransmits unconfirmed data safely without a second personal charge',async t=>{const c=await setup(t),data=bytes(),{a,b}=await online(c,collectFiles([new File([data],'one.bin')]));let once=true;const send=b.p.send.bind(b.p);b.p.send=message=>{if(message.type==='checkpoint'&&once&&message.point.fileIndex===0){once=false;b.p.socket.terminate();return;}return send(message)};await b.p.save('file');await wait(()=>a.p.state.status==='error'&&b.p.state.status==='error');assert.equal(b.p.recovery.point.bytes,'0');assert.ok(b.saved.files.get('/output.bin').length>=1048576);await Promise.all([a.p.resume(),b.p.resume()]);await wait(()=>b.p.state.status==='complete',()=>JSON.stringify({a:a.p.state,b:b.p.state}));assert.deepEqual(b.saved.files.get('/output.bin'),data);assert.ok(c.networkBytes>=data.length+1048576);assert.equal(c.store.usage.snapshot(identity('receiver'),c.store.readSettings().settings).personal.daily.usedBytes,String(data.length))});
test('metered relay recovery issues new traffic budgets for remaining frames while retaining one personal charge',async t=>{const c=await setup(t,{serverVpnPath:'confirmed-vpn',vpnMeterSource:'snapshot',vpnScopeVerified:true,vpnProtectionMode:'estimate',vpnDailyBytes:'50000000',vpnMonthlyBytes:'100000000',vpnReserveBytes:'0'}),data=bytes(),{a,b}=await online(c,collectFiles([new File([data],'one.bin')])),restore=pauseAfterCheckpoint(b.p);await b.p.save('file');await wait(()=>a.p.state.status==='paused');const pending=BigInt(c.store.vpn.view().pendingBytes);assert.ok(pending>0n);restore();await Promise.all([a.p.resume(),b.p.resume()]);await wait(()=>b.p.state.status==='complete',()=>JSON.stringify({a:a.p.state,b:b.p.state}));assert.ok(BigInt(c.store.vpn.view().pendingBytes)>pending);assert.equal(c.store.usage.snapshot(identity('receiver'),c.store.readSettings().settings).personal.daily.usedBytes,String(data.length))});

test('cancelling a paused task revokes its server recovery credentials',async t=>{const c=await setup(t),{a,b}=await online(c,collectFiles([new File([bytes()],'one.bin')]));pauseAfterCheckpoint(b.p);await b.p.save('file');await wait(()=>a.p.state.status==='paused');const task=b.p.recovery.task;b.p.cancel();await wait(()=>b.p.state.status==='cancelled',()=>JSON.stringify(b.p.state));assert.throws(()=>c.store.recovery.get(task),/FT_RECOVERY_UNAVAILABLE/);await a.p.resume();await wait(()=>a.p.state.status==='error');assert.equal(a.p.state.error,'FT_RECOVERY_UNAVAILABLE')});
test('many small files checkpoint independently without exhausting the ordinary signaling request limit',async t=>{const c=await setup(t),bundle=collectFiles(Array.from({length:320},(_,i)=>new File([],'file-'+String(i).padStart(4,'0')+'.txt',{lastModified:1}))),{a,b}=await online(c,bundle);await b.p.save('directory');await wait(()=>b.p.state.status==='complete'&&a.p.state.status==='complete',()=>JSON.stringify({a:a.p.state,b:b.p.state}));assert.equal(b.saved.files.size,320);assert.equal(b.saved.writers.size,0);assert.ok([...b.saved.files.values()].every(value=>value.length===0))});
