<script setup lang="ts">
import {ref,onMounted,computed} from 'vue'
import {useRouter,useRoute} from 'vue-router'
import {useAuthSession} from './imports'
const router=useRouter(),route=useRoute(),auth=useAuthSession(),setup=ref(false),name=ref(''),password=ref(''),token=ref(''),busy=ref(false),error=ref(''),ready=ref(false),zh=computed(()=>route.params.locale!=='en')
onMounted(async()=>{try{const s=await auth.load();setup.value=s.setupRequired;ready.value=true}catch{error.value=zh.value?'连接失败，请刷新重试。':'Connection failed. Please reload.'}})
async function submit(){busy.value=true;error.value='';try{if(setup.value)await $fetch('/transfer-api/v1/auth/setup',{method:'POST',body:{name:name.value,password:password.value,token:token.value}});await $fetch('/transfer-api/v1/auth/login',{method:'POST',body:{name:name.value,password:password.value}});await auth.load();const next=typeof route.query.next==='string'&&route.query.next.startsWith('/')&&!route.query.next.startsWith('//')?route.query.next:'/transfer-admin/';await router.push(next)}catch(e:any){error.value=({FT_LOGIN_FAILED:zh.value?'账号或密码不正确。':'Incorrect account or password.',FT_TOO_MANY_ATTEMPTS:zh.value?'尝试过于频繁，请 15 分钟后重试。':'Too many attempts. Retry in 15 minutes.',FT_AUTH_REQUIRED:zh.value?'初始化令牌不正确或尚未配置。':'Setup token is missing or incorrect.',FT_SETUP_COMPLETE:zh.value?'初始化已完成，请刷新后登录。':'Setup is complete. Reload to sign in.'}as any)[e.data?.error?.code]||(zh.value?'操作失败，请检查输入后重试。':'Please check your input and retry.')}finally{busy.value=false;password.value=''}}
</script>
<template><main class="ft-login ft-panel"><p class="ft-eyebrow">{{zh?'欢迎使用':'WELCOME'}}</p><h1>{{setup?(zh?'初始化管理账号':'Create the first administrator'):(zh?'登录文件快传':'Sign in')}}</h1><p class="ft-muted">{{zh?'独立账号，仅用于此文件快传实例。':'This account belongs to this transfer instance.'}}</p><form @submit.prevent="submit"><label v-if="setup" class="ft-field">{{zh?'初始化令牌':'Setup token'}}<input v-model="token" type="password" required autocomplete="off"><small>{{zh?'在部署环境中设置 FT_SETUP_TOKEN，仅首次初始化使用。':'Set FT_SETUP_TOKEN in your deployment environment.'}}</small></label><label class="ft-field">{{zh?'账号名称':'Account name'}}<input v-model="name" required maxlength="64" autocomplete="username"></label><label class="ft-field">{{zh?'密码（至少 6 位）':'Password (at least 6 characters)'}}<input v-model="password" type="password" required minlength="6" maxlength="256" :autocomplete="setup?'new-password':'current-password'"></label><p v-if="error" role="alert">{{error}}</p><button class="ft-button" :disabled="busy||!ready">{{busy?(zh?'请稍候…':'Please wait…'):setup?(zh?'创建并登录':'Create & sign in'):(zh?'登录':'Sign in')}}</button></form></main></template>
