import type { FileManifest, FileStats } from './files';
import type { AccessRule } from './client';
export const FILE_LIMITS: { entries: number; depth: number; pathBytes: number; componentBytes: number; totalPathBytes: number; chunkBytes: number; memoryDownloadBytes: number };
export function fileError(code: string, path?: string): Error & { code: string; path: string };
export function checkAbort(signal?: AbortSignal): void;
export function safePath(value: string): string;
export function pathKey(value: string): string;
export function renamedPath(path: string, attempt: number, directory?: boolean): string;
export function validateManifest(manifest: FileManifest): FileStats;
export function policyWarnings(manifest: FileManifest, rule?: AccessRule): string[];
