import type { SettingField, ToolSettings, AccessRule, PublicPolicy } from './client';
export const SETTINGS_SECTIONS: { id: string; zh: string; en: string; fields: SettingField[] }[];
export const POLICY_FIELDS: SettingField[];
export function defaultSettings(): ToolSettings;
export function defaultRule(kind?: string, id?: string): AccessRule;
export function validateSettings(value: unknown): ToolSettings;
export function validateSubmission(value: unknown): { revision: number; settings: ToolSettings; managers: string[] };
export function bytesToGB(value: string | null): string;
export function gbToBytes(value: string, nullable?: boolean): string | null;
export function validUid(value: unknown): boolean;
export function settingsError(code: string, status: number, fields?: Record<string, string>): Error & { code: string; status: number; fields: Record<string, string> };
export function publicPolicy(settings: ToolSettings, identity: unknown, usage?: unknown, vpn?: unknown): PublicPolicy;
