from __future__ import annotations


EXAMPLE_ROWS = {
    "profiles": [
        {
            "uid": "profile-member-wang",
            "name": "王五",
            "role": "副教授",
            "title": "副教授 / 硕士生导师",
            "organization": "某某大学",
            "lab": "智能系统实验室",
            "avatar_key": "default/teacher-default-avatar.png",
            "email": "wangwu@example.edu.cn",
            "office": "理工楼 A-503",
            "bio": "关注学习分析、教育数据挖掘和可解释智能评价，负责团队教育数据平台建设。",
            "personal_homepage": "https://example.edu.cn/wangwu",
            "contact_visibility": "public",
            "visibility": "public",
            "is_active": 1,
            "is_featured": 1,
            "sort_order": 5,
        },
        {
            "uid": "profile-member-zhao",
            "name": "赵六",
            "role": "博士后",
            "title": "博士后研究员",
            "organization": "某某大学",
            "lab": "智能系统实验室",
            "avatar_key": "default/teacher-default-avatar.png",
            "email": "zhaoliu@example.edu.cn",
            "bio": "研究方向为边缘智能系统、低资源推理与模型压缩。",
            "github": "https://github.com/",
            "visibility": "public",
            "is_active": 1,
            "is_featured": 1,
            "sort_order": 10,
        },
        {
            "uid": "profile-member-chen",
            "name": "陈晨",
            "role": "硕士生",
            "title": "2025 级硕士研究生",
            "organization": "某某大学",
            "avatar_key": "default/teacher-default-avatar.png",
            "email": "chenchen@example.edu.cn",
            "bio": "参与团队个人主页平台和学术内容迁移工具开发。",
            "visibility": "public",
            "is_active": 1,
            "is_featured": 0,
            "sort_order": 30,
        },
        {
            "uid": "profile-member-sun",
            "name": "孙悦",
            "role": "本科生助研",
            "title": "科研训练学生",
            "organization": "某某大学",
            "avatar_key": "default/teacher-default-avatar.png",
            "email": "sunyue@example.edu.cn",
            "bio": "协助维护课程资料、新闻动态和项目展示数据。",
            "visibility": "public",
            "is_active": 1,
            "is_featured": 0,
            "sort_order": 40,
        },
    ],
    "research_interests": [
        {"uid": "interest-rag", "name": "学术知识增强生成", "description": "围绕论文、项目、课程资料构建可检索、可追溯的知识问答系统。", "sort_order": 4, "visibility": "public"},
        {"uid": "interest-edge-ai", "name": "边缘智能与低资源部署", "description": "面向 Cloudflare Worker、嵌入式设备和低 CPU 服务器的轻量推理与系统优化。", "sort_order": 5, "visibility": "public"},
        {"uid": "interest-data-governance", "name": "科研数据治理", "description": "研究科研成果、学生动态、媒体资源和导出迁移包的结构化管理。", "sort_order": 6, "visibility": "public"},
    ],
    "publications": [
        {
            "uid": "pub-edge-teacher-site-2026",
            "title": "A Dual-Deployment Architecture for Academic Personal Websites",
            "authors": "San Zhang; Wu Wang; Chen Chen",
            "venue": "Proceedings of Web Engineering in Education",
            "year": 2026,
            "doi": "10.0000/example.2026.002",
            "citation_gbt": "Zhang S, Wang W, Chen C. A Dual-Deployment Architecture for Academic Personal Websites[C]. Proceedings of Web Engineering in Education, 2026.",
            "citation_apa": "Zhang, S., Wang, W., & Chen, C. (2026). A Dual-Deployment Architecture for Academic Personal Websites. Proceedings of Web Engineering in Education.",
            "citation_ieee": "S. Zhang, W. Wang and C. Chen, \"A Dual-Deployment Architecture for Academic Personal Websites,\" Proceedings of Web Engineering in Education, 2026.",
            "publication_type": "会议论文",
            "author_role": "corresponding",
            "index_type": "EI",
            "keywords": "academic website; Cloudflare Workers; migration",
            "visibility": "public",
            "pdf_visibility": "public",
            "is_featured": 1,
            "sort_order": 2,
        },
        {
            "uid": "pub-learning-analytics-2025",
            "title": "Learning Analytics with Interpretable Student Progress Models",
            "authors": "Wu Wang; San Zhang",
            "venue": "Education Data Science",
            "year": 2025,
            "doi": "10.0000/example.2025.011",
            "citation_gbt": "Wang W, Zhang S. Learning Analytics with Interpretable Student Progress Models[J]. Education Data Science, 2025.",
            "citation_apa": "Wang, W., & Zhang, S. (2025). Learning Analytics with Interpretable Student Progress Models. Education Data Science.",
            "citation_ieee": "W. Wang and S. Zhang, \"Learning Analytics with Interpretable Student Progress Models,\" Education Data Science, 2025.",
            "publication_type": "期刊论文",
            "author_role": "other",
            "index_type": "CSSCI",
            "keywords": "learning analytics; interpretability",
            "visibility": "public",
            "pdf_visibility": "public",
            "is_featured": 1,
            "sort_order": 3,
        },
        {
            "uid": "pub-rag-courseware-2025",
            "title": "Retrieval-Augmented Courseware Organization for Research Training",
            "authors": "San Zhang; Liu Zhao; Si Li",
            "venue": "Journal of Digital Learning Systems",
            "year": 2025,
            "doi": "10.0000/example.2025.021",
            "citation_gbt": "Zhang S, Zhao L, Li S. Retrieval-Augmented Courseware Organization for Research Training[J]. Journal of Digital Learning Systems, 2025.",
            "publication_type": "期刊论文",
            "author_role": "first",
            "index_type": "SCI",
            "keywords": "RAG; courseware; research training",
            "visibility": "public",
            "pdf_visibility": "public",
            "is_featured": 0,
            "sort_order": 4,
        },
        {
            "uid": "pub-lightweight-rendering-2024",
            "title": "Low-CPU Server-Side Rendering for Academic Information Systems",
            "authors": "Chen Chen; San Zhang",
            "venue": "Software Practice Notes",
            "year": 2024,
            "doi": "10.0000/example.2024.008",
            "citation_gbt": "Chen C, Zhang S. Low-CPU Server-Side Rendering for Academic Information Systems[J]. Software Practice Notes, 2024.",
            "publication_type": "技术报告",
            "author_role": "corresponding",
            "index_type": "校内报告",
            "keywords": "SSR; low CPU; academic systems",
            "visibility": "public",
            "pdf_visibility": "public",
            "is_featured": 0,
            "sort_order": 5,
        },
        {
            "uid": "pub-media-governance-2024",
            "title": "Media Asset Governance in Small Research Group Websites",
            "authors": "Yue Sun; San Zhang",
            "venue": "Open Web for Research Groups",
            "year": 2024,
            "doi": "10.0000/example.2024.015",
            "citation_gbt": "Sun Y, Zhang S. Media Asset Governance in Small Research Group Websites[C]. Open Web for Research Groups, 2024.",
            "publication_type": "会议论文",
            "author_role": "other",
            "index_type": "会议收录",
            "keywords": "media library; research group; website",
            "visibility": "public",
            "pdf_visibility": "public",
            "is_featured": 0,
            "sort_order": 6,
        },
    ],
    "projects": [
        {"uid": "project-rag-courseware", "name": "科研训练课程资源知识增强组织平台", "source": "省级教改项目", "fund_name": "教育数字化专项", "project_number": "EDU-2026-018", "principal": "王五", "members": "张三; 陈晨; 孙悦", "start_date": "2026-03-01", "end_date": "2028-02-29", "status": "在研", "amount": 15, "summary": "构建课程资料、论文阅读和学生训练过程的知识增强组织平台。", "visibility": "public", "is_featured": 1, "sort_order": 2},
        {"uid": "project-edge-worker", "name": "低资源边缘 Web 应用运行机制研究", "source": "横向合作", "fund_name": "智能边缘系统合作计划", "project_number": "EDGE-2025-006", "principal": "赵六", "members": "张三; 李四", "start_date": "2025-09-01", "end_date": "2027-08-31", "status": "在研", "amount": 30, "summary": "研究 Cloudflare Workers 等低 CPU 边缘运行环境下的动态网站架构。", "visibility": "public", "is_featured": 1, "sort_order": 3},
        {"uid": "project-publication-parser", "name": "科研成果自动解析与标准化工具", "source": "实验室开放课题", "fund_name": "学术数据治理计划", "project_number": "LAB-2025-003", "principal": "张三", "members": "陈晨", "start_date": "2025-01-01", "end_date": "2025-12-31", "status": "已结题", "amount": 5, "summary": "实现 DOI、BibTeX、GB/T 等论文引用格式的轻量解析和导出。", "visibility": "public", "is_featured": 0, "sort_order": 4},
        {"uid": "project-student-growth", "name": "研究生科研成长画像与过程评价", "source": "校级研究生教育项目", "fund_name": "研究生培养质量提升计划", "project_number": "GS-2024-112", "principal": "王五", "members": "李四; 孙悦", "start_date": "2024-06-01", "end_date": "2026-05-31", "status": "在研", "amount": 8, "summary": "围绕科研阅读、项目参与、论文写作和毕业去向构建学生成长画像。", "visibility": "public", "is_featured": 0, "sort_order": 5},
        {"uid": "project-media-archive", "name": "团队媒体资源归档与迁移系统", "source": "学院信息化建设", "fund_name": "网站内容治理专项", "project_number": "WEB-2024-009", "principal": "张三", "members": "孙悦", "start_date": "2024-03-01", "end_date": "2024-12-31", "status": "已结题", "amount": 6, "summary": "统一管理团队照片、新闻图片、PDF 附件和迁移清单。", "visibility": "public", "is_featured": 0, "sort_order": 6},
    ],
    "patents": [
        {"uid": "patent-courseware-rag", "name": "一种课程资料知识增强检索方法", "country": "中国", "patent_type": "发明专利", "application_number": "CN202610000001", "application_date": "2026-01-16", "inventors": "张三; 王五; 陈晨", "owner": "某某大学", "legal_status": "实质审查", "summary": "面向课程资料与论文阅读的知识增强检索方法。", "visibility": "public", "is_featured": 1, "sort_order": 2},
        {"uid": "patent-worker-render", "name": "一种低资源边缘网站动态渲染方法", "country": "中国", "patent_type": "发明专利", "application_number": "CN202510000018", "application_date": "2025-09-12", "inventors": "张三; 赵六", "owner": "某某大学", "legal_status": "申请中", "summary": "在低 CPU 限制环境下进行可配置动态页面渲染。", "visibility": "public", "is_featured": 1, "sort_order": 3},
        {"uid": "patent-media-recycle", "name": "一种科研网站媒体资源回收与恢复系统", "country": "中国", "patent_type": "实用新型", "application_number": "CN202420000031", "grant_number": "CN220000031U", "application_date": "2024-04-20", "grant_date": "2024-11-08", "inventors": "孙悦; 张三", "owner": "某某大学", "legal_status": "已授权", "summary": "支持媒体资源使用位置记录、回收站和恢复操作。", "visibility": "public", "is_featured": 0, "sort_order": 4},
        {"uid": "copyright-citation-parser", "name": "科研论文引用格式解析软件", "country": "中国", "patent_type": "软件著作权", "grant_number": "软著登字第000001号", "grant_date": "2025-05-22", "inventors": "陈晨; 张三", "owner": "某某大学", "legal_status": "已登记", "summary": "支持 BibTeX、GB/T、APA、IEEE 等格式解析。", "visibility": "public", "is_featured": 0, "sort_order": 5},
        {"uid": "copyright-export-bundle", "name": "学术网站数据导出迁移软件", "country": "中国", "patent_type": "软件著作权", "grant_number": "软著登字第000002号", "grant_date": "2025-07-09", "inventors": "张三; 李四", "owner": "某某大学", "legal_status": "已登记", "summary": "生成 JSON、YAML、CSV、Excel 与媒体清单导出包。", "visibility": "public", "is_featured": 0, "sort_order": 6},
    ],
    "students": [
        {"uid": "student-chen-chen", "name": "陈晨", "avatar_key": "default/student-default-avatar.png", "degree": "硕士", "category": "在读硕士", "grade": "2025", "direction": "低资源 Web 系统", "status": "在读", "email": "chenchen@example.edu.cn", "bio": "负责轻量后台、导出迁移工具和前台交互。", "visibility": "public", "contact_visibility": "public", "is_featured": 1, "sort_order": 2},
        {"uid": "student-sun-yue", "name": "孙悦", "avatar_key": "default/student-default-avatar.png", "degree": "本科", "category": "本科生助研", "grade": "2023", "direction": "媒体资源治理", "status": "在研", "email": "sunyue@example.edu.cn", "bio": "维护团队新闻、课程资料和媒体清单。", "visibility": "public", "contact_visibility": "public", "is_featured": 1, "sort_order": 3},
        {"uid": "student-zhou-min", "name": "周敏", "avatar_key": "default/student-default-avatar.png", "degree": "硕士", "category": "毕业生", "grade": "2021", "direction": "学习分析", "status": "已毕业", "email": "zhoumin@example.edu.cn", "graduation_date": "2024-06-30", "destination": "某科技公司算法工程师", "bio": "毕业论文关注学生学习路径建模。", "visibility": "public", "contact_visibility": "public", "is_featured": 0, "sort_order": 4},
        {"uid": "student-he-rui", "name": "何睿", "avatar_key": "default/student-default-avatar.png", "degree": "博士", "category": "毕业生", "grade": "2019", "direction": "可信人工智能", "status": "已毕业", "email": "herui@example.edu.cn", "graduation_date": "2025-06-30", "destination": "高校教师", "bio": "研究方向为模型鲁棒性和可解释性。", "visibility": "public", "contact_visibility": "public", "is_featured": 0, "sort_order": 5},
        {"uid": "student-lin-qiao", "name": "林乔", "avatar_key": "default/student-default-avatar.png", "degree": "硕士", "category": "联合培养", "grade": "2024", "direction": "学术知识图谱", "status": "在读", "email": "linqiao@example.edu.cn", "bio": "参与论文元数据补全和知识图谱构建。", "visibility": "public", "contact_visibility": "public", "is_featured": 0, "sort_order": 6},
    ],
    "student_category_displays": [
        {"uid": "cat-undergrad", "key": "undergrad", "label": "本科生助研", "keywords": "本科,助研,undergraduate", "enabled": 1, "display_order": 4},
        {"uid": "cat-joint", "key": "joint", "label": "联合培养", "keywords": "联合培养,访问,joint", "enabled": 1, "display_order": 5},
        {"uid": "cat-postdoc", "key": "postdoc", "label": "博士后", "keywords": "博士后,postdoc", "enabled": 1, "display_order": 6},
    ],
    "news": [
        {"uid": "news-project-approved", "title": "团队获批省级教育数字化专项", "slug": "project-approved", "category": "项目", "content": "团队牵头的科研训练课程资源知识增强组织平台获批立项，将围绕课程资料、论文阅读和学生训练过程开展系统建设。", "content_format": "plain", "published_at": "2026-07-20", "visibility": "public", "is_featured": 1, "sort_order": 2},
        {"uid": "news-paper-accepted", "title": "团队论文被 Web Engineering in Education 录用", "slug": "paper-accepted", "category": "论文", "content": "论文 A Dual-Deployment Architecture for Academic Personal Websites 被会议录用，介绍双平台部署和标准导出包设计。", "content_format": "plain", "published_at": "2026-06-18", "visibility": "public", "is_featured": 1, "sort_order": 3},
        {"uid": "news-student-award", "title": "李四获得研究生科研创新奖", "slug": "student-award-li", "category": "学生", "content": "李四同学围绕可信机器学习与学术知识图谱的研究获得校级研究生科研创新奖。", "content_format": "plain", "published_at": "2026-05-30", "visibility": "public", "is_featured": 1, "sort_order": 4},
        {"uid": "news-course-open", "title": "人工智能系统实践课程资料更新", "slug": "course-open", "category": "课程", "content": "课程新增低资源 Web 系统、Cloudflare Workers 部署和科研数据迁移实践单元。", "content_format": "plain", "published_at": "2026-03-01", "visibility": "public", "is_featured": 0, "sort_order": 5},
        {"uid": "news-alumni-update", "title": "毕业生去向与团队校友信息更新", "slug": "alumni-update", "category": "校友", "content": "网站新增毕业生去向、学生动态和校友留言维护入口，便于长期记录团队成长。", "content_format": "plain", "published_at": "2026-01-12", "visibility": "public", "is_featured": 0, "sort_order": 6},
    ],
    "courses": [
        {"uid": "course-research-method", "name": "科研方法与论文写作", "semester": "2026 秋", "audience": "研究生", "summary": "训练文献检索、实验设计、论文结构和学术表达。", "visibility": "public", "is_featured": 1, "sort_order": 2},
        {"uid": "course-web-engineering", "name": "Web 系统工程实践", "semester": "2026 春", "audience": "高年级本科生", "summary": "覆盖静态站点、轻量后台、数据导出、Ubuntu 与 Cloudflare 双部署。", "visibility": "public", "is_featured": 1, "sort_order": 3},
        {"uid": "course-learning-analytics", "name": "学习分析与教育数据挖掘", "semester": "2025 秋", "audience": "研究生", "summary": "介绍学习行为数据采集、建模、可解释评价和隐私保护。", "visibility": "public", "is_featured": 0, "sort_order": 4},
        {"uid": "course-ai-safety", "name": "可信人工智能专题", "semester": "2025 春", "audience": "博士生", "summary": "讨论鲁棒性、可解释性、公平性和安全评测。", "visibility": "public", "is_featured": 0, "sort_order": 5},
        {"uid": "course-python-tools", "name": "Python 科研工具开发", "semester": "2024 秋", "audience": "研究生", "summary": "围绕数据清洗、Excel 导入导出、文档自动化和轻量 Web 工具开发。", "visibility": "public", "is_featured": 0, "sort_order": 6},
    ],
    "messages": [
        {"uid": "msg-demo-001", "name": "刘同学", "email": "liustudent@example.com", "message_type": "recruiting", "subject": "咨询硕士招生方向", "content": "老师您好，我对低资源 Web 系统和教育数据挖掘方向感兴趣，想了解明年硕士招生计划。", "status": "new", "visibility": "staff"},
        {"uid": "msg-demo-002", "name": "企业合作联系人", "email": "partner@example.com", "message_type": "cooperation", "subject": "边缘智能系统合作", "content": "希望就低 CPU 边缘应用部署和科研数据治理方向开展合作交流。", "status": "read", "visibility": "staff"},
        {"uid": "msg-demo-003", "name": "课程学生", "email": "course@example.com", "message_type": "course", "subject": "课程资料访问", "content": "请问人工智能系统实践课程的实验模板是否可以提前下载？", "status": "replied", "visibility": "staff"},
        {"uid": "msg-demo-004", "name": "会议秘书", "email": "conf@example.org", "message_type": "paper", "subject": "邀请作报告", "content": "邀请团队介绍学术个人网站双平台部署与迁移实践。", "status": "new", "visibility": "staff"},
        {"uid": "msg-demo-005", "name": "校友", "email": "alumni@example.net", "message_type": "other", "subject": "更新毕业去向", "content": "希望将毕业去向更新为高校教师，并补充主页链接。", "status": "archived", "visibility": "staff"},
        {"uid": "msg-demo-006", "name": "访问学生", "email": "visitor@example.edu", "message_type": "recruiting", "subject": "联合培养咨询", "content": "想了解联合培养学生参与项目和论文工作的方式。", "status": "new", "visibility": "staff"},
    ],
    "media_assets": [
        {"uid": "media-course-syllabus", "object_key": "courses/ai-system-syllabus.pdf", "title": "人工智能系统实践课程大纲", "category": "courses", "mime_type": "application/pdf", "size": 0, "status": "active"},
        {"uid": "media-project-summary", "object_key": "projects/reliable-ai-summary.pdf", "title": "可靠人工智能项目简介", "category": "projects", "mime_type": "application/pdf", "size": 0, "status": "active"},
        {"uid": "media-news-cover", "object_key": "default/site-logo.png", "title": "动态默认封面", "category": "news", "mime_type": "image/png", "size": 0, "status": "active"},
    ],
    "translation_cache": [
        {"uid": "trans-site-title", "source_hash": "site-title", "source_ref_key": "site_settings.site_name", "source_text": "教师个人与团队网站", "source_lang": "zh", "target_lang": "en", "translated_text": "Teacher Personal and Research Group Website", "provider": "manual", "status": "success", "is_manual": 1, "is_current": 1, "source_refs": "site_settings:site-default"},
        {"uid": "trans-nav-team", "source_hash": "nav-team", "source_ref_key": "navigation_items.nav-team", "source_text": "团队", "source_lang": "zh", "target_lang": "en", "translated_text": "Team", "provider": "manual", "status": "success", "is_manual": 1, "is_current": 1, "source_refs": "navigation_items:nav-team"},
        {"uid": "trans-nav-publications", "source_hash": "nav-publications", "source_ref_key": "navigation_items.nav-publications", "source_text": "论文", "source_lang": "zh", "target_lang": "en", "translated_text": "Publications", "provider": "manual", "status": "success", "is_manual": 1, "is_current": 1, "source_refs": "navigation_items:nav-publications"},
        {"uid": "trans-interest-ai", "source_hash": "interest-ai", "source_ref_key": "research_interests.interest-ai", "source_text": "可靠人工智能", "source_lang": "zh", "target_lang": "en", "translated_text": "Reliable Artificial Intelligence", "provider": "manual", "status": "success", "is_manual": 1, "is_current": 1, "source_refs": "research_interests:interest-ai"},
        {"uid": "trans-news-welcome", "source_hash": "news-welcome", "source_ref_key": "news.news-welcome", "source_text": "新版个人主页启动", "source_lang": "zh", "target_lang": "en", "translated_text": "New Personal Homepage Launched", "provider": "manual", "status": "success", "is_manual": 1, "is_current": 1, "source_refs": "news:news-welcome"},
    ],
}
