from __future__ import annotations

from .security import stable_uid


DEMO_ROWS = {
    "site_settings": [
        {
            "id": 1,
            "uid": "site-default",
            "is_active": 1,
            "site_name": "教师个人与团队网站",
            "hero_title": "面向可靠智能系统的教学与科研",
            "hero_subtitle": "这里展示教师简介、团队成员、论文、项目、专利、课程和新闻动态。后台可维护导航、首页按钮、团队照片和成果内容。",
            "logo_key": "default/site-logo.png",
            "favicon_key": "default/site-logo.png",
            "og_image_key": "default/site-logo.png",
            "seo_title": "教师个人主页",
            "seo_description": "教师个人与团队网站，展示科研项目、论文、专利、学生、课程与动态。",
            "seo_keywords": "教师主页,科研团队,论文,项目,专利,学生",
            "footer_text": "© 2026 教师个人与团队网站",
            "homepage_profile_uid": "profile-main-teacher",
            "homepage_publication_limit": 5,
            "homepage_news_limit": 4,
        }
    ],
    "global_settings": [
        {
            "id": 1,
            "uid": "global-default",
            "allow_public_registration": 0,
            "allow_anonymous_messages": 1,
            "upload_max_size_mb": 10,
            "upload_allowed_extensions": ".jpg,.jpeg,.png,.webp,.svg,.pdf,.doc,.docx,.xls,.xlsx,.csv",
            "media_trash_retention_days": 30,
            "news_pdf_engine": "native",
            "news_pdf_allow_download": 1,
            "publication_metadata_provider": "manual",
            "publication_metadata_providers": "crossref,openalex,semanticscholar",
            "publication_display_style": "gbt",
            "publication_suggestion_cache_seconds": 30,
            "profile_suggestion_cache_seconds": 30,
            "project_suggestion_cache_seconds": 30,
            "patent_suggestion_cache_seconds": 30,
            "student_suggestion_cache_seconds": 30,
            "news_suggestion_cache_seconds": 30,
            "course_suggestion_cache_seconds": 30,
            "translation_provider": "auto",
            "translation_providers": "auto,libretranslate,deepl_free,google_translate,microsoft_translator,mymemory,argos_local",
            "libretranslate_url": "https://translate.terraprint.co",
            "libretranslate_api_key": "",
            "deepl_api_key": "",
            "google_translate_api_key": "",
            "microsoft_translator_key": "",
            "microsoft_translator_region": "",
            "microsoft_translator_endpoint": "",
            "mymemory_email": "",
            "translation_batch_size": 10,
            "translation_worker_count": 4,
            "translation_timeout_seconds": 12,
            "translation_job_state": "",
            "patent_metadata_providers": "patentsview,epo_ops",
            "patentsview_api_key": "",
            "epo_ops_client_id": "",
            "epo_ops_client_secret": "",
        }
    ],
    "navigation_items": [
        {"id": 1, "uid": "nav-home", "title": "首页", "kind": "route", "path": "/", "location": "header", "style": "link", "enabled": 1, "sort_order": 10, "visibility": "public"},
        {"id": 2, "uid": "nav-team", "title": "团队", "kind": "route", "path": "/team", "location": "header", "style": "link", "enabled": 1, "sort_order": 20, "visibility": "public"},
        {"id": 3, "uid": "nav-publications", "title": "论文", "kind": "route", "path": "/publications", "location": "header", "style": "link", "enabled": 1, "sort_order": 30, "visibility": "public"},
        {"id": 12, "uid": "nav-featured-publications", "title": "代表论文", "kind": "route", "path": "/featured-publications", "location": "header", "style": "link", "enabled": 1, "sort_order": 35, "visibility": "public"},
        {"id": 4, "uid": "nav-projects", "title": "项目", "kind": "route", "path": "/projects", "location": "header", "style": "link", "enabled": 1, "sort_order": 40, "visibility": "public"},
        {"id": 5, "uid": "nav-patents", "title": "专利", "kind": "route", "path": "/patents", "location": "header", "style": "link", "enabled": 1, "sort_order": 50, "visibility": "public"},
        {"id": 6, "uid": "nav-students", "title": "学生", "kind": "route", "path": "/students", "location": "header", "style": "link", "enabled": 1, "sort_order": 60, "visibility": "public"},
        {"id": 7, "uid": "nav-news", "title": "动态", "kind": "route", "path": "/news", "location": "header", "style": "link", "enabled": 1, "sort_order": 70, "visibility": "public"},
        {"id": 8, "uid": "nav-contact", "title": "联系", "kind": "route", "path": "/contact", "location": "header", "style": "link", "enabled": 1, "sort_order": 80, "visibility": "public"},
        {"id": 9, "uid": "hero-publications", "title": "查看论文", "kind": "button", "path": "/publications", "location": "home_hero", "style": "primary", "enabled": 1, "sort_order": 10, "visibility": "public"},
        {"id": 10, "uid": "hero-team", "title": "团队成员", "kind": "button", "path": "/team", "location": "home_hero", "style": "secondary", "enabled": 1, "sort_order": 20, "visibility": "public"},
        {"id": 11, "uid": "hero-contact", "title": "联系留言", "kind": "button", "path": "/contact", "location": "home_hero", "style": "ghost", "enabled": 1, "sort_order": 30, "visibility": "public"},
    ],
    "profiles": [
        {
            "id": 1,
            "uid": "profile-main-teacher",
            "name": "张三",
            "role": "教师",
            "title": "教授 / 博士生导师",
            "organization": "某某大学",
            "lab": "智能系统实验室",
            "avatar_key": "default/teacher-male-avatar.png",
            "email": "teacher@example.edu.cn",
            "office": "理工楼 A-501",
            "bio": "长期从事智能系统、可靠机器学习与教育数字化方向研究，欢迎对科研和工程实现都有兴趣的同学加入团队。",
            "education": "博士，某某大学计算机科学与技术。",
            "experience": "主持多项国家级和省部级科研项目。",
            "recruiting": "招收机器学习、软件工程、教育技术方向博士和硕士研究生。",
            "orcid": "0000-0000-0000-0000",
            "google_scholar": "https://scholar.google.com/",
            "github": "https://github.com/",
            "contact_visibility": "public",
            "visibility": "public",
            "is_active": 1,
            "is_featured": 1,
            "sort_order": 1,
        },
        {
            "id": 2,
            "uid": "profile-member-li",
            "name": "李四",
            "role": "博士生",
            "title": "2024 级博士研究生",
            "organization": "某某大学",
            "avatar_key": "default/teacher-male-avatar.png",
            "email": "student@example.edu.cn",
            "bio": "研究方向为可信机器学习与学术知识图谱。",
            "visibility": "public",
            "is_active": 1,
            "is_featured": 1,
            "sort_order": 20,
        },
    ],
    "research_interests": [
        {"id": 1, "uid": "interest-ai", "name": "可靠人工智能", "description": "模型可靠性、可解释性与鲁棒性。", "sort_order": 1, "visibility": "public"},
        {"id": 2, "uid": "interest-edu", "name": "教育数字化", "description": "学习分析、教学资源智能组织与评价。", "sort_order": 2, "visibility": "public"},
        {"id": 3, "uid": "interest-system", "name": "轻量系统工程", "description": "低资源部署、边缘计算与 Web 系统。", "sort_order": 3, "visibility": "public"},
    ],
    "publications": [
        {
            "id": 1,
            "uid": stable_uid("pub", "Reliable AI Systems for Education 2026"),
            "title": "Reliable AI Systems for Education",
            "authors": "San Zhang; Si Li",
            "venue": "Journal of Educational Intelligence",
            "year": 2026,
            "volume": "12",
            "issue": "1",
            "pages": "15-28",
            "doi": "10.0000/example.2026.001",
            "citation_gbt": "Zhang S, Li S. Reliable AI Systems for Education[J]. Journal of Educational Intelligence, 2026.",
            "citation_elsevier": "[1] S. Zhang, S. Li, Reliable AI systems for education, Journal of Educational Intelligence (2026). https://doi.org/10.0000/example.2026.001.",
            "citation_apa": "Zhang, S., & Li, S. (2026). Reliable AI Systems for Education. Journal of Educational Intelligence.",
            "citation_ieee": "S. Zhang and S. Li, \"Reliable AI Systems for Education,\" Journal of Educational Intelligence, 2026.",
            "publication_type": "期刊论文",
            "author_role": "corresponding",
            "index_type": "SCI",
            "display_tags": "期刊论文, SCI",
            "keywords": "AI; education; reliability",
            "visibility": "public",
            "pdf_visibility": "public",
            "is_featured": 1,
            "sort_order": 1,
        }
    ],
    "projects": [
        {"id": 1, "uid": "project-reliable-ai", "name": "面向教育场景的可靠人工智能系统", "source": "国家自然科学基金", "project_number": "NSFC-000000", "principal": "张三", "members": "李四", "start_date": "2026-01-01", "end_date": "2029-12-31", "status": "在研", "summary": "研究低资源、高可靠、可解释的教育智能系统。", "visibility": "public", "is_featured": 1, "sort_order": 1}
    ],
    "patents": [
        {"id": 1, "uid": "patent-ai-platform", "name": "一种教学资源智能组织方法及系统", "country": "中国", "patent_type": "发明专利", "application_number": "CN000000000", "application_date": "2026-03-18", "inventors": "张三; 李四", "owner": "某某大学", "legal_status": "申请中", "visibility": "public", "is_featured": 1, "sort_order": 1}
    ],
    "students": [
        {"id": 1, "uid": "student-li-si", "name": "李四", "avatar_key": "default/student-male-avatar.png", "degree": "博士", "category": "在读博士", "grade": "2024", "direction": "可信机器学习", "status": "在读", "email": "student@example.edu.cn", "bio": "关注可靠机器学习与知识图谱。", "visibility": "public", "contact_visibility": "public", "is_featured": 1, "sort_order": 1}
    ],
    "student_category_displays": [
        {"id": 1, "uid": "cat-phd", "key": "phd", "label": "在读博士", "keywords": "博士,phd", "enabled": 1, "display_order": 1},
        {"id": 2, "uid": "cat-master", "key": "master", "label": "在读硕士", "keywords": "硕士,master", "enabled": 1, "display_order": 2},
        {"id": 3, "uid": "cat-alumni", "key": "alumni", "label": "毕业生", "keywords": "毕业,校友,alumni", "enabled": 1, "display_order": 3},
    ],
    "news": [
        {"id": 1, "uid": "news-welcome", "title": "新版个人主页启动", "slug": "welcome", "category": "网站", "content": "新版网站支持 Cloudflare Workers 与 Ubuntu 双平台部署，并提供标准导出包便于迁移。", "content_format": "plain", "published_at": "2026-08-14", "visibility": "public", "is_featured": 1, "sort_order": 1}
    ],
    "courses": [
        {"id": 1, "uid": "course-ai-system", "name": "人工智能系统实践", "semester": "2026 春", "audience": "研究生", "summary": "面向科研训练的 AI 系统工程课程。", "visibility": "public", "is_featured": 1, "sort_order": 1}
    ],
    "messages": [],
    "media_assets": [
        {"id": 1, "uid": "media-site-logo", "object_key": "default/site-logo.png", "title": "网站默认图标", "category": "default", "mime_type": "image/png", "size": 340684, "storage_kind": "static", "status": "active"},
        {"id": 2, "uid": "media-teacher-default-avatar", "object_key": "default/teacher-male-avatar.png", "title": "教师默认头像", "category": "default", "mime_type": "image/png", "size": 11819, "storage_kind": "static", "status": "active"},
        {"id": 3, "uid": "media-student-default-avatar", "object_key": "default/student-male-avatar.png", "title": "学生默认头像", "category": "default", "mime_type": "image/png", "size": 10567, "storage_kind": "static", "status": "active"},
    ],
    "translation_cache": [],
}
